### ISSUE TITLE
Filter query not working correctly

### ISSUE THREAD

**Issue by karthikhebbar** [ecederstrand/exchangelib#583] opened 2019-04-29 12:34 UTC
Filter query not working correctly if there are international characters.

> Query: Received: > 2019-04-19 17:51:32 AND from:∂åß¬∆˚∂å…ß∂@gmail.com AND subject:From - International Characters AND hasattachment:true Attachment:Test.docx

I am not getting any output for above filter query, however if i remove subject from above query it gives me correct results.  

> Query:  Received: > 2019-04-19 17:51:05 AND from:∂åß¬∆˚∂å…ß∂@gmail.com AND hasattachment:true Attachment:Test.docx

If all values are just plain english character for example query like it gives me correct output even with subject in place.

> Query: Received: > 2019-04-19 17:57:36 AND from:source@test1.com AND subject:normal AND hasattachment:true Attachment:BRK3215.pptx

Am i doing something wrong or is it a bug ?

**Comment by ecederstrand** [comment] 2019-05-01 08:18
Do you get the same behavior without filtering on Received and attachments, or is that relevant for the issue? Is this a QueryString filter as described in https://msdn.microsoft.com/en-us/library/ee693615.aspx? If so, is it only an issue with QueryString filtering, or do you get the same with e.g. `.filter(subject='∂åß[...]')`? Can you please post your code so it's easier to reproduce?

**Comment by karthikhebbar** [comment] 2019-05-06 02:36
Yep , i am getting same behaviour without filtering on other parameters.
Ex query = Q('subject:From - International Characters') alone also doesn't give any results.

Yes query string is as discribed in link https://msdn.microsoft.com/en-us/library/ee693615.aspx. I got result to many other test queries. Attaching u'' also didn't make a difference

My code is something like below
query_str = 'subject:%s'  % subject
query = Q(query_str)
account.infox.filter(query)
(For other parameters like from, received i used to do AND , example attached in previous comment)

I am using python2 and my exchange server version is 2013

**Comment by karthikhebbar** [comment] 2019-05-06 02:59
[response.txt](https://github.com/ecederstrand/exchangelib/files/3146355/response.txt)

This is debug output if i remove subject from filter query.

**Comment by ecederstrand** [comment] 2019-05-07 13:46
I have tested using this example:

```python
import logging
import random
import string
import time

from exchangelib import Credentials, Account, EWSDateTime, EWSTimeZone, CalendarItem, Message
from exchangelib.util import PrettyXmlHandler

#logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
username, password = 'john@example.com', 'PASSWORD'
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)

def rand_str(length):
    return ''.join(map(lambda i: random.choice(string.ascii_letters + ':.-_æøå∂åß¬∆˚'), range(length)))

subject = rand_str(16).lower()
item = Message(folder=a.inbox, subject=subject).save()

print('Searching for item with subject %r' % subject)
print(a.inbox.filter(subject=subject).count())
print(a.inbox.filter('subject:"%s"' % subject).count())

print('Waiting 10 minutes')
time.sleep(600)
print(a.inbox.filter('subject:"%s"' % subject).count())

item.delete()
```

I seem to consistently get this output:

```python
Searching for item with subject 'umkyøuzåprc_u∂eb'
1
0
Waiting 10 minutes
1
```
I seem to remember reading that `QueryString` filters rely on a search index being populated, so you cannot use this type of filter for items that are very new, but the filter does work eventually.

**Comment by ecederstrand** [comment] 2019-05-07 14:48
Also, I see there's a `ResetCache` attribute on the `QuerySet` element that we don't implement: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype

Maybe it could be of use here.

**Comment by karthikhebbar** [comment] 2019-05-07 15:56
But in my case the mail is like 5-6 days old... Also my subject doesn't
contain international character here, it was in from address. So
international character doesn't seem to be actual cause for the issue
neither cache..

**Comment by karthikhebbar** [comment] 2019-05-07 16:31
I am seeing strange behaviour.
1. If i use query like account.inbox.filter(subject='From - International Characters') - i am getting mail back
2. But if i use filter like account.inbox.filter('subject:From - International Characters') - no results
3. If i use filter like account.inbox.filter('subject:International Characters') - i am getting mail back

Am i missing something ?

**Comment by ecederstrand** [comment] 2019-05-07 18:27
Ah, in that case yes, you got the syntax of AQS wrong. I you have spaces in the value part of a `property:value` filter, you must quote the value, as shown in the "Word phase restriction" section in https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype

**Comment by karthikhebbar** [comment] 2019-05-08 04:22
Oops correct, didn't know about quotes. Now it's working as expected. Thanks !!

I have similar problem with screenshot attachments query that too on exchange server 2013,

Query - received: > 2019-04-28 09:41:40 AND from:source@test1.com AND subject:"Screenshot attachment" AND hasattachment:true
Result - i am getting mail back
Logs - [without_attachment_name.txt](https://github.com/ecederstrand/exchangelib/files/3155472/without_attachment_name.txt)

But with
Query - received: > 2019-04-28 09:43:22 AND from:source@test1.com AND subject:"Screenshot attachment" AND hasattachment:true attachment:Screenshot 2019-05-05 at 8.58.10 PM.png
Result - not receiving mail back
Logs - [output.txt](https://github.com/ecederstrand/exchangelib/files/3155470/output.txt)

Same with attachment alone query
Query - hasattachment:true attachment:Screenshot 2019-05-05 at 8.58.10 PM.png. 
Result - not receiving mail back
Logs - [attachment_alone.txt](https://github.com/ecederstrand/exchangelib/files/3155474/attachment_alone.txt)
 
Here also am i missing something silly ?

**Comment by ecederstrand** [comment] 2019-05-08 05:28
You probably also need to quote the dates and the attachment names.

**Comment by ecederstrand** [comment] 2019-05-09 14:04
Closing. Feel free to re-open if you still think this is a bug in exchangelib.

**Closed by ecederstrand** 2019-05-09 14:04 UTC

**Comment by karthikhebbar** [comment] 2019-05-13 04:34
Quoting didn't help.

**Comment by ecederstrand** [comment] 2019-05-13 06:12
Ok. Do you have any documentation that states that it's possible to search for attachments by filename using AQS?

**Comment by karthikhebbar** [comment] 2019-05-14 03:27
> Ok. Do you have any documentation that states that it's possible to search for attachments by filename using AQS?

https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference//querystring-querystringtype

**Comment by ecederstrand** [comment] 2019-05-14 07:10
I just tested briefly and can't get it to filter on full or partial attachment names, either. It seems like a bug in EWS because the syntax and the generated XML request we send is definitely correct.

**Comment by karthikhebbar** [comment] 2019-05-14 15:11
I have tested this for many sample attachment names. Only for Screenshot files i am facing below issue as of now.

Strange thing is that i see this issue only for exchange version of 2013. It works perfectly for 2016 exchange version. I am also feeling this is bun on exchange side. Can you let me know if this is bug on exchange side by looking into logs. Have attached logs for both 2013 and 2016 exchange servers.
 
[exchange2013.log](https://github.com/ecederstrand/exchangelib/files/3178501/exchange2013.log)
[exchange2016.log](https://github.com/ecederstrand/exchangelib/files/3178502/exchange2016.log)

**Comment by ecederstrand** [comment] 2019-05-14 17:26
I don't know if it makes a difference, but you are missing an `AND` in this part of your query: `hasattachment:true attachment:Screenshot[...]`

**Comment by karthikhebbar** [comment] 2019-05-15 03:18
Tried that as well. Didn't make a difference :-(
