### ISSUE TITLE
how to get ToRecipients information from messages?

### ISSUE THREAD

**Issue by trivita** [ecederstrand/exchangelib#141] opened 2017-06-06 15:52 UTC
``` python
account.inbox.all().only('to_recipients')
```
failed miserably

**Comment by djreynolds922** [comment] 2017-06-07 02:05
```
for item in account.inbox.all():
   print(item.to_recipients)
```

This worked for me. It's unclear to me what you're attempting to do but it seems like it's working for you because account.inbox.all() is a folder object, not an Item object. So you'd have to iterate over the items within the folder object and pull the to_recipients attribute from each item.

**Comment by trivita** [comment] 2017-06-07 04:41
Thanks. But The thing is that only() function will tell server not to include unnecessary part when generating response. Otherwise you will end up retrieving everything from your folders which takes up lots of bandwidth. Where I only need email header information in this specific case.

**Comment by ecederstrand** [comment] 2017-06-07 20:50
There's a bug in the latest release where if you call `.only()` with only complex fields (fields that must be retrieved with a `GetItems` call), we will still only call `FindItems` and these attributes will be `None`. I think I actually committed a fix already. I'll check later unless you beat me to it :-)

**Comment by trivita** [comment] 2017-06-08 19:56
Good to hear. I will report back when I tested it.

**Comment by trivita** [comment] 2017-06-09 06:32
```
Traceback (most recent call last):
  File "ews-fun.py", line 11, in <module>
    for i in account.inbox.all().only('to_recipients', 'subject'):
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\queryset.py", line 161, in __iter__
    for val in result_formatter(self._query()):
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\folders.py", line 287, in find_items
    for i in items:
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 313, in _paged_call
    rootfolder, next_offset = self._get_page(response)
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 336, in _get_page
    rootfolder = self._get_element_container(message=response[0], name='{%s}RootFolder' % MNS)
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Users\trivita\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyForOperation: 属性对此操作无效。 (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="message:ToRecipients" />)
```

I get this. Python 3.6.1. exchangelib 1.9.3. Exchange 2013

**Comment by ecederstrand** [comment] 2017-06-09 06:36
Reopening to make sure this gets fixed.

**Closed** 2017-06-11 21:14 UTC

**Comment by trivita** [comment] 2017-06-12 01:49
Thanks! Read the commit. 😀

**Comment by Ads5740** [comment] 2017-10-09 14:59
Hi, 

Not sure if I'm doing something wrong, getting the same error as above, exchange is 2007 pulled the Git code on 09/10/2017:

my code:
```python
import logging
# This handler will pretty-print and syntax highlight the request and response XML documents
from exchangelib.util import PrettyXmlHandler

logging.basicConfig(filename='test.log',level=logging.DEBUG, handlers=[PrettyXmlHandler()])

import os
from datetime import timedelta
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version
    
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter    
credentials = Credentials(username='username', password='password')
version = Version(build=Build(8, 3, 83, 6))
config = Configuration(server='exchange server', credentials=credentials, version=version, auth_type=NTLM)
account = Account(primary_smtp_address='email', config=config, autodiscover=False, access_type=DELEGATE)
print(account.version)

my_folder=account.inbox
print(my_folder)

for item in my_folder.all():
    for attachment in item.attachments:
        if isinstance(attachment, FileAttachment):
            local_path = os.path.join('C:\test', attachment.name)
            with open(local_path, 'wb') as f:
                f.write(attachment.content)
            print('Saved attachment to', local_path)
        elif isinstance(attachment, ItemAttachment):
            if isinstance(attachment.item, Message):
                print(attachment.item.subject, attachment.item.body)
```

Error log:

c:\Data\RD\Mailbox>python test1.py
Build=8.3.83.6, API=Exchange2007_SP1, Fullname=Microsoft Exchange Server 2007 SP
1
Messages (Inbox)
Traceback (most recent call last):
  File "test1.py", line 27, in <module>
    for item in my_folder.all():
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 197, in __i
ter__
    for val in result_formatter(self._query()):
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 272, in _as
_items
    for i in iterable:
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 393, in fetc
h
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_
fields, shape=IdOnly):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 443, in _po
ol_requests
    elems = r.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
exchangelib.errors.ErrorSchemaValidation: The 'FieldURI' attribute is invalid -
The value 'item:ConversationId' is invalid according to its datatype 'http://sch
emas.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enu
meration constraint failed.

**Comment by ecederstrand** [comment] 2017-10-10 20:06
No. That one is different. Apparently, not many people still use Exchange 2007 since this was not reported before. Anyway, fixed in https://github.com/ecederstrand/exchangelib/commit/d54fa21b8043d599f7fcfac4501a17a40c6aa431

There may be more like these, since I recently added support for many more fields on the master branch. Please report them so we can get Exchange 2007 support back in shape :-)

**Comment by Ads5740** [comment] 2017-10-11 08:02
Hi, thanks for the update.
Ran the code this morning and getting others:

```c:\Data\RD\Mailbox>python test1.py
Build=8.3.83.6, API=Exchange2007_SP1, Fullname=Microsoft Exchange Server 2007 SP
1
Messages (Inbox)
Traceback (most recent call last):
  File "test1.py", line 27, in <module>
    for item in my_folder.all():
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 197, in __i
ter__
    for val in result_formatter(self._query()):
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 272, in _as
_items
    for i in iterable:
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 393, in fetc
h
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_
fields, shape=IdOnly):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 443, in _po
ol_requests
    elems = r.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
exchangelib.errors.ErrorSchemaValidation: The 'FieldURI' attribute is invalid -
The value 'item:IsAssociated' is invalid according to its datatype 'http://schem
as.microsoft.com/exchange/services/2006/types:UnindexedFieldURIType' - The Enume
ration constraint failed.
c:\Data\RD\Mailbox>```

**Comment by Ads5740** [comment] 2017-10-11 08:11
FYI, I tried a similar fix to the previous in the terms of:
```python
BooleanField('is_associated', field_uri='item:IsAssociated', is_read_only=True, supported_from=EXCHANGE_2010),
```
in Items.py line 133

but the new error after the change above is:

```
c:\Data\RD\Mailbox>python test1.py
Build=8.3.83.6, API=Exchange2007_SP1, Fullname=Microsoft Exchange Server 2007 SP
1
Messages (Inbox)
Traceback (most recent call last):
  File "test1.py", line 27, in <module>
    for item in my_folder.all():
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 197, in __i
ter__
    for val in result_formatter(self._query()):
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 272, in _as
_items
    for i in iterable:
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 393, in fetc
h
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_
fields, shape=IdOnly):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 445, in _po
ol_requests
    for elem in elems:
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 272, in _ge
t_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.elemen
t_container_name)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 245, in _ge
t_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 262, in _ra
ise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this o
bject type. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchan
ge/services/2006/types" FieldURI="folder:ParentFolderId" />)

c:\Data\RD\Mailbox>```

**Comment by ecederstrand** [comment] 2017-10-11 08:14
Ok. Can you disable this field and see what else fails?

```python
from exchangelib.version import EXCHANGE_2010
from exchangelib.folders import Messages
Messages.get_item_field_by_fieldname('is_associated').supported_from = EXCHANGE_2010
```

Repeat as necessary. You can search https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/items.py for the corresponding exchangelib field name for any given FieldURI.

**Comment by ecederstrand** [comment] 2017-10-11 08:15
If you're in a hurry, a workaround is to use `my_folder.all().only(list_of_field_names)` to only fetch the fields you need.

**Comment by Ads5740** [comment] 2017-10-11 09:58
Thanks.
I think I may have found a work around, basically same as yours above.
Added:
```python
EWSElementField('parent_folder_id', field_uri='folder:ParentFolderId', value_cls=ParentFolderId,
                        is_read_only=True, supported_from=EXCHANGE_2010),

BooleanField('is_associated', field_uri='item:IsAssociated', is_read_only=True, supported_from=EXCHANGE_2010),
```

and I now get output, thanks for your help

**Comment by ecederstrand** [comment] 2017-10-11 10:09
Are you sure the `parent_folder_id` change is necessary? According to https://msdn.microsoft.com/en-us/library/office/aa494327(v=exchg.150).aspx, it's supported on Exchange 2007.

**Comment by Ads5740** [comment] 2017-10-11 10:15
unfortunately yes:
```
Traceback (most recent call last):
  File "test1.py", line 31, in <module>
    for item in my_folder.filter(subject__contains='FW: New Notice Posted'):
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 197, in __i
ter__
    for val in result_formatter(self._query()):
  File "C:\Python27\lib\site-packages\exchangelib\queryset.py", line 272, in _as
_items
    for i in iterable:
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 393, in fetc
h
    for i in GetItem(account=self).call(items=ids, additional_fields=additional_
fields, shape=IdOnly):
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 445, in _po
ol_requests
    for elem in elems:
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 272, in _ge
t_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.elemen
t_container_name)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 245, in _ge
t_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 262, in _ra
ise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this o
bject type. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchan
ge/services/2006/types" FieldURI="folder:ParentFolderId" />)
```

**Comment by Ads5740** [comment] 2017-10-11 10:15
unless is our environment

**Comment by ecederstrand** [comment] 2017-10-11 10:23
Ah, the field *is* supported but I didn't notice the FieldURI was wrong. This should help: https://github.com/ecederstrand/exchangelib/commit/3609fa23e403821bdc5f80cd896a9df1d73f0275. I fixed the `is_associated` error in https://github.com/ecederstrand/exchangelib/commit/8561bd0f3e6bfd7c8d01bc57cbcc3dca3cf33fc4.

**Comment by Ads5740** [comment] 2017-10-11 10:34
Confirmed working with updates! Thanks a lot :)
