### ISSUE TITLE
Returning calendar entries for current hour

### ISSUE THREAD

**Issue by SynapseCarbon** [ecederstrand/exchangelib#849] opened 2021-01-18 16:30 UTC
I'm connecting to an on-premise Exchange Server using exchangelib and trying to retrieve some calendar entries

I originally put some Python code together on a Windows 10 PC in PyCharm.  That code is using Python 2.7 and exchangelib 2.2 though.

I'm now trying the same code on Ubuntu 20 LTS and Python 3 + exchangelib 3.3.2.  My code is intended to retrieve a maximum of two calendar items for the current hour.

```python
def get_meetings_this_hour():
    my_account = connect_to_exchange()
    current = EWSDateTime(now.year,now.month,now.day,now.hour,00,tzinfo = EWSTimeZone.localzone())
    print (current)
    future = current + datetime.timedelta(minutes=59)
    print (future)
    return list(my_account.calendar.view(start=current, end=future, max_items=2))


print("Time Now: ", now.strftime("%d-%m-%Y %H:%M:%S"))
print (tz)
meetings = get_meetings_this_hour()
if not meetings:
    print ('No meetings')
else:
    for item in meetings:
        print(item.subject, ' - Start: ',  item.start.strftime("%d-%m-%Y %H:%M:%S:%f"))
```

So if I run it now, I have no calendar entries for the current hour (16:00 to 16:59 GMT)  However, it returns an entry called "Test" which is from 15:30.  This is the script results:

```
Time Now:  18-01-2021 16:19:02
Europe/London
2021-01-18 16:00:00+00:00
2021-01-18 16:59:00+00:00
Test  - Start:  18-01-2021 15:30:00:000000
```

I did wonder if it's time zone related, hence printing the system time zone, plus the two times I generate as the view criteria.

What confuses me is that the same code runs as expected on the previous mentioned Windows PC (with the older libraries).  Am I missing something obvious?

**Comment by ecederstrand** [comment] 2021-01-18 22:13
What is the end time of the meeting that is returned? I believe that a calendar view will include all items that overlap with the date range of the view. It could be that there is indeed an overlap.

Also, try printing just `item.start` instead of formatting it, to be sure that you also get the timezone offset in the output.

**Comment by SynapseCarbon** [comment] 2021-01-22 12:18
A bit more digging has turned up what I think is catching me out.  On my W10 PC with Python 2.7 and exchangelib 2.2 (which needs upgrading), this code:

`    current = EWSDateTime(now.year,now.month,now.day,now.hour,0,tzinfo = EWSTimeZone.localzone())
`

returns:

`2021-01-22 12:00:00-00:01`

On Ubuntu with Python 3 and exchangelib 3.3.2

`current = EWSDateTime(now.year,now.month,now.day,now.hour,0,tzinfo = EWSTimeZone.localzone())
`

returns

`2021-01-22 11:00:00+00:00`

What is the "-00:01" part of the first timestamp?  A timezone offset or a fraction of a second?  Either way, it's enough to exclude items from the "previous" hour (which ran to 11:00).  Simple fix would seem to be to start the current hour at 1 second past.

**Comment by ecederstrand** [comment] 2021-01-22 13:47
Ah, that's because in exchangelib 2.2, `EWSTimeZone` was based on `pytz` where this way of creating timezone-aware dates is not supported. You have to use `tz.localize(EWSDateTime(...))`. In exchangelib 3.3, `EWSTimeZone` is based on `zoneinfo` which does support `EWSDateTime`(..., tzinfo=tz)`.

**Comment by ecederstrand** [comment] 2021-01-22 13:49
BTW, the `-00:01` is a timezone offset, but it's a wrong offset caused by the incorrect construction of the `EWSDateTime()` object.

**Comment by ecederstrand** [comment] 2021-01-25 13:57
I think we found the cause of this issue. Closing. Feel free to reopen if you need additional help.

**Closed by ecederstrand** 2021-01-25 13:57 UTC
