### ISSUE TITLE
Can't find specific folder with shared mailbox

### ISSUE THREAD

**Issue by ninSmith** [ecederstrand/exchangelib#420] opened 2018-05-31 22:11 UTC
Hi,

I've added a folder to a shared mailbox.
But when listing all folders with:
```
for f in account.root.walk():
   print(f.name)
```

I can't find it in all folder names returned...

But I clearly see the folder in Outlook, Owa and even when using powershell (```get-mailboxfolderstatistics```).

Am I missing something ?

FYI:

```
exchangelib==1.11.3
Exchange 2016
```

Thanks.

**Comment by ninSmith** [comment] 2018-05-31 22:44
When testing furthermore, it seems that the ```account.root.walk()``` is done on the user mailbox and not on the shared mailbox (I use the user credentials to access the shared mailbox).

Same thing for folder creation:
```
f = Folder(parent=account.inbox, name='testNewFolder')
f.save()
```
The folder is created in the user mailbox, not in the shared mailbox. 

Strange because in ```Account(primary_smtp_address=``` I do put the shared mailbox address.
Moreover, I managed to read emails in the shared mailbox (but in the ```Inbox``` folder only).

I did the account with:

```
config = Configuration(server='ews.foo.bar',
    credentials=Credentials(username='foo.bar\\user001', password='P455w0rd'),
    auth_type=NTLM)

account = Account(primary_smtp_address='shared@foo.bar', config=config, autodiscover=False, access_type=DELEGATE)
```

**Comment by ecederstrand** [comment] 2018-06-04 06:14
I think this is a duplicate of https://github.com/ecederstrand/exchangelib/issues/391. Ugrading to 1.11.4 should fix this for you.

**Closed** 2018-06-04 23:15 UTC

**Comment by ninSmith** [comment] 2018-06-05 10:20
I confirm it worked !
