### ISSUE TITLE
KeyError: 'folders' and Access Denied

### ISSUE THREAD

**Issue by sgauert** [ecederstrand/exchangelib#658] opened 2019-10-16 13:07 UTC
Hello 
I just got a strange error from the exchangelib Version 2.0.1 .
Python is 3.7.3

This is the very basic connection..

```Python
credentials = Credentials(username='user', password='password')

config = Configuration(server='email.domain.de', credentials=credentials)
account = Account(primary_smtp_address='user@domain.de', config=config, credentials=credentials,
                    autodiscover=True, access_type=DELEGATE
                    )

print(account.root.tree())
```

And the trace says:
```cmd
Traceback (most recent call last):
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Ablage\CCM\Code\utils\test.py", line 27, in <module>
    for item in folder.all():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\queryset.py", line 297, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\queryset.py", line 194, in _query
    additional_fields = {FieldPath(field=f) for f in self.folder_collection.allowed_item_fields()}
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 104, in allowed_item_fields
    for item_model in self.supported_item_models:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 110, in supported_item_models
    return tuple(item_model for folder in self.folders for item_model in folder.supported_item_models)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 34, in folders
    return list(self._folders)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\base.py", line 161, in _glob
    for c in self.walk():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 40, in __iter__
    for f in self.folders:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 34, in folders
    return list(self._folders)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\base.py", line 138, in _walk
    for c in self.children:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 40, in __iter__
    for f in self.folders:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 34, in folders
    return list(self._folders)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\roots.py", line 67, in get_children
    for f in self._folders_map.values():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\roots.py", line 148, in _folders_map
    for f in SingleFolderQuerySet(account=self.account, folder=self).depth(self.TRAVERSAL_DEPTH).all():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\queryset.py", line 133, in _query
    for f, complex_f in zip(resolveable_folders, complex_folders):
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 287, in get_folders
    shape=ID_ONLY,
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\get_folder.py", line 31, in call
    shape=shape,
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\common.py", line 373, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\common.py", line 333, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again.
```

So my first guess was that the user or the password might be wrong. They are not. 
If I put in a typo the error message is: `<UnauthorizedError: Wrong username or password for`>

Now what I don't get:
First of all the key error in the dict? 
And then the the combination with the Access is denied.

Can you help me on this one?

**Comment by sgauert** [comment] 2019-10-16 13:19
I just tried it with Kerberos Auth with the following code:
```
import exchangelib
from exchangelib import DELEGATE, Account, Configuration
import logging
from exchangelib.util import PrettyXmlHandler
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
import requests_kerberos
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

def auth_model(**kwargs):
    return requests_kerberos.HTTPKerberosAuth()
exchangelib.transport.AUTH_TYPE_MAP["GSSAPI"] = auth_model
credentials = exchangelib.Credentials("", "")

config = Configuration(service_endpoint='https://ews.msg.hk.xxx.com/ews/exchange.asmx', credentials=credentials, auth_type="GSSAPI")

account = Account(
    primary_smtp_address='name@yyy.com',
    config=config,
    autodiscover=False,
    access_type=DELEGATE)
```

the result however is similar:
```
Traceback (most recent call last):
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\gf32\.vscode\extensions\ms-python.python-2019.10.41019\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Ablage\CCM\Env\Python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Ablage\CCM\Code\utils\testKerberos.py", line 23, in <module>
    Broker = account.inbox / 'Broker'
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\base.py", line 629, in __truediv__
    for c in self.children:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 40, in __iter__
    for f in self.folders:
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 34, in folders
    return list(self._folders)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\roots.py", line 67, in get_children
    for f in self._folders_map.values():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\roots.py", line 148, in _folders_map
    for f in SingleFolderQuerySet(account=self.account, folder=self).depth(self.TRAVERSAL_DEPTH).all():
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\queryset.py", line 133, in _query
    for f, complex_f in zip(resolveable_folders, complex_folders):
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\folders\collections.py", line 287, in get_folders
    shape=ID_ONLY,
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\get_folder.py", line 31, in call
    shape=shape,
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\common.py", line 373, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Ablage\CCM\venvs\test\lib\site-packages\exchangelib\services\common.py", line 333, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again.

**Comment by sgauert** [comment] 2019-10-17 09:13
I just checked it with an older version of the exchangelib.
with Version 1.12.1 the code works

```
credentials = Credentials(username='user', password='password')

config = Configuration(server='email.domain.de', credentials=credentials)
account = Account(primary_smtp_address='user@domain.de', config=config, credentials=credentials,
                    autodiscover=True, access_type=DELEGATE
                    )

print(account.root.tree())
```
Seems there is a different behaviour in the versions?

**Comment by ecederstrand** [comment] 2019-10-18 05:24
I think this is a duplicate of https://github.com/ecederstrand/exchangelib/issues/610 Can you test the workaround posted there?

**Comment by sgauert** [comment] 2019-10-21 08:42
You are right.
If i use your suggested monkey patch of the folder it works.
But why does it work with 1.12.1. driesken found this error in that version.
Now for me I have the problem with the newer version 2.0.1

Thanks anyway for your quick response. Sorry it took me so long to retest it. Was off for the weekend.

**Comment by ecederstrand** [comment] 2019-10-24 04:51
No problem. I'm not sure why it works for you in 1.12.1 but not for driesken. I'll have a release out shortly that contains the fix from issue 610.

**Closed by ecederstrand** 2019-10-24 04:51 UTC
