### ISSUE TITLE
Pre defined the IP/Hostname for Exchange WebService

### ISSUE THREAD

**Issue by ccs1910** [ecederstrand/exchangelib#244] opened 2017-09-12 13:27 UTC
Hi... this is not an issue... i just really need a help.

in my case, i am using the exchangelib to connect, send email, manipulate calendar thru my company exchange webservice and i am using Raspberry Pi with LAN Cable.

Because for intranet or exchange web service, i am using LAN Cable and for internet, i am using Wifi.
i am facing problem, because i am using the "auto discover" and i explicitly configure the gateway of my EWS in the Route Table.

question is : how can i set the IP address of my EWS in the exchangelib?

thanks,
Christian CS

**Comment by ecederstrand** [comment] 2017-09-13 07:43
If you want to force the location of your EWS server, don't use autodiscover:

```python
config = Configuration(server='10.0.0.1', credentials=credentials)
account = Account(primary_smtp_address='john@example.com', config=config,
                  autodiscover=False, access_type=DELEGATE)
```

If you're having trouble resolving the correct IP address for your EWS hostname on your multihomed server, then this is a problem outside exchangelib. ou need to look at the DNS settings in your operating system.

**Comment by ecederstrand** [comment] 2017-09-15 08:09
Closing. Please reopen if you still have issues with this :-)

**Closed by ecederstrand** 2017-09-15 08:09 UTC

**Comment by kfjelsted** [comment] 2018-01-08 15:04
I'm getting some errors when I try to install exchangelib (I'm just using "sudo pip install exchangelib"). The attachment shows what came up in the terminal after I ran that command.
[exchangelib install errors.txt](https://github.com/ecederstrand/exchangelib/files/1611929/exchangelib.install.errors.txt)

**Comment by ecederstrand** [comment] 2018-01-08 15:23
It looks like it fails to install the `lxml` package. Are you installing on Linux? In that case, you need to install the `libxml2-dev` and `libxslt-dev` packages for your operating system first, to get `lxml` to compile and install.

**Comment by kfjelsted** [comment] 2018-01-08 15:51
I'm installing on Raspbian, and I managed to get lxml installed now. The lxml errors are now gone when I try again to install exchangelib, but I'm still getting this line:

error in cryptography setup command: Invalid environment marker: python_version < '3'

Is exchangelib not compatible with Python 2?

**Comment by ecederstrand** [comment] 2018-01-08 16:00
exchangelib is compatible with Python2.7, but for some reason the `cryptography` package we depend on is not installable on your machine.

You may have an old version of `pip` that does not understand the syntax of the `setup.py` file that `cryptography` provides. Try running `pip --version`. If you have a version older than 9.0.1, then upgrade it (`pip install -U pip`) and proceed installing exchangelib again.

**Comment by kfjelsted** [comment] 2018-01-08 16:42
Thanks, that helped! I had to manually install cryptography again after updating pip, but that did eventually work. No errors anymore on the exchangelib installation!

**Comment by kfjelsted** [comment] 2018-01-08 18:31
We believe we have the dependencies installed. We are now trying to log into an organization office365 account and it makes it through the discovery. How do we confirm that the credentials actually worked? Is there a log we can check?
What is the best channel to ask these type of questions?
-Kevin

**Comment by ecederstrand** [comment] 2018-01-08 21:07
It's fine to ask here, maybe as a new issue if that makes sense. Some people ask on StackOverflow instead, but it's mostly me answering questions anyway.

If discovery worked, then the credentials are OK. But if you want, you can select something from the account you just connected to:

```python
account = Account(..., autodiscover=True)
print(account.inbox.all().count())
```

**Comment by kfjelsted** [comment] 2018-01-08 22:05
We are attempting the connection from two different platforms.

We have taken the "notifier.py" script and stripped out the notifier Ubuntu
portions. When using Mac OS X, the discovery appears to go into a continuous loop for ever with timeout. upon pressing CTRL-C to interrupt the process, we see the following;
 <<<<python<notifier.py
^CTraceback (most recent call last):
  File "<stdin>", line 67, in <module>
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/account.py", line 74, in __init__
    credentials=credentials)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/autodiscover.py", line 186, in discover
    protocol=protocol)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/autodiscover.py", line 323, in _autodiscover_quick
    return primary_smtp_address, Protocol(service_endpoint=ews_url, credentials=credentials, auth_type=None)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/protocol.py", line 172, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/protocol.py", line 204, in __init__
    name=self.credentials.username)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/exchangelib/transport.py", line 133, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/Users/kfjelsted/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
Kevins-2012-Mac-mini-5:localtests kfjelsted$ >>>>

What other tests do we need to run to narrow down this timeout problem?
On the Raspberry Pi the prompt returns quickly. We put a print statement directly after the discovery block and that statement prints out.  however, we try and print out the data in the inbox  for one message and the structure is empty. We just want to make sure that the credentials did indeed match and that the problem is not with connectivity, or authentication. 
-Kevin

**Comment by ecederstrand** [comment] 2018-01-09 07:39
When you issued the KeyboardInterrupt in the above stack trace, the code was still trying to autodiscover. Autodiscovery can take a really long time on the first try, even a couple of minutes. After that, we cache the most essential information.
