### ISSUE TITLE
Everything on a mail returns None including unique_body.

### ISSUE THREAD

**Issue by ozbrk** [ecederstrand/exchangelib#1173] opened 2023-02-28 08:19 UTC
**Describe the bug**

Hello, I use exhangelib for an email checking application yet some of the mails are just return as contentless. Mails themselves are not contentless but somehow it doesn't appear on the bull mail.body output. 

**To Reproduce**

Since you don't have access to the exchange server in question it is not applicible.

**Expected behavior**

There must be some content on the mail output. 

tzinfo=EWSTimeZone(key='UTC'))

 response_objects=ResponseObjects(accept_item=None

 tentatively_accept_item=None

 decline_item=None

 reply_to_item=ReplyToItem(subject=None

 body=None

 to_recipients=None

 cc_recipients=None

 bcc_recipients=None

 is_read_receipt_requested=None

 is_delivery_receipt_requested=None

 author=None

 reference_item_id=None

 new_body=None

 received_by=None

 received_representing=None)

 forward_item=ForwardItem(subject=None

 body=None

 to_recipients=None

 cc_recipients=None

 bcc_recipients=None

 is_read_receipt_requested=None

 is_delivery_receipt_requested=None

 author=None

 reference_item_id=None

 new_body=None

 received_by=None

 received_representing=None)

 reply_all_to_item=ReplyAllToItem(subject=None

 body=None

 to_recipients=None

 cc_recipients=None

 bcc_recipients=None

 is_read_receipt_requested=None

 is_delivery_receipt_requested=None

 author=None

 reference_item_id=None

 new_body=None

 received_by=None

 received_representing=None)

 cancel_calendar_item=None

 remove_item=None

 post_reply_item=None

 success_read_receipt=None

 accept_sharing_invitation=None)

**Comment by ecederstrand** [comment] 2023-03-01 19:51
Can you please post the code that you use to fetch the problematic messages?

Also, if you [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) you can see the exact data that the server responds with when fetching messages. That will give you an idea whether the issue is caused by the server sending empty fields, od a parsing issue in exchangelib.

**Comment by ozbrk** [comment] 2023-03-01 23:19
Hello @ecederstrand thank you for your response.

Since mods part of the code is confidential I can share you the part that I'm getting none results.

-------------------------------------------------------------------------------------------------------


'


	for i in redacted:
		for s in searchon:
			main_q = s.filter(f"From:{domain} AND Subject:{i} OR From:{domain} AND Content: {i}")
			print(main_q)
			#print([f.name for f in Message.FIELDS])
			if main_q.exists():
				for m in main_q:
					#print(m)
					#print(type(m))
						#print(m.body)
					hit_id.append(i)
					subject_name.append(m.subject)
					author_name.append(m.author.name)
					customer_name.append(selected_customer)
					body = m.body
					reminder_data = m.reminder_message_data
					headers = m.headers
					print(body)
					print(reminder_data)
					print(headers)
			else:
				#print("no hit for" + str(i)) #QUERY CORE DEBUGGER
				pass
'

**Comment by ecederstrand** [comment] 2023-03-02 07:44
It's possible that the item you are trying to print is not a `Message` object. Check the object type with `type(m)`. `m.item_class` can also tell you if this is a different item type.

**Comment by ozbrk** [comment] 2023-03-02 11:21
m is a message object I've checked it. But strange enough the fields that supposed to be populated are returning none on both full m  - I checked it with print(m) - and xml data

**Comment by ecederstrand** [comment] 2023-03-03 20:40
If the server responds with empty fields in the returned XML document, then there's nothing exchange lib can do. That sounds like a bug in Exchange, or a broken record in the backend storage of the server.

Are you sure you haven't added a `.only()` somewhere in your QuerySet?

**Comment by ozbrk** [comment] 2023-03-06 13:07
I'm sure. Bu I use querystring not qeryset

**Comment by ecederstrand** [comment] 2023-03-27 12:51
Closing because I believe this is not an issue with your specific server, not with exchangelib itself. Feel free to reopen if you think otherwise.

**Comment by ecederstrand** [comment] 2023-03-27 12:51
Closing because I believe this is not an issue with your specific server, not with exchangelib itself. Feel free to reopen if you think otherwise.

**Closed by ecederstrand** 2023-03-27 12:51 UTC
