### ISSUE TITLE
Creating an appointment (not meeting) in attendee calendar

### ISSUE THREAD

**Issue by MaxNielsen** [ecederstrand/exchangelib#663] opened 2019-11-04 13:31 UTC
I can create calendar invites:

```
item = CalendarItem(folder=account.calendar, subject='foo')
    item.start = tz.localize(EWSDateTime(year, month, day, hour, 30))
    item.end = tz.localize(EWSDateTime(year, month, day, hour + 1, 15))
    item.required_attendees  = [Attendee(
            mailbox=Mailbox(email_address='email')
        )]
    item.save()  # This gives the item an 'id' and a 'changekey' value
    item.save(send_meeting_invitations=SEND_ONLY_TO_ALL)  # Send a meeting invitation to attendees
```

However, these need to be accepted, I want to create appointments for the attendees that dont have to be accepted. Is this possible?

I figured I use SEND_TO_NONE if I look at MS docs, but that obv only works for the current Account.

There is some info on it here:

https://stackoverflow.com/questions/2419651/using-ews-managed-api-to-create-appointments-for-other-users, it says to use:

`appointment.Save(new FolderId(WellKnownFolderName.Calendar, new Mailbox(_EmailAddress)));`

Not sure how to do that using this lib tho.

**Comment by ecederstrand** [comment] 2019-11-05 07:36
If you want to save the appointment directly to the attendee calendar, you need to connect to that account and save the appointment there:

```python
recipient = Account('recipient@example.com', ...)
item = CalendarItem(folder=recipient.calendar, ...).save()
```

This requires that you have delegate or impersonation access to write to that account, of course.

**Comment by MaxNielsen** [comment] 2019-11-05 12:13
Hi,

I tried the following:

```
recipient = Account('email', config=config, autodiscover=False, access_type=DELEGATE)
    item = CalendarItem(
        folder=recipient.calendar, 
        subject='foo', 
        start=tz.localize(EWSDateTime(year, month, day, hour)),
        end = tz.localize(EWSDateTime(year, month, day, hour + 1))
    ).save(send_meeting_invitations=SEND_TO_NONE)
```
My User has the following permissions for this account:

Roll: Author
CreateItems: The user can create items in the specified folder.
DeleteOwnedItems: The user can only delete items that they created from the specified folder.
EditOwnedItems: The user can only edit items that they created in the specified folder.
FolderVisible: The user can view the specified folder, but can't read or edit items within the specified public folder.
ReadItems: The user can read items within the specified folder.

I still get an error:

> Access is denied. Check credentials and try again., underlying MAPI stream threw exception

**Comment by ecederstrand** [comment] 2019-11-05 12:41
That error looks like a duplicate of https://github.com/ecederstrand/exchangelib/issues/610

**Closed** 2019-11-05 12:53 UTC
