### ISSUE TITLE
Autodiscover Error

### ISSUE THREAD

**Issue by cr1010** [ecederstrand/exchangelib#410] opened 2018-05-14 07:17 UTC
Hi, connection has been functioning as expected then just started getting this error since last Friday. I upgraded exchangelib from 1.10.1 to 1.11.3 but the error still persists. I tried a different O365 account as as well and same error. Do you have any ideas for me to try to resolve? I am using Django 2.0.4

Traceback:

```python
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001FDD5D5D6A8>
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 250, in _try_autodiscover
    email=email, has_ssl=False)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 306, in _autodiscover_hostname
    auth_type = _get_auth_type_or_raise(url=url, email=email, hostname=hostname)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 282, in _get_auth_type_or_raise
    return _get_auth_type(url=url, email=email)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 363, in _get_auth_type
    raise_from(AutoDiscoverFailed('Error guessing auth type: %s' % e), None)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\future\utils\__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)

  File "<string>", line 1, in <module>
exchangelib.errors.AutoDiscoverFailed: Error guessing auth type: HTTPConnectionPool(host='autodiscover.outlook.ms-acdc.office.com', port=80): Max retries exceeded with url: /Autodiscover/Autodiscover.xml (Ca
used by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDD731BBA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\resolver.py", line 215, in __init__
    rdclass, rdtype)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\message.py", line 352, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\resolver.py", line 225, in __init__
    dns.rdatatype.CNAME)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\message.py", line 352, in find_rrset
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])

  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\urls\resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\urls\resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\user\Anaconda3\Scripts\crm\crm\urls.py", line 20, in <module>
    from . import views
  File "C:\Users\user\Anaconda3\Scripts\crm\crm\views.py", line 56, in <module>
    autodiscover=True, access_type=DELEGATE)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\account.py", line 82, in __init__
    credentials=credentials)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 209, in discover
    return _try_autodiscover(hostname=domain, credentials=credentials, email=email)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 257, in _try_autodiscover
    return _try_autodiscover(e.server, credentials, email)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 260, in _try_autodiscover
    hostname_from_dns = _get_canonical_name(hostname='autodiscover.%s' % hostname)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 452, in _get_canonical_name
    canonical_name = resolver.query(hostname).canonical_name.to_unicode().rstrip('.')
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\resolver.py", line 1053, in query
    raise_on_no_answer)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\dns\resolver.py", line 234, in __init__
    raise NoAnswer(response=response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: autodiscover.outlook.ms-acdc.office.com.telstra.com.au. IN A
```

**Comment by ecederstrand** [comment] 2018-05-14 07:59
The autodiscover protocol is a mess and not very easy to implement and debug, unfortunately.

The problem here is that one or more of the steps we took to find the correct server failed, and we finally ran out of steps to try.

There are at least 4 things that can go wrong:

1. We're not following the [autodiscover protocol](http://msdn.microsoft.com/en-us/library/hh352638(v=exchg.140).aspx) 100%. I.e. we have a bug.
2. Your host does not have the right root certificates installed, so TLS verification failed for the destination server when it should have succeeded. If you enable INFO logging on `exchangelib.autodiscover`, you should be able to see the steps that were taken, and which servers were skipped.
3. Your DNS resolver is broken, so we didn't get the results we needed to complete the process.
4. Autodiscover was configured incorrectly by Exchange admins, so autodiscover is simply not possible for your domain name. You can test this by generating an autodiscover report at https://testconnectivity.microsoft.com

Generating the report at https://testconnectivity.microsoft.com should give you a hint about where the problem is.

**Comment by cr1010** [comment] 2018-05-14 22:02
Thanks for your reply. here is the final fail point in the autodiscover test:
Attempting to send an Autodiscover POST request to potential Autodiscover URLs.
Autodiscover settings weren't obtained when the Autodiscover POST request was sent.
Additional Details
Elapsed Time: 84 ms.
Test Steps
The Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml for user calendar3@vfgl3.onmicrosoft.com.
The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
Additional Details
An HTTP 401 Unauthorized response was received from the remote Unknown server. This is usually the result of an incorrect username or password. If you are attempting to log onto an Office 365 service, ensure you are using your full User Principal Name (UPN). HTTP Response Headers: request-id: fac1dc80-265c-4e3a-8b56-4f400bb78066 X-CasErrorCode: UnauthenticatedRequest X-FEServer: SG2PR04CA0151 Content-Length: 0 Cache-Control: private Date: Mon, 14 May 2018 20:59:43 GMT Server: Microsoft-IIS/10.0 WWW-Authenticate: Basic Realm="" X-AspNet-Version: 4.0.30319 X-Powered-By: ASP.NET
Elapsed Time: 84 ms

Could it be possible for autodiscover to be configured incorrectly by Exchange admins given it was previously working, and this is an Office 365 Enterprise E3 Developer Trial account?

Does this error message from the connectivity test provide any further clues as to the issue?

**Comment by cr1010** [comment] 2018-05-15 00:48
I tried with another exchange account (not a E3 Developer Trial account, but still O365) and successfully passed the connectivity test, but still get an error with django:

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000002173FF3D6A8>
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)

  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\urls\resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\django\urls\resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\user\Anaconda3\Scripts\crm\crm\urls.py", line 20, in <module>
    from . import views
  File "C:\Users\user\Anaconda3\Scripts\crm\crm\views.py", line 56, in <module>
    autodiscover=True, access_type=DELEGATE)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\account.py", line 82, in __init__
    credentials=credentials)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 209, in discover
    return _try_autodiscover(hostname=domain, credentials=credentials, email=email)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 257, in _try_autodiscover
    return _try_autodiscover(e.server, credentials, email)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\exchangelib\autodiscover.py", line 275, in _try_autodiscover
    raise_from(AutoDiscoverFailed('All steps in the autodiscover protocol failed'), None)
  File "C:\Users\user\Anaconda3\envs\myDjangoEnv\lib\site-packages\future\utils\__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

**Comment by ecederstrand** [comment] 2018-05-15 07:06
For your first comment, I don't have much to add. The error message from the connectivity test says that the username or password is incorrect, so either you can't log in at all, or the site is incorrectly configured and can't log into the service it's attempting to log in to. I think you'll have to pursue that with official Microsoft support if you're unable to solve it yourself.

Regarding the second issue, where the connectivity test succeeds in autodiscovering, but exchangelib fails: the best way to debug this is to enable enable INFO logging on `exchangelib.autodiscover` and comparing the steps we take with the steps mentioned in the connectivity test report. We're taking a different route somewhere, and ended up running out of steps to try.

**Comment by ecederstrand** [comment] 2018-05-16 19:48
I think this is actually a duplicate of #337

**Closed** 2018-05-16 19:52 UTC
