### ISSUE TITLE
not writing values after 250 rows into csv..

### ISSUE THREAD

**Issue by VishruthBharadwaj** [ecederstrand/exchangelib#946] opened 2021-07-08 09:08 UTC
Am configuring emailid and password in this way:

```python
credentials = Credentials(
    username = emailid,
    password = passwrd
)

config = Configuration(server='outlook.office365.com', credentials=credentials)

outlook = Account(
    primary_smtp_address = emailid,
    config = config,
    autodiscover = False,
    access_type = DELEGATE
)

for item in outlook.inbox.filter(datetime_received__range=(start,end)):
```

there are 3000+ rows which i will add to df..but till 250 rows i get all attribute values after that not showing example message id ..

Howto overcome this?

**Comment by ecederstrand** [comment] 2021-07-11 08:45
Are you saying that after iterating 250 items, the items don't have a `message_id` value? Maybe the following items are not `Message` instances and thus don't have a `message_id` field. Also, I'm not sure that items in Exchange are required to have a `message_id` values.

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:15
> Are you saying that after iterating 250 items, the items don't have a `message_id` value? Maybe the following items are not `Message` instances and thus don't have a `message_id` field. Also, I'm not sure that items in Exchange are required to have a `message_id` values.

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:16
Am saying I will get 1000+ Emails Message text body.
but after 49 items in CSV file.. message id becomes nan and after 99th row..another column become nan..like this..it keep on Getting nan after that..
If there are 1200mesaage..I need all the attributes of it..Till 49rows..it gives all the attributes mentioned in for loop of the script...
So how to overcome this?

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:18
If I add all the data into CSV..Only till 49 ..It gives all the attributes value...But after that..it keeps on giving nan for message id and afte rsome values..another attribute becomes..nan..how to overcome this?

**Comment by ecederstrand** [comment] 2021-07-11 09:20
You haven't posted the code that creates your CSV file, so I can't say if anything is wrong with that part of the code. If something like this keeps on printing the attributes you expected, then the problem is not with exchangelib:

```python
or item in outlook.inbox.filter(datetime_received__range=(start,end)):
    print(item.__class__.__name__, item.id, item.message_id)
```

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:29
mails = outlook.inbox.filter(datetime_received__range=(start,end)):



    
    for item in mails:
  ######### Attributes here #########


![image](https://user-images.githubusercontent.com/64675356/125189979-7825fc00-e26d-11eb-964c-504aeedbb3bf.png)
Like this some attributes keep on becoming nan

Til 49th row it gives all value after that nan

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:31
Attributes will be printed till 49th row..But after that some attributes becomes nan...example importance,sensitivity wrt mails..etc..but text body will be there..but this importance...sensitivity becomes nan wrt that mail...Why is that so?

**Comment by ecederstrand** [comment] 2021-07-11 09:34
It's either because those items don't have a value for those attributes, or because there's a but in the the part of your code that produces the CSV file.

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:36
It has value if i check through mails details...But till 50 it produces proper data but after that it becomes nan..?You can also try once...Like importance,sensitivity,  routing_type

**Comment by VishruthBharadwaj** [comment] 2021-07-11 09:41
item in outlook.inbox.filter(datetime_received__range=(start,end)):
    print(item.__class__.__name__, item.id, item.message_id,**item.importance**,**item.sensitivity,**, **item.sender.routing_type**)


please try mails in start,end having more than 80+ mails..Importance ,routing_type,sensitivity become nan..after 49th or 50th row..You can try this..

**Comment by ecederstrand** [comment] 2021-07-11 09:50
I just tried that, and I cannot reproduce. It prints the attributes just fine. Here's my code:

```python
a = Account(...)
items = list(Message(subject=f'Item {i}') for i in range(100))
a.inbox.bulk_create(items=items)

for item in a.inbox.filter(subject__startswith='Item '):
    print(item.importance, item.sensitivity)

a.inbox.filter(subject__startswith='Item ').delete()
```

**Comment by VishruthBharadwaj** [comment] 2021-07-11 10:03
Can you please try once based on datetime range between start,end..In the  same way..Will it print the value? after 50th item?

Please filter based on start,end (datetime range)


Please help me here

**Comment by VishruthBharadwaj** [comment] 2021-07-11 10:08
item in outlook.inbox.filter(datetime_received__range=(start,end)):
    print(item.sensitivity, item.importance)



Can you please try this for atleast 100mails(rows)
for datetime range like this..
Am working on this..
Do it prints the value for you for more than 50+ mails?

**Comment by VishruthBharadwaj** [comment] 2021-07-11 10:29
Thanks ecederstrand ..
Will try as per you said .
I think in writing to data frame there is some mistake in code.
Will get back if I get any issue..
Thanks a lot.

**Comment by ecederstrand** [comment] 2021-07-11 10:31
I get the same result. If you want to dig a bit deeper into this, you can check whether EWS actually sends correct values for the items you are fetching from the server. To do this, enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting). You may want to use `.only('sensitivity', 'importance', ...)` to cut down on the amount of data transferred so you can more clearly see the information you're interested in.

**Comment by VishruthBharadwaj** [comment] 2021-07-11 10:33
Okay thanks a lot.
Will dig a bit tomorrow .
Happy day

**Comment by VishruthBharadwaj** [comment] 2021-07-13 05:47
Hi @ecederstrand ,
This issue got reolved but am getting warning of 
**DeprecationWarning: replace tz.localize() with dt.replace(tzinfo=tz)
end            = outlook.default_timezone.localize(EWSDateTime.from_datetime(to_date))**

What need to be used for this? it wont work if i use dt.replace(tzinfo=tz) ews wont  support

**Comment by ecederstrand** [comment] 2021-07-13 06:49
`tz` and `dt` in the warning message refer to `EWSTimeZone` and `EWSDateTime` instances, respectively. So you would rewrite your code as:

```python
# Old
outlook.default_timezone.localize(EWSDateTime.from_datetime(to_date))
# New
EWSDateTime.from_datetime(to_date).replace(tzinfo=outlook.default_timezone)

```

**Comment by VishruthBharadwaj** [comment] 2021-07-14 07:05
Thanks @ecederstrand

**Closed** 2021-07-14 07:05 UTC
