### ISSUE TITLE
folder:UnreadCount not supported on Exchange 2010?

### ISSUE THREAD

**Issue by mmmmaister** [ecederstrand/exchangelib#352] opened 2018-03-01 19:57 UTC
Hi ecederstrand, 

I'm trying to access the calendar of my account. I was able to get the calendar items through account.root,get_folder_by_name('Calendar'). But when I tried to directly pull the calendar view to get availability at a certain time. It returned error as below. Wondering if you know what is the reason for that. Really appreciate it!

Thank you so much!

```
Traceback (most recent call last)
C:\ProgramData\Anaconda\lib\site-packages\cached_property.py in __get__(self, obj, cls)
     49                 # check if the value was computed before the lock was acquired
---> 50                 return obj_dict[name]
     51             except KeyError:

KeyError: 'calendar'

During handling of the above exception, another exception occurred:

ErrorInvalidPropertyRequest               Traceback (most recent call last)
<ipython-input-45-8bf1ed0c630e> in <module>()
      2 start_dt = ts.localize(EWSDateTime(2018, 3,1,14,0)),
      3 end_dt = ts.localize(EWSDateTime(2018, 3, 1,14,30))
----> 4 account.calendar.view(start=start_dt, end=end_dt)

C:\ProgramData\Anaconda\lib\site-packages\cached_property.py in __get__(self, obj, cls)
     51             except KeyError:
     52                 # if not, do the calculation and release the lock
---> 53                 return obj_dict.setdefault(name, self.func(obj))
     54 
     55 

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\account.py in calendar(self)
    149         # Attempt not to return one of those. An account may not always have a calendar called "Calendar", but a
    150         # Calendar folder with a localized name instead. Return that, if it's available.
--> 151         return self.root.get_default_folder(Calendar)
    152 
    153     @threaded_cached_property

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\folders.py in get_default_folder(self, folder_cls)
    735             # Get the default folder
    736             log.debug('Testing default %s folder with GetFolder', folder_cls)
--> 737             f = folder_cls.get_distinguished(account=self.account)
    738             return self._folders_map.get(f.folder_id, f)  # Use cached instance if available
    739         except ErrorAccessDenied:

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\folders.py in get_distinguished(cls, account)
    619     def get_distinguished(cls, account):
    620         assert cls.DISTINGUISHED_FOLDER_ID
--> 621         folders = list(cls.get_folders(account=account, ids=[cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID)]))
    622         if not folders:
    623             raise ErrorFolderNotFound('Could not find distinguished folder %s' % cls.DISTINGUISHED_FOLDER_ID)

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\folders.py in get_folders(cls, account, ids, additional_fields)
    610                 folders=ids,
    611                 additional_fields=additional_fields,
--> 612                 shape=IdOnly
    613         ):
    614             if isinstance(elem, Exception):

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\services.py in _get_elements_in_response(self, response)
    281         for msg in response:
    282             assert isinstance(msg, ElementType)
--> 283             container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
    284             if isinstance(container_or_exc, ElementType):
    285                 for c in self._get_elements_in_container(container=container_or_exc):

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\services.py in _get_element_container(self, message, name)
    254         # rspclass == 'Error', or 'Success' and not 'NoError'
    255         try:
--> 256             self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
    257         except self.ERRORS_TO_CATCH_IN_RESPONSE as e:
    258             return e

C:\ProgramData\Anaconda\lib\site-packages\exchangelib\services.py in _raise_errors(cls, code, text, msg_xml)
    271         try:
    272             # Raise the error corresponding to the ResponseCode
--> 273             raise vars(errors)[code](text)
    274         except KeyError:
    275             # Should not happen

ErrorInvalidPropertyRequest: Property is not valid for this object type. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="folder:UnreadCount" />)
```

**Comment by ecederstrand** [comment] 2018-03-01 21:53
https://msdn.microsoft.com/en-us/library/office/aa581334(v=exchg.140).aspx doesn't mention that `UnreadCount` is only valid for some Exchange versions, so this is a bit surprising.

Which version of Exchange is this? You can find out with `print(account.protocol.version)`

**Comment by mmmmaister** [comment] 2018-03-02 20:56
Here's the version: Build=14.0.7192.500, API=Exchange2010, Fullname=Microsoft Exchange Server 2010

**Comment by mmmmaister** [comment] 2018-03-07 15:36
Thanks! it worked!!

**Comment by ecederstrand** [comment] 2018-03-07 15:47
Well, that's absurd. The field is explicitly documented as supported on Exchange 2010. See https://msdn.microsoft.com/en-us/library/office/aa494315(v=exchg.140).aspx and https://msdn.microsoft.com/en-us/library/office/aa580965(v=exchg.140).aspx

We can mark the field as not supported on Exchange 2010, but I'd like at least *some* other confirmation that this isn't just a peculiarity with your exact Exchange server.

**Comment by BenJoParadise** [comment] 2018-06-20 14:12
My thoughts exactly! The question is, how should this difference in configuration be handled by exchangelib?

**Comment by ecederstrand** [comment] 2018-06-20 14:28
I don't think exchangelib should handle this automatically until we have a much better idea about what causes this.

For now, I would suggest handling this in your client code. Connect to the server and read the `unread_count` attribute for an arbitrary folder. If that fails, then apply the workaround mentioned in https://github.com/ecederstrand/exchangelib/issues/352#issuecomment-370706598 (but only do it once!) and try again.

**Comment by mehdi-erroussafi** [comment] 2018-06-26 12:12
Dear All,

Sorry for the very newbie comment, but I'm encountring the same error (just discovered your project).

`Traceback (most recent call last):
  File "mail.py", line 29, in <module>
    for item in account.inbox.all().order_by('-datetime_received')[:10]:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\account.py", line 193, in inbox
    return self.root.get_default_folder(Inbox)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\folders.py", line 965, in get_default_folder
    for f in self._folders_map.values():
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\folders.py", line 928, in _folders_map
    for f in FolderCollection(account=self.account, folders=distinguished_folders).get_folders():
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 1053, in call
    shape=shape,
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 330, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 303, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertyRequest: Propriété non valide pour ce type d'objet. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="folder:UnreadCount" />)`

my env is the following : 

Build=8.3.213.0, API=Exchange2007_SP1, Fullname=Microsoft Exchange Server 2007 SP1

Tried the workaround and now i'm getting the error on another field :

`[IdField(name='folder_id', value_cls=<class 'str'>, is_list=False, is_complex=False, default=None), IdField(name='changekey', value_cls=<class 'str'>, is_list=False, is_complex=False, default=None), EWSElementField(name='parent_folder_id', value_cls=<class 'exchangelib.properties.ParentFolderId'>, is_list=False, is_complex=False, default=None), TextField(name='folder_class', value_cls=<class 'str'>, is_list=False, is_complex=True, default=None), TextField(name='name', value_cls=<class 'str'>, is_list=False, is_complex=True, default=None), IntegerField(name='total_count', value_cls=<class 'int'>, is_list=False, is_complex=False, default=None), IntegerField(name='child_folder_count', value_cls=<class 'int'>, is_list=False, is_complex=False, default=None), EffectiveRightsField(name='effective_rights', value_cls=<class 'exchangelib.properties.EffectiveRights'>, is_list=False, is_complex=False, default=None)]
Traceback (most recent call last):
  File "mail.py", line 32, in <module>
    for item in account.inbox.all().order_by('-datetime_received')[:10]:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\queryset.py", line 311, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\queryset.py", line 390, in _as_items
    for i in iterable:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\account.py", line 629, in fetch
    shape=IdOnly,
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 608, in _pool_requests
    for elem in elems:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 330, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\services.py", line 303, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertyRequest: Propriété non valide pour ce type d'objet. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:MeetingTimeZone" />)`

**Comment by mehdi-erroussafi** [comment] 2018-06-26 13:01
@ecederstrand 

Thank you, i understand now the logic. Except i'm now getting other error in lib functions 

```python
Build=8.3.213.0, API=Exchange2007_SP1, Fullname=Microsoft Exchange Server 2007 SP1
Traceback (most recent call last):
  File "mail.py", line 46, in <module>
    for item in account.inbox.all().order_by('-datetime_received')[:10]:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\queryset.py", line 311, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\queryset.py", line 390, in _as_items
    for i in iterable:
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\account.py", line 625, in fetch
    additional_fields = validation_folder.validate_fields(fields=only_fields)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\exchangelib\folders.py", line 561, in validate_fields
    meeting_tz_field, start_tz_field, end_tz_field = CalendarItem.timezone_fields()
ValueError: not enough values to unpack (expected 3, got 2)
```

I would like to know, why calendar items are being parsed. I'm actually trying to get the simple list 100 items in example code of the library working. Is there a way to prevent calendar/timezones for being processed and only process mails in inbox ?

thank you again for your kind comments on the issue.

**Comment by ecederstrand** [comment] 2018-06-27 06:32
@mehdi-erroussafi Ok, that didn't work out as planned. Other parts of the code depends on `_meeting_timezone` being available.

The reason we are parsing calendar item fields is that an inbox folder can contain many item types - messages, tasks, calendar items etc. When you run `account.inbox.all()` we as the server to give us all fields for all items in the inbox folder. That includes asking for calendar item fields even though your inbox may only contain messages.

Sa you can see in https://github.com/ecederstrand/exchangelib/blob/8adaee98f6227aa0de199a362d8bb9c96e51cf57/exchangelib/items.py#L571 calendar items have three different timezone fields. `_meeting_timezone` is documented as supported only in Exchange 2007, while the other two are supported from Exchange 2010 and up. It's possible your Exchange 2007 server supports the `_start_timezone` and `_end_timezone` fields after all, for some reason.

There isn't a simple way to change the way timezone fields are selected depending on the version, but you can avoid fetching the timezone fields by using `account.inbox.all().only('subject', 'body', 'datetime_received', ...)` to request only the fields you need.

**Comment by ecederstrand** [comment] 2018-08-03 08:36
Closing. Feel free to reopen if you think there's more we can do in exchangelib to work around these issues :-)

**Closed by ecederstrand** 2018-08-03 08:36 UTC

**Comment by Florent0589** [comment] 2020-08-17 13:15
account.inbox.all().only('subject', 'body', 'datetime_received', ...)

This has worked on me, thank you,  really struggled for sometime

**Comment by dbreese-keystone** [comment] 2020-10-28 22:28
Let me know if I should open a new request instead -- this issue also seems to be on my Exchange 2007 (build 8.3.485.1).  A couple of fields are apparently not supported.  Code to reproduce:

```python
credentials = Credentials(username='DOMAIN\\user', password='secret123')
version = Version(build=Build(8, 3, 485, 1))
config = Configuration(server='mail.example.com', credentials=credentials, version=version)
my_account = Account(primary_smtp_address='user@example.com', config=config, autodiscover=False, access_type=DELEGATE)
print(a.root.tree())  # Errors out
```

I fixed 2 missing fields, and the last statement now works:

```python
from exchangelib.folders import Folder
for i, f in enumerate(Folder.FIELDS):
    if f.name == 'unread_count' or f.name == 'permission_set':
        Folder.FIELDS.pop(i)
print(a.root.tree())  # Works fine
```

**Comment by ecederstrand** [comment] 2020-10-29 06:40
That's weird. Your Exchange version is 2007 SP3 according to https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019

According to https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/folder, UnreadCount is supported for all versions of Exchange, and PermissionSet was introduced in 2007 SP1. This is also what we define for these fields in https://github.com/ecederstrand/exchangelib/blob/6efe0abc2354cfc49366190521b700a1352b6879/exchangelib/folders/base.py#L558

So my best bet is that you have an Exchange server that is somehow broken. And in that case, I think you should just continue with the workaround:

```python
for i, f in enumerate(Folder.FIELDS):
    if f.name in ('unread_count', 'permission_set'):
        Folder.FIELDS.pop(i)
```

**Comment by dbreese-keystone** [comment] 2020-10-29 14:34
"somehow broken" I will absolutely _not_ contest that!  :)  The workaround fully satisfies my needs.  Many thanks to you and everyone in this thread for helping identify it.

One last odd note, I can't figure out why, but your more succinct workaround code `if f.name in ('unread_count', 'permission_set'):` does not seem to work for me.  For some reason, anything short of running two separate for loops (as below) seems to result in the former field `unread_count` getting successfully removed, but not the latter field `permission_set`:

```
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type. (field: FieldURI(field_uri='folder:PermissionSet'))
```

The work-around code that does work for me:

```python
for i, f in enumerate(Folder.FIELDS):
    if f.name == 'unread_count':
        Folder.FIELDS.pop(i)
for i, f in enumerate(Folder.FIELDS):
    if f.name == 'permission_set':
        Folder.FIELDS.pop(i)
```

This could also be something I'm doing wrong.  And regardless, you have given me what I need already to make my code work.  So I'm posting this note just in case it helps you or anyone else.  Cheers!

**Comment by ecederstrand** [comment] 2020-10-29 14:50
Sorry! I tried to shorten the workaround but introduced an embarrassing bug along the way. Never change a list while iterating over it!
