### ISSUE TITLE
File Attachment

### ISSUE THREAD

**Issue by Ads5740** [ecederstrand/exchangelib#363] opened 2018-03-14 14:20 UTC
Hi, 

Not sure if this has been covered before, I'm having issues with attaching an attachment, this may be due to our exchange version:

```python
# Connect to exchange mailbox   
    credentials = Credentials(username=username, password=password)
    version = Version(build=Build(8, 3, 83, 6))
    config = Configuration(server=server, credentials=credentials, version=version, auth_type=NTLM)
    account = Account(primary_smtp_address=email, config=config, autodiscover=False, access_type=DELEGATE)

m = Message(
            account=account,
            subject='For Action', 
            body='All bodies are beautiful', 
            to_recipients=[Mailbox(email_address=email)])
with open (file, 'rb') as f:
my_file = FileAttachment(name=filename, content=f.read().encode('utf-8'))
m.attach(my_file)
m.send()
```
error:

```
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 580, in send
    res = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=s
end_meeting_invitations)
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 204, in _creat
e
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 241, in bulk
_create
    send_meeting_invitations=send_meeting_invitations,
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 235, in <gen
expr>
    i if isinstance(i, Exception)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 445, in _po
ol_requests
    for elem in elems:
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 272, in _ge
t_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.elemen
t_container_name)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 245, in _ge
t_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 262, in _ra
ise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property.
(field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/
2006/types" FieldURI="item:Attachments" />)
 ```

the details for email addresses, etc are set further up the script. This works and sends the email if I don't have an attachment.

**Comment by ecederstrand** [comment] 2018-03-14 14:26
Since you're on Exchange 2007, I believe this is a duplicate of https://github.com/ecederstrand/exchangelib/issues/150. There's a workaround in that issue.

I committed a fix in https://github.com/ecederstrand/exchangelib/commit/92d967fd917b4b6d395e4846e66772edef5ce802 but it hasn't been released yet. Please try it out and let me know if it works for you

**Comment by Ads5740** [comment] 2018-03-14 14:41
Hi, thanks for the info
yep the fix in #150 works, I tried the change but I was getting the error:

```
    m.send()
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 593, in send
    self.delete()
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 306, in delete

    affected_task_occurrences=affected_task_occurrences, suppress_read_receipts=
suppress_read_receipts)
  File "C:\Python27\lib\site-packages\exchangelib\items.py", line 313, in _delet
e
    raise ValueError('Item must have an ID')
ValueError: Item must have an ID

```
But my version is 1.10.3 so this might be why

**Comment by ecederstrand** [comment] 2018-03-14 14:52
I think the `self.delete()` in `exchangelib\items.py` line 593 (as per your stack trace) needs to go away. Can you test that?

**Comment by ecederstrand** [comment] 2018-03-14 15:36
Committed proposed fix. Feel free to re-open if it doesn't work for you.

**Closed** 2018-03-14 15:36 UTC

**Comment by Ads5740** [comment] 2018-03-14 16:09
yep removing the self.delete from the  92d967f worked
