### ISSUE TITLE
SyncFolderItems operation service is not implemented !

### ISSUE THREAD

**Issue by suddenraj** [ecederstrand/exchangelib#327] opened 2018-01-08 12:15 UTC
Hi Team,

Can i came to know when the folder sync service will get implement ?

https://msdn.microsoft.com/en-us/library/office/aa563967(v=exchg.150).aspx

**Comment by ecederstrand** [comment] 2018-01-08 13:33
This is a duplicate of #209 

There are no plans to implement this in the near future, but pull requests are most welcome :-)

**Closed by ecederstrand** 2018-01-08 13:33 UTC

**Comment by suddenraj** [comment] 2018-01-08 14:42
Thanks for the update

**Comment by spmsh** [comment] 2019-08-16 16:32
Hi @ecederstrand, reviving this old topic as I can see you may have started to implement the SyncFolderItems class.

I have tried it, I am getting some response with a list of CreateChange, UpdateChange or DeleteChange class objects, but all I get from those are None values. 

Whether I'm looping through their fields, __slots__ or else, there is no where I could find the corresponding ItemId, and other fields values coming from it's parent class (Item, BaseItem, etc...).

Looking at the response, I could see the results in the xml reponse (request is sent with IdOnly, so we're getting only the ItemIds which is fine), but then it's not getting populated when the xml got processed into those classes.

 So the question, is it still WIP, or it is in another class/function somewhere in the lib ?

Thanks again.

**Comment by ecederstrand** [comment] 2019-08-17 05:07
Hi @spmsh 

I'm not driving the work going on in #355. Last time I looked, it was not complete or ready for general consumption, and it's not part of any release yet. I'll happily accept the PR when it has a clear description of the API, documentation and tests that pass.

**Comment by spmsh** [comment] 2019-08-17 09:44
oh right, my bad, I didn't realize till now that it was part of the 355 PR and not from the standard lib. 
I will then assume it is not complete and see if there's anything I can do to make some progress. Thanks from the prompt response !
