### ISSUE TITLE
ErrorAccessDenied after upgrading from 1.12.2 to 1.12.3

### ISSUE THREAD

**Issue by nblivin** [ecederstrand/exchangelib#682] opened 2019-11-21 22:46 UTC
We recently upgraded from 1.12.2 and queries started failing with the error "exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again." Downgrading to 1.12.2 resolves the error, upgrading to 1.12.3 causes it to occur.

Looking at the differences between the two versions, it looks like the inclusion of FieldURI="folder:PermissionSet" is the only difference in the request data for the request that receives the error response. Any ideas on how I might resolve the issue?

**Comment by ecederstrand** [comment] 2019-11-22 04:33
This is a duplicate of #610

**Closed** 2019-11-22 06:04 UTC
