### ISSUE TITLE
Problems with modifying existing calendarevent

### ISSUE THREAD

**Issue by ekca1234** [ecederstrand/exchangelib#380] opened 2018-04-02 12:29 UTC
Hi,
 I had problem with modifying existing CalendarItem. The error was following:

`exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:IsOnlineMeeting" />)`

I dont know what's the correct way to fix the issue.
Currently (v 1.10.7) disabling the IsOnlineMeeting field did the trick...
```
diff items.py items.py~
504,505c504,505
< #        BooleanField('is_online_meeting', field_uri='calendar:IsOnlineMeeting', default=None,
< #                     is_required_after_save=True),
---
>         BooleanField('is_online_meeting', field_uri='calendar:IsOnlineMeeting', default=None,
>                      is_required_after_save=True),
```

Best,
 and thanks for the library!

tsapaj

**Comment by ecederstrand** [comment] 2018-04-02 14:44
Which version of Exchange is this? You can check with `account.version`.

It's hard to tell what the problem is without some example code, but maybe you're trying to modify the `is_online_meeting` of an item and saving it. Your Exchange version does not support that. Setting `som_item.is_online_meeting = None` before saving the item should achieve the same as disabling the field.

**Comment by ecederstrand** [comment] 2018-04-03 14:48
I just found out this is actually a duplicate of #307, fixed in https://github.com/ecederstrand/exchangelib/commit/d439475e834cf223487b96ea6b35d1618c495286 but not yet released on PyPI.

**Closed by ecederstrand** 2018-04-03 14:48 UTC
