### ISSUE TITLE
Add extended property to Folder

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#281] opened 2017-11-01 20:04 UTC
Hi, 
I want to add following property to Folders to check if it is a hidden folder. I cannot do Folder.register. can you help with this ?
class IsHidden(extended_properties.ExtendedProperty):
    property_tag = 0x10f4  
    property_type = 'Boolean'

**Comment by ecederstrand** [comment] 2017-11-01 20:41
This is not yet supported. See #171

**Comment by ecederstrand** [comment] 2017-11-07 08:34
Closing as duplicate of #171

**Closed by ecederstrand** 2017-11-07 08:34 UTC
