### ISSUE TITLE
UnboundLocalError: local variable 'log_vals' referenced before assignment 

### ISSUE THREAD

**Issue by martin-xia** [ecederstrand/exchangelib#407] opened 2018-05-09 22:04 UTC
I am seeing the following exceptions in version 1.11.0

```python
config = Configuration(server=server_name, credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/exchangelib/configuration.py", line 46, in __init__
    version=version

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/protocol.py", line 176, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/protocol.py", line 229, in __init__
    self.version = Version.guess(self)

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/version.py", line 205, in guess
    return cls._guess_version_from_service(protocol=protocol, hint=api_version)

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/version.py", line 238, in _guess_version_from_service
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/services.py", line 1558, in call
    contact_data_shape=contact_data_shape,

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/services.py", line 90, in _get_elements
    response = self._get_response_xml(payload=payload)

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/services.py", line 166, in _get_response_xml
    allow_redirects=False)

  File "/usr/local/lib/python2.7/dist-packages/exchangelib/util.py", line 512, in post_ratelimited
    log.error(str('%s: %s\n%s'), e.__class__.__name__, str(e), log_msg % log_vals)
UnboundLocalError: local variable 'log_vals' referenced before assignment
```

**Comment by martin-xia** [comment] 2018-05-09 22:06
Seems like a straightforward bug

**Comment by ecederstrand** [comment] 2018-05-12 21:14
Can you post some code that reproduces this? Does it also occur in the latest release (1.11.3)?

**Comment by ecederstrand** [comment] 2018-05-16 19:37
I think this has been fixed in newer versions. Feel free to re-open if you can reproduce this.

**Closed by ecederstrand** 2018-05-16 19:37 UTC

**Comment by ecederstrand** [comment] 2018-06-22 06:14
Yeah, that's just unfortunate timing for the `KeyboardInterrupt`. It's not uncommon for Python code to print all sorts of strange output when you hit `Ctrl-C`.

**Comment by ecederstrand** [comment] 2018-06-22 18:48
I agree. There wasn’t really any reason not to fix it.

**Comment by utapyngo** [comment] 2018-09-12 03:41
1.11.4 is still the latest version on PyPI: https://pypi.org/project/exchangelib/#history

**Comment by utapyngo** [comment] 2018-09-25 06:46
Please release 1.11.5!

**Comment by ecederstrand** [comment] 2018-09-25 07:41
There will be a 1.12.0 release instead sometime this week because there are backwards-incompatible changes since 1.11.4. See the CHANGELOG.
