### ISSUE TITLE
Error on line 79

### ISSUE THREAD

**Issue by alexross19** [ecederstrand/exchangelib#2] opened 2016-05-13 19:01 UTC
Hi,
 I am trying to list  cal event from my exchange account  on office365.
I simplified the code to just list  events, but its not working;
----------------------------------------------
from exchangelib import DELEGATE, services
from exchangelib.configuration import Configuration
from exchangelib.account import Account
from exchangelib.ewsdatetime import EWSDateTime, EWSTimeZone
from exchangelib.folders import CalendarItem

year, month, day = 2016, 5, 13
tz = EWSTimeZone.timezone('US/Eastern')
calendar_items = []
config = Configuration(username='xxxx\xxxx', password='xxxxx')
account = Account(primary_smtp_address='xxxx@xxxx.xxx', config=config, autodiscover=True, access_type=DELEGATE)

ids = account.calendar.find_items(
    start=tz.localize(EWSDateTime(year, month, day)),
    end=tz.localize(EWSDateTime(year, month, day+1)),
    shape=services.IdOnly,
)
print(ids)
------------------- error ----------------------------

C:\Users\Alex\Desktop>python Python2ExchnageCal_v2.py
Traceback (most recent call last):
  File "Python2ExchnageCal_v2.py", line 1, in <module>
    from exchangelib import DELEGATE, services
  File "C:\Program Files (x86)\Python26\lib\site-packages\exchangelib\__init__.py", line 2, in <module>
    from .account import Account
  File "C:\Program Files (x86)\Python26\lib\site-packages\exchangelib\account.py", line 79
    raise ErrorFolderNotFound('No useable calendar folders') from e
                                                                ^
SyntaxError: invalid syntax

--------------------------------------------------------------------
 Thanks
Alex Ross

**Comment by ecederstrand** [comment] 2016-05-13 19:07
Duplicate of #1

**Closed by ecederstrand** 2016-05-13 19:07 UTC
