### ISSUE TITLE
Querying emails across all folders

### ISSUE THREAD

**Issue by thefedoration** [ecederstrand/exchangelib#1022] opened 2021-11-08 19:53 UTC
**Describe the bug**
I'd like to be able to filter across all email folders at once, because the users of my app utilize folders in their outlook app. So far, I have not found a reliable way of doing so using exchangelib. I have attempted to filter in the following formats:

glob format:
`(account.root // 'Top of Information Store').glob('**/**').filter(item_class='IPM.Note').count()`

compiling all folders with email type objects:
```
top_folder = account.root // 'Top of Information Store'
email_folders = [f for f in top_folder.walk() if f.CONTAINER_CLASS == 'IPF.Note']
collection = FolderCollection(account=account, folders=email_folders)
collection.all().count()
```

Both of these result in the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/exchangelib/services/common.py", line 230, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/usr/local/lib/python3.8/site-packages/exchangelib/services/common.py", line 198, in <genexpr>
    return (self._get_page(message) for message in response)
  File "/usr/local/lib/python3.8/site-packages/exchangelib/services/common.py", line 731, in _get_page
    item_count, next_offset = self._get_paging_values(paging_elem)
  File "/usr/local/lib/python3.8/site-packages/exchangelib/services/common.py", line 722, in _get_paging_values
    raise ValueError("Expected empty 'next_offset' when 'item_count' is 0")
ValueError: Expected empty 'next_offset' when 'item_count' is 0
```

It's worth noting that sometimes these queries return a result and not an exception, it appears to be more likely to raise an exception when there are lots of items being returned and there is a need for pagination.
For example, `(account.root // 'Top of Information Store').glob('**/**').filter(is_read=False).count()` does not throw an exception, while changing to `is_read=True` does.

Additionally, I've noticed that when we do successfully return a queryset of emails from a cross-folder search, we seem to lose the `order_by` functionality. The emails appear to be sorted within their folders, but not in the combined result. For example, if I have 3 folders A, B, C, the emails will return like: `A_recent, A_old, B_recent, B_old, C_recent` while I would expect `A_recent, B_recent, C_recent, A_old, B_old`

One more thing, I use usually use the AQS format for filters because it supports filtering on to/bcc while the normal filters don't. It appears that this doesn't work at all across multiple folders. running `FolderCollection(account=account, folders=[account.inbox, account.sent]).filter('isRead:false').count()` always returns `exchangelib.errors.ErrorInvalidOperation: Shared folder search cannot be performed on multiple folders.` even though inbox + sent are not shared folders.

**Expected behavior**
I would expect to be able to make filter queries across multiple email folders without throwing an exception. I also expect results of cross-folder querysets to abide by the ordering set in `order_by`. Lastly, I'd expect the string filtering to work across multiple folders (as it does in the outlook web client)

**Additional context**
`exchangelib==4.5.2`

I know this is a lot of info and potentially a couple separate issues, but I wanted to include them together to show all of the things I've tried. If there is any logging context that would be useful to include, please let me know which query of the above would be the most helpful and I'll include it as a comment.

I really appreciate what you've done with this package, and you're always quite responsive to issues here. Thank you in advance for helping me run cross-folder queries Erik!

**Comment by thefedoration** [comment] 2021-11-08 21:05
In case it's helpful, my preferred method of filtering would be to use the querystring format without getting the `Shared folder search cannot be performed on multiple folders` exception. So if we get that one working I'd be happy. But figured I'd write up the full scope of what I've found with querying across multiple email folders

**Comment by ecederstrand** [comment] 2021-11-09 07:09
Thanks for the kind words!

The `ErrorInvalidOperation` is an exception thrown by the server. You can verify that by enabling [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and see the XML response for the request containing the filter on inbox and sent folders. Assuming there's nothing wrong with the request itself, then this is a limitation of the server and there's nothing exchangelib can do to fix that.

The `next_offset` error looks like a problem on our side. The logic around calculating paging values is non-trivial - especially when paging multiple folders at a time. You can probably trigger this error more easily if you lower the paging value, as described in https://ecederstrand.github.io/exchangelib/#paging I'll try to reproduce locally, but any hints that you can glean from the debug output would be most helpful to understand the situation leading to the error.

**Comment by thefedoration** [comment] 2021-11-09 22:00
Yes that's true, `ErrorInvalidOperation` is being returned by the exchange server. It just seems strange that we get that error for inbox & sent, which are not shared folders. Is there a way for me to use exchangelib to send a generic xml request to the server? I'd like to see if there's another format that achieves the desired results without this error.

I'm still looking for insights from the debug output to reproduce the `next_offset` error. So far I haven't come up with anything meaningful. Will post more findings here as I come across them.

BTW I also attempted using the `AllItems` search folder, like `(account.root // 'AllItems').filter('kind:email isread:false').count()`. It seemed very promising - searches all subfolders, really fast, no pagination errors. The only problem is that not all email filter properties are available (like "from" and "to"), but they work in the inbox/sent folders. I think that's because the results in that folder are of the class Item and not Message. If you know how to filter on message properties in search folders, that would be very helpful.

**Comment by thefedoration** [comment] 2021-11-15 21:27
Hey @ecederstrand so looking at the logs under different pagination conditions, I didn't find much difference when increasing/decreasing the page values.

Here's what I found though. I'm making a query on subject through all email folders (14 in my case) in a FolderCollection.
A few of the logs from right before the exception:
```
[exchangelib.services.common] DEBUG Got page with next offset None (last_page True)
[exchangelib.services.common] DEBUG Got page with next offset None (last_page True)
[exchangelib.services.common] DEBUG Got page with next offset 914 (last_page False)
[exchangelib.services.common] DEBUG Got page with next offset 0 (last_page False)
[exchangelib.services.common] DEBUG Got page with next offset 0 (last_page False)
ValueError: Expected empty 'next_offset' when 'item_count' is 0
```

What caught my eye was that `last_page` is `False` when next offset is 0, but `True` when next offset is `None`. I looked at the response from exchange to confirm that it's actually being returned with those values:
```
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header>
      <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="20" MajorBuildNumber="4690" MinorBuildNumber="27" Version="V2018_01_08" />
   </s:Header>
   <s:Body>
      <m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         <m:ResponseMessages>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="86" TotalItemsInView="86" IncludesLastItemInRange="true">
                  <t:Items>
                     // lots of items here
                  </t:Items>
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="true">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="914" TotalItemsInView="1863" IncludesLastItemInRange="false">
                  <t:Items>
                     // lots of items here
                  </t:Items>
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="2" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="25" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="808" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="6" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="8" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="3" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="1" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="2" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
            <m:FindItemResponseMessage ResponseClass="Success">
               <m:ResponseCode>NoError</m:ResponseCode>
               <m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="false">
                  <t:Items />
               </m:RootFolder>
            </m:FindItemResponseMessage>
         </m:ResponseMessages>
      </m:FindItemResponse>
   </s:Body>
</s:Envelope>
```

Quite strange that the second `FindItemResponseMessage` has 0 items and returns:
`<m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="true">`
But the last `FindItemResponseMessage` has 0 items and returns:
`<m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="false">`

I would think that each response should behave similarly, and if there are 0 items in the folder, then the `IncludesLastItemInRange` value would aways be consistent, probably set to `true`.

Do you think this a bug from the exchange server?
Even if it is, given that a `FindItemResponseMessage` returns 0 items, would it make sense to force [is_last_page](https://github.com/ecederstrand/exchangelib/blame/8b72c666977b41471c720992934dc65ffa11f467/exchangelib/services/common.py#L716) to be `False` from exchangelib?

**Comment by ecederstrand** [comment] 2021-11-16 21:36
I did a pretty deep dive into the paging code today.

I agree that `<m:RootFolder IndexedPagingOffset="0" TotalItemsInView="0" IncludesLastItemInRange="false">` does not make sense. We didn't handle that well. 554628f should take care of this.

A bigger problem was that when we requested paging of a number of folders, we kept requesting folders to be paged even when these folders had been exhausted. This led to weird paging values in the response, and also requests that were unnecessarily large, and requests for offsets to folders that we knew didn't have that many items to begin with. a8e349d should take care of that.

**Comment by ecederstrand** [comment] 2021-11-16 21:43
Finally, if all you want is an estimated count of all items in a folder, you could have a look at the `Folder.total_count` and `Folder.unread_count` attributes. I believe that's what e.g. Outlook uses to show the item count on a folder.

**Comment by thefedoration** [comment] 2021-11-17 15:10
Thank you Erik. appreciate your work on the pagination logic. I'll test and confirm this solves this issue for my dataset.

Thanks for the tip about total & unread count. I was only using `count()` as an example, will need to be able to filter & fetch contents of emails as well.

**Comment by thefedoration** [comment] 2021-11-17 15:33
I've confirmed that the `Expected empty 'next_offset' when 'item_count' is 0` error is resolved now. Thanks @ecederstrand!

However, the sorting is still off for these emails. The filtered emails appear to be returned sorted by folder which they are located in, and not abiding by the overall `order_by()` on the email queryset. This is quite important to my use-case, to be able to sort the overall filtered email set by data, and paginate through the results. Do you think this is something we would be able to support with exchangelib pagination?

**Comment by ecederstrand** [comment] 2021-11-17 18:17
The server-side ordering does not sort across folders. A response returns the next X items in each requested folder. The response contains one item list per folder.

If you want to sort items in a multi-folder search, you’ll have to do the sorting client-side.

**Comment by ecederstrand** [comment] 2021-11-20 01:42
I'm closing this issue because the original pagination error was fixed. Please open new issues for any remaining issues.

**Closed by ecederstrand** 2021-11-20 01:42 UTC
Labels: bug
