### ISSUE TITLE
 attachment.name returns None for Attached Outlook Items Despite Valid Subject

### ISSUE THREAD

**Issue by michal-dagan** [ecederstrand/exchangelib#1329] opened 2024-09-12 16:51 UTC
Issue:
When attempting to retrieve the name of an attached Outlook item from an email using attachment.name, the result returns None instead of the expected name. This occurs even though the attachment has a subject, which indicates that the attachment metadata is present.

Reproduction Steps:
Attach an Outlook item to an email.
Try retrieving the attachment name with `attachment.name`.
The value returned is None instead of the expected name.
Expected Behavior:
attachment.name should return the subject or name of the attached item.

Actual Behavior:
attachment.name returns None, even though the attached item has a subject, as shown in the XML response:
`<t:Name/>`

Notes:
The attached item has valid metadata, as the subject exists, but the name field is empty or incorrectly parsed.

**Comment by ecederstrand** [comment] 2024-09-12 19:27
I cannot reproduce this. The following example prints `ZZZ XXX` as expected:

```python
m1 = Message(folder=a.drafts, subject="XXX").save()
m2 = Message(folder=a.drafts, subject="YYY").save()
m2.attach(ItemAttachment(item=m1, name="ZZZ"))
att = a.drafts.get(subject="YYY").attachments[0]
print(att.name, att.item.subject)
```

**Comment by michal-dagan** [comment] 2024-09-15 15:23
Hi, thanks!
Can you please clarify when an ItemAttachment does not have a name? 
I'm trying to retrieve an attachment from an email, specifically when the attachment is of the .eml type. Sometimes it has a name, but other times it only has a subject. Why is this happening?

**Comment by ecederstrand** [comment] 2024-09-15 17:00
I don't know why it's happening. exchangelib just reads what the server sends, so I assume it's caused by differences in the clients that created the messages originally.

**Comment by ecederstrand** [comment] 2024-09-19 13:38
Closing, but feel free to reopen if you have additional questions related to this.

**Closed by ecederstrand** 2024-09-19 13:38 UTC
