### ISSUE TITLE
ValueError: Item type {http://schemas.microsoft.com/exchange/services/2006/types}Booking was unexpected in a BaseFolder folder

### ISSUE THREAD

**Issue by benopotamus** [ecederstrand/exchangelib#877] opened 2021-03-16 23:13 UTC
**Describe the bug**
When using exchangelib to access a calendar created by the Microsoft Bookings app, a value error is raised when looping over account.calendar.all().

**To Reproduce**

```
from exchangelib import Credentials, Account

emailaddr = 'name@company.com'
password = 'password123'
booking_calendar_emailaddr = 'bookingapp1@company.onmicrosoft.com'

credentials = Credentials(username=emailaddr, password=password)
account = Account(booking_calendar_emailaddr, credentials=credentials, autodiscover=True)

print(account.calendar.all())
print(account.calendar.all().count())

for calendar_item in account.calendar.all():
	print('hi')
```

**Expected behavior**

I expect to be able to loop over the account.calendar.all() queryset and access data within each calendar item.

**Log output**
The error log and print statement outputs are:

```
PS C:\tmp> py .\main.py
QuerySet(q=Q(), folders=[Calendar (Calendar)])
162
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\exchangelib\folders\base.py", line 224, in item_model_from_tag
    return cls.ITEM_MODEL_MAP[tag]
KeyError: '{http://schemas.microsoft.com/exchange/services/2006/types}Booking'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\main.py", line 37, in <module>
    for calendar_item in account.calendar.all():
  File "C:\Python\Python38\lib\site-packages\exchangelib\queryset.py", line 273, in __iter__        
    yield from self._format_items(items=self._query(), return_format=self.return_format)
  File "C:\Python\Python38\lib\site-packages\exchangelib\queryset.py", line 348, in _item_yielder   
    for i in iterable:
  File "C:\Python\Python38\lib\site-packages\exchangelib\account.py", line 581, in fetch
    yield from self._consume_item_service(service_cls=GetItem, items=ids, chunk_size=chunk_size, kwargs=dict(
  File "C:\Python\Python38\lib\site-packages\exchangelib\account.py", line 343, in _consume_item_service
    yield from service_cls(account=self, chunk_size=chunk_size).call(**kwargs)
  File "C:\Python\Python38\lib\site-packages\exchangelib\services\get_item.py", line 27, in call    
    yield BaseFolder.item_model_from_tag(elem.tag).from_xml(elem=elem, account=self.account)
  File "C:\Python\Python38\lib\site-packages\exchangelib\folders\base.py", line 226, in item_model_from_tag
    raise ValueError('Item type %s was unexpected in a %s folder' % (tag, cls.__name__))
ValueError: Item type {http://schemas.microsoft.com/exchange/services/2006/types}Booking was unexpected in a BaseFolder folder
```

**Additional context**
Python 3.8.6
exchangelib 4.1.0

**Comment by ecederstrand** [comment] 2021-03-17 08:23
Thanks for the report! This is a bit surprising, given that the `Booking` element is not mentioned anywhere in https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/ews-xml-elements-in-exchange This XML element isn't even mentioned in [types.xsd](https://github.com/jamesiarmes/php-ews/blob/master/src/assets/types.xsd)

Can you capture the response XML of the query containing the `Booking` element (see https://ecederstrand.github.io/exchangelib/#troubleshooting)? Then I can at least implement it as a dummy object, allowing you to continue your work.

**Comment by ecederstrand** [comment] 2021-03-17 08:29
Possible workaround until then (untested):

```python
from exchangelib.folders import BaseFolder
from exchangelib.item import Item

class Booking(Item):
    ELEMENT_NAME = 'Booking'

BaseFolder .ITEM_MODEL_MAP[Booking.response_tag()] = Booking

# Your script here
```

**Comment by benopotamus** [comment] 2021-03-21 23:35
The work around worked (just a missing s in exchangelib.items). Thanks!

This appears to be the main object in the PrettyXmlHandler logging 

```
<t:CalendarItem xsi:type="t:BookingItemType">
	<t:ItemId Id="VCKVCMKKLASDDFFDBFGHKSDFGHFIDTBHYTIUKNUKFKFKETF" ChangeKey="IOREIOPQPDPDPDD" />
	<t:PreBuffer>0</t:PreBuffer>
	<t:PostBuffer>0</t:PostBuffer>
	<t:PricingType>Undefined</t:PricingType>
	<t: Price>0</t:Price>
	<t:BookingFee>0</t:BookingFee>
	<t:BookingTax>0</t:BookingTax>
	<t:SelfServiceId>00000000-0000-0000-0000-000000000000</t:Se lfServiceId>
</t:CalendarItem>
```

**Comment by ecederstrand** [comment] 2021-03-22 07:54
Thanks for confirming the workaround.

I was expecting an XML element called `Booking`. Can you find that in the log output?

**Comment by benopotamus** [comment] 2021-03-22 22:48
Ahh yes - how about this one below. 

In case it matters:

- `t:BookingItemType` was in a log generated using `logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])` and running the program as `main.py > el-xml.log 2>&1`. 
- `t:Booking` object below was in a log generated using `logging.basicConfig(level=logging.DEBUG, filename='exchangelib.output.log')` and just running the program as `main.py`.



```
<m:GetItemResponseMessage ResponseClass="Success">
	<m:ResponseCode>NoError</m:ResponseCode>
	<m:Items>
		<t:Booking>
			<t:MimeContent CharacterSet="UTF-8">LOTSOFSTUFFHERE</t:MimeContent>
			<t:ItemId Id="ANIDHERE" ChangeKey="ASHORTERKEYHERE" />
			<t:ParentFolderId Id="ANOTHERID" ChangeKey="ANOTHERKEY" />
			<t:ItemClass>IPM.Appointment.Microsoft.OnlineBooking</t:ItemClass>
			<t:Subject>Part day</t:Subject>
			<t:Sensitivity>Normal</t:Sensitivity>
			<t:Body BodyType="Text" IsTruncated="false">
				The body of the booing is here. This is the same info I see in the booking/meeting when I view it using
				Outlook
			</t:Body>
			<t:DateTimeReceived>2021-01-27T10:09:46+10:00</t:DateTimeReceived>
			<t:Size>11438</t:Size>
			<t:Categories>
				<t:String>Staff member name here</t:String>
			</t:Categories>
			<t:Importance>Normal</t:Importance>
			<t:IsSubmitted>false</t:IsSubmitted>
			<t:IsDraft>false</t:IsDraft>
			<t:IsFromMe>false</t:IsFromMe>
			<t:IsResend>false</t:IsResend>
			<t:IsUnmodified>false</t:IsUnmodified>
			<t:DateTimeSent>2021-01-27T10:09:46+10:00</t:DateTimeSent>
			<t:DateTimeCreated>2021-01-27T10:09:46+10:00</t:DateTimeCreated>
			<t:ResponseObjects>
				<t:CancelCalendarItem />
				<t:ReplyToItem />
				<t:ReplyAllToItem />
				<t:ForwardItem />
			</t:ResponseObjects>
			<t:ReminderDueBy>2021-01-29T08:00:00+10:00</t:ReminderDueBy>
			<t:ReminderIsSet>true</t:ReminderIsSet>
			<t:ReminderMinutesBeforeStart>15</t:ReminderMinutesBeforeStart>
			<t:DisplayCc />
			<t:DisplayTo>Staff member name here</t:DisplayTo>
			<t:HasAttachments>false</t:HasAttachments>
			<t:Culture>en-GB</t:Culture>
			<t:EffectiveRights>
				<t:CreateAssociated>false</t:CreateAssociated>
				<t:CreateContents>false</t:CreateContents>
				<t:CreateHierarchy>false</t:CreateHierarchy>
				<t:Delete>true</t:Delete>
				<t:Modify>true</t:Modify>
				<t:Read>true</t:Read>
				<t:ViewPrivateItems>true</t:ViewPrivateItems>
			</t:EffectiveRights>
			<t:LastModifiedName>Booking app instance name here</t:LastModifiedName>
			<t:LastModifiedTime>2021-01-27T10:09:46+10:00</t:LastModifiedTime>
			<t:IsAssociated>false</t:IsAssociated>
			<t:WebClientReadFormQueryString>
				https://outlook.office365.com/owa/?ItemID=ANOTHERIDHERE&amp;exvsurl=1&amp;viewmodel=ReadMessageItem
			</t:WebClientReadFormQueryString>
			<t:ConversationId Id="ANDANOTHERIDHERE" />
			<t:TextBody BodyType="Text" IsTruncated="false">The body of the booing is here. This is the same info I see
				in the booking/meeting when I view it using Outlook </t:TextBody>
			<t:UID>123456789</t:UID>
			<t:Start>2021-01-29T08:00:00+10:00</t:Start>
			<t:End>2021-01-29T11:00:00+10:00</t:End>
			<t:IsAllDayEvent>false</t:IsAllDayEvent>
			<t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
			<t:Location />
			<t:IsMeeting>true</t:IsMeeting>
			<t:IsCancelled>false</t:IsCancelled>
			<t:IsRecurring>false</t:IsRecurring>
			<t:MeetingRequestWasSent>true</t:MeetingRequestWasSent>
			<t:IsResponseRequested>false</t:IsResponseRequested>
			<t:CalendarItemType>Single</t:CalendarItemType>
			<t:MyResponseType>Organizer</t:MyResponseType>
			<t:Organizer>
				<t:Mailbox>
					<t:Name>Name of the Microsoft Bookings instance here</t:Name>
					<t:EmailAddress>bookingappinstancemailaddresshere@mycompany.onmicrosoft.com</t:EmailAddress>
					<t:RoutingType>SMTP</t:RoutingType>
					<t:MailboxType>Mailbox</t:MailboxType>
				</t:Mailbox>
			</t:Organizer>
			<t:RequiredAttendees>
				<t:Attendee>
					<t:Mailbox>
						<t:Name>Staff member name here</t:Name>
						<t:EmailAddress>email_address_for_the_staff_member_being_booked_in_the_app@mycompany.com
						</t:EmailAddress>
						<t:RoutingType>SMTP</t:RoutingType>
						<t:MailboxType>OneOff</t:MailboxType>
					</t:Mailbox>
					<t:ResponseType>Unknown</t:ResponseType>
				</t:Attendee>
			</t:RequiredAttendees>
			<t:ConflictingMeetingCount>3</t:ConflictingMeetingCount>
			<t:AdjacentMeetingCount>1</t:AdjacentMeetingCount>
			<t:ConflictingMeetings>
				<t:CalendarItem>
					<t:ItemId Id="ANOTHERID" ChangeKey="ANOTHERKEY" />
					<t:Subject>All day</t:Subject>
					<t:Start>2021-01-29T08:00:00+10:00</t:Start>
					<t:End>2021-01-29T16:00:00+10:00</t:End>
					<t:IsAllDayEvent>false</t:IsAllDayEvent>
					<t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
					<t:Location />
				</t:CalendarItem>
				<t:CalendarItem>
					<t:ItemId Id="ANOTHERID" ChangeKey="ANOTHERKEY" />
					<t:Subject>All day</t:Subject>
					<t:Start>2021-01-29T08:00:00+10:00</t:Start>
					<t:End>2021-01-29T16:00:00+10:00</t:End>
					<t:IsAllDayEvent>false</t:IsAllDayEvent>
					<t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
					<t:Location />
				</t:CalendarItem>
				<t:CalendarItem>
					<t:ItemId Id="ANOTHERID" ChangeKey="ANOTHERKEY" />
					<t:Subject>Part day</t:Subject>
					<t:Start>2021-01-29T08:00:00+10:00</t:Start>
					<t:End>2021-01-29T11:00:00+10:00</t:End>
					<t:IsAllDayEvent>false</t:IsAllDayEvent>
					<t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
					<t:Location />
				</t:CalendarItem>
			</t:ConflictingMeetings>
			<t:AdjacentMeetings>
				<t:CalendarItem>
					<t:ItemId Id="ANOTHERID" ChangeKey="ANOTHERKEY" />
					<t:Subject>Part day</t:Subject>
					<t:Start>2021-01-29T11:00:00+10:00</t:Start>
					<t:End>2021-01-29T16:00:00+10:00</t:End>
					<t:IsAllDayEvent>false</t:IsAllDayEvent>
					<t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
					<t:Location />
				</t:CalendarItem>
			</t:AdjacentMeetings>
			<t:Duration>PT3H</t:Duration>
			<t:AppointmentSequenceNumber>0</t:AppointmentSequenceNumber>
			<t:AppointmentState>1</t:AppointmentState>
			<t:StartTimeZone Name="(UTC+10:00) Brisbane" Id="E. Australia Standard Time">
				<t:Periods>
					<t:Period Bias="-PT10H" Name="Standard"
						Id="trule:Microsoft/Registry/E. Australia Standard Time/1-Standard" />
				</t:Periods>
				<t:TransitionsGroups>
					<t:TransitionsGroup Id="0">
						<t:Transition>
							<t:To Kind="Period">trule:Microsoft/Registry/E. Australia Standard Time/1-Standard</t:To>
						</t:Transition>
					</t:TransitionsGroup>
				</t:TransitionsGroups>
				<t:Transitions>
					<t:Transition>
						<t:To Kind="Group">0</t:To>
					</t:Transition>
				</t:Transitions>
			</t:StartTimeZone>
			<t:EndTimeZone Name="(UTC+10:00) Brisbane" Id="E. Australia Standard Time">
				<t:Periods>
					<t:Period Bias="-PT10H" Name="Standard"
						Id="trule:Microsoft/Registry/E. Australia Standard Time/1-Standard" />
				</t:Periods>
				<t:TransitionsGroups>
					<t:TransitionsGroup Id="0">
						<t:Transition>
							<t:To Kind="Period">trule:Microsoft/Registry/E. Australia Standard Time/1-Standard</t:To>
						</t:Transition>
					</t:TransitionsGroup>
				</t:TransitionsGroups>
				<t:Transitions>
					<t:Transition>
						<t:To Kind="Group">0</t:To>
					</t:Transition>
				</t:Transitions>
			</t:EndTimeZone>
			<t:IsOnlineMeeting>false</t:IsOnlineMeeting>
			<t:PreBuffer>0</t:PreBuffer>
			<t:PostBuffer>0</t:PostBuffer>
			<t:PricingType>Undefined</t:PricingType>
			<t:Price>0</t:Price>
			<t:BookingFee>0</t:BookingFee>
			<t:BookingTax>0</t:BookingTax>
			<t:SelfServiceId>00000000-0000-0000-0000-000000000000</t:SelfServiceId>
		</t:Booking>
	</m:Items>
</m:GetItemResponseMessage>
```

**Comment by ecederstrand** [comment] 2021-03-23 09:09
Ok, thanks for the extra info.

I'm undecided what to do for exchangelib. It seems that this is caused by installing Microsoft Bookings (https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?view=o365-worldwide) which somehow changes the XML schema of the EWS service. On one hand, it's ugly to get this exception just because someone installed this plugin. On the other hand, I'm not fond of adding code to exchangelib that cannot be tested.

The workaround should get you going, but would not give you access to the extra fields that are mentioned in the `BookingItemType` calendar item mentioned above. Do you need access to those fields?

**Comment by benopotamus** [comment] 2021-03-23 10:46
Thanks Erik. I don't need the extra fields so the workaround was enough for me. Thanks for helping - and for the library!

**Comment by ecederstrand** [comment] 2021-03-23 11:55
My pleasure!

I'm closing this issue. If other users are affected by this, we may have to revisit and add support for Bookings in exchangelib.

**Closed by ecederstrand** 2021-03-23 11:55 UTC

**Comment by rafael-sanz** [comment] 2022-01-20 15:40
Hi, just confirm that I reproduce the error and[ the patch ](https://github.com/ecederstrand/exchangelib/issues/877#issuecomment-800895629)work for me too. At least getting the element directly, because as all().only('subject', 'start', 'text_body') iterator fail.

**Work**
```
cal=account.calendar
for ci in cal.all().order_by('-start').only('subject', 'start')[:10]:
    log.debug('--> %s => %s', ci.subject, ci.start)
    item=cal.get(id=ci.id)
    log.debug(' Msg: [%s]', item.text_body[:60]) 
```
**Fail**
```
cal=account.calendar
for ci in cal.all().order_by('-start').only('subject', 'start', 'text_body')[:10]:
    log.debug('--> %s => %s', ci.subject, ci.start)
    log.debug(' Msg: [%s]', ci.text_body[:60]) 
```
Output error:
    log.debug('--> %s => %s', ci.subject, ci.start)
    AttributeError: 'Booking' object has no attribute 'start'

Thanks very much!

**Comment by ecederstrand** [comment] 2022-01-20 20:53
Before referencing `ci.start`, it's a good idea to check whether `ci` is in fact an instance of `CalendarItem`, and skip over `Booking` instances.

**Comment by rafael-sanz** [comment] 2022-01-21 10:31
Thanks very much Erik for your quick response.
Untill I understand all items are Bookings but i'm accesing them as Calendar (advise I'm retrieving with same pointer "cal"). My doubt is here if I must instanciate other class else "account.calendar" (account.Booking perhaps?)

This is some extract from XML if it will help:
```xml
<m:GetItemResponseMessage ResponseClass="Success">
  <m:ResponseCode>NoError</m:ResponseCode>
  <m:Items>
	<t:Booking>
	  <t:MimeContent CharacterSet="UTF-8">QkVHSU46VkNBTEVOREFSDQpNR...................Wljcm9zb2Z0LmNvbQ0KRU5EOlZBTEFSTQ0KRU5EOlZFVkVOVA0KRU5EOlZDQUxFTkRBUg0K</t:MimeContent>
	  <t:ItemId Id="AAMkAGMyNzk1MTgyLWZmMzYtNDViOC05MjUyLWE4ZjZ..............ENAABWXr1K5BV9T4WKveJtX+KlAAEord8OAAA=" ChangeKey="TgAAABYAAABWXr1K5BV9T4WKveJtX+KlAAEoywzZ"/>
	  <t:ParentFolderId Id="AAMkAGMyNzk1MTgyLWZmM............2mdQFTSzkCAQBWXr1K5BV9T4WKveJtX+KlAAAAAAENAAA=" ChangeKey="AQAAAA=="/>
	  <t:ItemClass>IPM.Appointment.Microsoft.OnlineBooking</t:ItemClass>
	  <t:Subject>subject of appointment</t:Subject>
	  <t:Sensitivity>Normal</t:Sensitivity>
	  <t:Body BodyType="Text" IsTruncated="false"> SOME LARGE HTML TEXT HERE*****&#13;</t:TextBody>
	  <t:UID>040000008200E00074C5B7101A......00003FC0ACD5732D2745852E7578B1010194</t:UID>
	  <t:Start>2022-02-01T14:00:00+01:00</t:Start>
	  <t:End>2022-02-01T14:30:00+01:00</t:End>
	  <t:IsAllDayEvent>false</t:IsAllDayEvent>
	  <t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus>
	  <t:Location>Renovacion en remoto</t:Location>
	  <t:IsMeeting>true</t:IsMeeting>
	  <t:IsCancelled>false</t:IsCancelled>
	  <t:IsRecurring>false</t:IsRecurring>
	  <t:MeetingRequestWasSent>true</t:MeetingRequestWasSent>
	  <t:IsResponseRequested>false</t:IsResponseRequested>
	  <t:CalendarItemType>Single</t:CalendarItemType>
	  <t:MyResponseType>Organizer</t:MyResponseType>
	  <t:Organizer>
		<t:Mailbox>
		  <t:Name>client name</t:Name>
		  <t:EmailAddress>some@address.com</t:EmailAddress>
		  <t:RoutingType>SMTP</t:RoutingType>
		  <t:MailboxType>Mailbox</t:MailboxType>
		</t:Mailbox>
	  </t:Organizer>
	  <t:RequiredAttendees>
		<t:Attendee>
		  <t:Mailbox>
			<t:Name>Thomas Smith</t:Name>
			<t:EmailAddress>thomas@address.com</t:EmailAddress>
			<t:RoutingType>SMTP</t:RoutingType>
			<t:MailboxType>OneOff</t:MailboxType>
		  </t:Mailbox>
		  <t:ResponseType>Unknown</t:ResponseType>
		</t:Attendee>
	  </t:RequiredAttendees>
	  <t:ConflictingMeetingCount>0</t:ConflictingMeetingCount>
	  <t:AdjacentMeetingCount>0</t:AdjacentMeetingCount>
	  <t:Duration>PT30M</t:Duration>
	  <t:AppointmentSequenceNumber>0</t:AppointmentSequenceNumber>
	  <t:AppointmentState>1</t:AppointmentState>
	  <t:StartTimeZone Name="(UTC+01:00) Brussels, Copenhagen, Madrid, Paris" Id="Romance Standard Time">
		<t:Periods>
		  <t:Period Bias="-PT1H" Name="Standard" Id="trule:Microsoft/Registry/Romance Standard Time/1-Standard"/>
		  <t:Period Bias="-PT2H" Name="Daylight" Id="trule:Microsoft/Registry/Romance Standard Time/1-Daylight"/>
		</t:Periods>
		<t:TransitionsGroups>
		  <t:TransitionsGroup Id="0">
			<t:RecurringDayTransition>
			  <t:To Kind="Period">trule:Microsoft/Registry/Romance Standard Time/1-Daylight</t:To>
			  <t:TimeOffset>PT2H</t:TimeOffset>
			  <t:Month>3</t:Month>
			  <t:DayOfWeek>Sunday</t:DayOfWeek>
			  <t:Occurrence>-1</t:Occurrence>
			</t:RecurringDayTransition>
			<t:RecurringDayTransition>
			  <t:To Kind="Period">trule:Microsoft/Registry/Romance Standard Time/1-Standard</t:To>
			  <t:TimeOffset>PT3H</t:TimeOffset>
			  <t:Month>10</t:Month>
			  <t:DayOfWeek>Sunday</t:DayOfWeek>
			  <t:Occurrence>-1</t:Occurrence>
			</t:RecurringDayTransition>
		  </t:TransitionsGroup>
		</t:TransitionsGroups>
		<t:Transitions>
		  <t:Transition>
			<t:To Kind="Group">0</t:To>
		  </t:Transition>
		</t:Transitions>
	  </t:StartTimeZone>
	  <t:EndTimeZone Name="(UTC+01:00) Brussels, Copenhagen, Madrid, Paris" Id="Romance Standard Time">
		<t:Periods>
		  <t:Period Bias="-PT1H" Name="Standard" Id="trule:Microsoft/Registry/Romance Standard Time/1-Standard"/>
		  <t:Period Bias="-PT2H" Name="Daylight" Id="trule:Microsoft/Registry/Romance Standard Time/1-Daylight"/>
		</t:Periods>
		<t:TransitionsGroups>
		  <t:TransitionsGroup Id="0">
			<t:RecurringDayTransition>
			  <t:To Kind="Period">trule:Microsoft/Registry/Romance Standard Time/1-Daylight</t:To>
			  <t:TimeOffset>PT2H</t:TimeOffset>
			  <t:Month>3</t:Month>
			  <t:DayOfWeek>Sunday</t:DayOfWeek>
			  <t:Occurrence>-1</t:Occurrence>
			</t:RecurringDayTransition>
			<t:RecurringDayTransition>
			  <t:To Kind="Period">trule:Microsoft/Registry/Romance Standard Time/1-Standard</t:To>
			  <t:TimeOffset>PT3H</t:TimeOffset>
			  <t:Month>10</t:Month>
			  <t:DayOfWeek>Sunday</t:DayOfWeek>
			  <t:Occurrence>-1</t:Occurrence>
			</t:RecurringDayTransition>
		  </t:TransitionsGroup>
		</t:TransitionsGroups>
		<t:Transitions>
		  <t:Transition>
			<t:To Kind="Group">0</t:To>
		  </t:Transition>
		</t:Transitions>
	  </t:EndTimeZone>
	  <t:IsOnlineMeeting>true</t:IsOnlineMeeting>
	  <t:PreBuffer>0</t:PreBuffer>
	  <t:PostBuffer>0</t:PostBuffer>
	  <t:PricingType>Undefined</t:PricingType>
	  <t:Price>0</t:Price>
	  <t:BookingFee>0</t:BookingFee>
	  <t:BookingTax>0</t:BookingTax>
	  <t:SelfServiceId>00000000-0000-0000-0000-000000000000</t:SelfServiceId>
	</t:Booking>
  </m:Items>
</m:GetItemResponseMessage>
```

**Comment by ecederstrand** [comment] 2022-01-21 11:07
`account.calendar` points to the calendar folder in your mailbox. Normally, a calendar folder can only contain `CalendarItem` instances, but since someone installed the bookings plugin on your Exchange server, your calendar folder can now contain both `CalendarItem` and `Booking` instances.

The patch doesn't add full support for bookings, it just allows exchangelib to not crash when it encounters a booking in the calendar folder.
