### ISSUE TITLE
is_online_meeting

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#322] opened 2017-12-21 17:30 UTC
Hi, a few weeks (or was it months) ago I started getting an error that the Field IsOnlineMeeting is not set.

What am I doing:
- I create a calendar event with DELEGATION rights (no is_online_meeting set, no error)
- then I try to update and save the same event and it throws me this IsOnlineMeeting error unless I do something like:

```
element.is_online_meeting = None
element.save()
```

Is there a way to default that field to None?

**Comment by ecederstrand** [comment] 2017-12-21 20:32
Which Exchange version is your server? `print(your_account.version)` will show you.

**Comment by fruitloop** [comment] 2017-12-21 23:39
I use an Office365 Subscription which gives me `Build=15.20.323.19, API=Exchange2016, Fullname=Microsoft Exchange Server 2016` as Version

**Comment by fruitloop** [comment] 2017-12-21 23:42
Code:
```
credentials = ServiceAccount(username=email, password=password)
  account = Account(primary_smtp_address=email, credentials=credentials, autodiscover=True, access_type=DELEGATE)
  folder = calendar_folder_searched_by_name
  tz = EWSTimeZone.timezone('Europe/Vienna')
  events = get_events(function to get exactly the events of the date used below)
  CalendarItem(
    account=account,
    folder=folder,
    subject='0900-1000',
    start=tz.localize(EWSDateTime.from_datetime(datetime.datetime(2017,12,11,9,0))),
    end=tz.localize(EWSDateTime.from_datetime(datetime.datetime(2017,12,11,10,0))),
    body='foo',
  ).save()
  for e in events:
    e.body = datetime.datetime.now()
    e.save()
```

Error:
```
Traceback (most recent call last):
  File "main.py", line 572, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 47, in main
    e.save()
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 181, in save
    send_meeting_invitations=send_meeting_invitations
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 239, in _update
    send_meeting_invitations_or_cancellations=send_meeting_invitations)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 431, in bulk_update
    suppress_read_receipts=suppress_read_receipts,
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 425, in <genexpr>
    i if isinstance(i, Exception) else Item.id_from_xml(i)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 456, in _pool_requests
    for elem in elems:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 283, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 256, in _get_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 273, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:IsOnlineMeeting" />)
```

**Comment by ecederstrand** [comment] 2018-01-15 10:10
Maybe this field is just not updateable. In that case, marking it as `is_read_only_after_send` may solve this.

**Comment by fruitloop** [comment] 2018-01-15 13:29
is that something I need to change in my script?

**Comment by ecederstrand** [comment] 2018-01-18 17:07
This is actually a duplicate of #307

**Closed by ecederstrand** 2018-01-18 17:07 UTC
