### ISSUE TITLE
Autodiscover failing with Office 365

### ISSUE THREAD

**Issue by greatman** [ecederstrand/exchangelib#337] opened 2018-02-08 19:15 UTC
Hello!

I seems to have catched a bug with the autodiscover HTTP redirect with an Office 365 environment. The autodiscover is trying to use the CNAME value of the dns record autodiscover-s.outlook.com which cause an error because the SSL certificate on microsoft sides only accepts *.outlook.com and not "outlook.ms-acdc.office.com".

If in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py#L443 I simply return directly the hostname received as a parameter, the autodiscover works fine.

```
DEBUG:exchangelib.autodiscover:Trying autodiscover on http://autodiscover.redacted.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for http://autodiscover.redacted.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): autodiscover.redacted.com
DEBUG:urllib3.connectionpool:http://autodiscover.redacted.com:80 "HEAD /Autodiscover/Autodiscover.xml HTTP/1.1" 302 0
DEBUG:exchangelib.autodiscover:We were redirected to https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.autodiscover:Attempting to get canonical name for autodiscover-s.outlook.com
DEBUG:exchangelib.autodiscover:autodiscover-s.outlook.com has canonical name outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Canonical hostname is outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Trying autodiscover on https://outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for https://outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.ms-acdc.office.com
ERROR:urllib3.connection:Certificate did not match expected hostname: outlook.ms-acdc.office.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'Washington'),), (('localityName', 'Redmond'),), (('organizationName', 'Microsoft Corporation'),), (('commonName', 'outlook.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert Cloud Services CA-1'),)), 'version': 3, 'serialNumber': '0ECD90EC9E8A91E1DED5DE9E714F0FF4', 'notBefore': 'Sep 13 00:00:00 2017 GMT', 'notAfter': 'Sep 13 12:00:00 2018 GMT', 'subjectAltName': (('DNS', '*.clo.footprintdns.com'), ('DNS', '*.nrb.footprintdns.com'), ('DNS', '*.hotmail.com'), ('DNS', '*.internal.outlook.com'), ('DNS', '*.live.com'), ('DNS', '*.office.com'), ('DNS', '*.office365.com'), ('DNS', '*.outlook.com'), ('DNS', '*.outlook.office365.com'), ('DNS', 'attachment.outlook.live.net'), ('DNS', 'attachment.outlook.office.net'), ('DNS', 'attachment.outlook.officeppe.net'), ('DNS', 'ccs.login.microsoftonline.com'), ('DNS', 'ccs-sdf.login.microsoftonline.com'), ('DNS', 'hotmail.com'), ('DNS', 'mail.services.live.com'), ('DNS', 'office365.com'), ('DNS', 'outlook.com'), ('DNS', 'outlook.office.com'), ('DNS', 'substrate.office.com'), ('DNS', 'substrate-sdf.office.com')), 'OCSP': ('http://ocspx.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertCloudServicesCA-1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertCloudServicesCA-1-g1.crl', 'http://crl4.digicert.com/DigiCertCloudServicesCA-1-g1.crl')}
DEBUG:exchangelib.autodiscover:Trying autodiscover on https://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for https://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): autodiscover.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Trying autodiscover on http://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for http://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): autodiscover.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Attempting to get canonical name for autodiscover.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Nonexistent domain autodiscover.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Attempting to get SRV record on autodiscover.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Attempting to get SRV record on _autodiscover._tcp.outlook.ms-acdc.office.com
DEBUG:exchangelib.autodiscover:Releasing_autodiscover_cache_lock
```

**Comment by ecederstrand** [comment] 2018-02-08 19:51
Thanks for the report. Can you get an O365 autodiscover test report from https://testconnectivity.microsoft.com and find out where we're diverging from the path that the report takes to get a successful autodiscover response?

**Comment by greatman** [comment] 2018-02-08 20:03
![2018-02-08_14h58_28](https://user-images.githubusercontent.com/95754/35995369-1c0ea012-0ce1-11e8-9030-b5222238a9de.png)

![2018-02-08_15h00_57](https://user-images.githubusercontent.com/95754/35995382-24ef1298-0ce1-11e8-8d8c-4a516e67c1ec.png)

Here is the test.

**Comment by john2x** [comment] 2018-05-16 09:10
We're currently running into the same issue. The same domain https://outlook.ms-acdc.office.com is failing with invalid certificate error.

I was able to work around the issue by manually populating the autodiscover cache with the correct server as seen in the connectivity test above.

```python
import exchangelib

credentials = exchangelib.Credentials(username='user@domain.com', password='hunter2')
protocol = exchangelib.autodiscover.AutodiscoverProtocol(
    service_endpoint='https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml',
    credentials=credentials, auth_type='basic')

exchangelib.autodiscover._autodiscover_cache[('domain.com', credentials)] = protocol

account = exchangelib.Account(
    primary_smtp_address='user@domain.com',
    credentials=credentials, autodiscover=True,
    access_type=exchangelib.DELEGATE)
```

**Comment by ecederstrand** [comment] 2018-05-16 09:31
Ah, yes. I've seen this before. I have no idea why the entire world isn't affected when the TLS certificate on Office365 servers like https://outlook.ms-acdc.office.com is broken for days or weeks.

The relevant part of the log output is:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.ms-acdc.office.com
ERROR:urllib3.connection:Certificate did not match expected hostname: outlook.ms-acdc.office.com. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'Washington'),), (('localityName', 'Redmond'),), (('organizationName', 'Microsoft Corporation'),), (('commonName', 'outlook.com'),)), 'issuer': ((('countryName', 'US'),), (('organizationName', 'DigiCert Inc'),), (('commonName', 'DigiCert Cloud Services CA-1'),)), 'version': 3, 'serialNumber': '0ECD90EC9E8A91E1DED5DE9E714F0FF4', 'notBefore': 'Sep 13 00:00:00 2017 GMT', 'notAfter': 'Sep 13 12:00:00 2018 GMT', 'subjectAltName': (('DNS', '*.clo.footprintdns.com'), ('DNS', '*.nrb.footprintdns.com'), ('DNS', '*.hotmail.com'), ('DNS', '*.internal.outlook.com'), ('DNS', '*.live.com'), ('DNS', '*.office.com'), ('DNS', '*.office365.com'), ('DNS', '*.outlook.com'), ('DNS', '*.outlook.office365.com'), ('DNS', 'attachment.outlook.live.net'), ('DNS', 'attachment.outlook.office.net'), ('DNS', 'attachment.outlook.officeppe.net'), ('DNS', 'ccs.login.microsoftonline.com'), ('DNS', 'ccs-sdf.login.microsoftonline.com'), ('DNS', 'hotmail.com'), ('DNS', 'mail.services.live.com'), ('DNS', 'office365.com'), ('DNS', 'outlook.com'), ('DNS', 'outlook.office.com'), ('DNS', 'substrate.office.com'), ('DNS', 'substrate-sdf.office.com')), 'OCSP': ('http://ocspx.digicert.com',), 'caIssuers': ('http://cacerts.digicert.com/DigiCertCloudServicesCA-1.crt',), 'crlDistributionPoints': ('http://crl3.digicert.com/DigiCertCloudServicesCA-1-g1.crl', 'http://crl4.digicert.com/DigiCertCloudServicesCA-1-g1.crl')}
```

I have no idea why the connectivity test accepts this certificate anyway.

Hardcoding server hostnames fixes the issue (either by injecting the correct hostname into the autodiscover cache as you did, or by skipping autodiscover alltogether), as does disabling TLS (which is obviously a bad solution), and finally some exchangelib users will not notice this because the on-disk autodiscover cache contains a valid result from a time when the certificate was not broken.

**Comment by ecederstrand** [comment] 2018-05-16 09:49
If you are an Office365 customer, I would urge you to raise a support ticket with Microsoft. I can't see any non-horrible ways to fix this in exchangelib.

**Comment by ecederstrand** [comment] 2018-05-17 17:30
Our autodiscover implementation really needs an overhaul, BTW, to make sure we're following the autodiscover protocol 100%.

**Comment by SamCB** [comment] 2018-05-18 07:04
This particular problem seems to come from using the canonical hostname instead of the provided redirect endpoint. For several of our accounts, we get redirected to `autodiscover-s.outlook.com` which CNAMEs to `outlook.office365.com` to `outlook.ha.office365.com` to the infamous `outlook.ms-acdc.office.com`.

Manually making the Autodiscover request to `autodiscover-s.outlook.com` works without any ssl problems which also appears to be what test connectivity does. Presumably there isn't any certificate problems with `autodiscover-s.outlook.com`. Is there any reason exchangelib's autodiscover attempts to resolve the canonical hostname itself instead of letting requests figure it out?

**Comment by ecederstrand** [comment] 2018-05-18 08:02
Looking in DNS for the canonical name is part of the autodiscover protocol, but I think our bug is to prefer the canonical name if it's available in DNS. Instead, we should only use the canonical name if using the hostname fails.

It tried raising the certificate issue with Office365 support, but they couldn't care less.

**Comment by laur89** [comment] 2018-06-06 16:28
Could we also add timeout to the autodiscovery logic? I have a cron script executed every 5min  that pulls latest calendar data. Now the script hangs at

```
<snip>
INFO:exchangelib.autodiscover:Trying autodiscover on http://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for http://autodiscover.outlook.ms-acdc.office.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): autodiscover.outlook.ms-acdc.office.com
DEBUG:urllib3.connectionpool:http://autodiscover.outlook.ms-acdc.office.com:80 "HEAD /Autodiscover/Autodiscover.xml HTTP/1.1" 404 0
```

and eventually system runs out of memory, as process never terminates. This can of course be solved by making sure only one process is allowed at any given time, but timeout still seems like a reasonable safety.

**Comment by ecederstrand** [comment] 2018-06-06 16:59
Autodiscover HTTP requests already have a timeout:

https://github.com/ecederstrand/exchangelib/blob/ddd509f848ef87f9c06520e664d117944db39d63/exchangelib/autodiscover.py#L495

Autodiscovery may take a while because there could be a long list of servers to try, but it should always return at some point. Under certain failure scenarios when using a `ServiceAccount` to connect, autodiscovery make only give up after 1 hour. See the `max_wait` argument:

https://github.com/ecederstrand/exchangelib/blob/ddd509f848ef87f9c06520e664d117944db39d63/exchangelib/credentials.py#L77

**Comment by laur89** [comment] 2018-06-07 07:52
Left the script running in the foreground over the night - no sign of terminating after ~14h.

**Comment by ecederstrand** [comment] 2018-06-11 17:56
Ok, I can reproduce that here when auto discovering an Office365-hosted email address. What is really needed is a complete rewrite of the autodiscover code to more closely follow the autodiscover protocol. For now, try uncommenting this and the following 3 lines to avoid hitting and getting stuck on http://autodiscover.outlook.ms-acdc.office.com. Unfortunately, it may affect other sites that need this functionality.

https://github.com/ecederstrand/exchangelib/blob/e1fef7b6e4209443261ca1bd7c5bfc85f9822518/exchangelib/autodiscover.py#L291

**Comment by ecederstrand** [comment] 2018-08-29 06:05
FWIW, the following link describes a somewhat different autodiscover algorithm that Office 2016 follows: https://support.microsoft.com/en-us/help/3211279/outlook-2016-implementation-of-autodiscover

We may want to follow that instead of the "[classic](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-interoperability-guidance/hh352638(v=exchg.140))" autodiscover algorithm, since it provides more detail on caching and follows a O365-first approach. It seems almost everyone is moving to O365 these days anyway. It will still work with on-premise Exchange, of course.

**Comment by coperyan** [comment] 2019-06-05 15:58
I ran into this issue at one point, was able to figure out a fix. Can confirm this works, use all day every day:

`from exchangelib import DELEGATE, Account, Credentials, Message, FileAttachment, Mailbox, Configuration

#Defining outlook class
class OutlookMail:

    #Initialization
    def __init__(self,username,password,email):
        self.username = username
        self.password = password
        self.email = email
        self.subject = None
        self.account = None
        self.message = None
        self.body = None
        self.myfile = None
        self.to_recipients = []
        self.cc_recipients = []
        self.bcc_recipients = []

    #Adding recipients function
    def add_recipients(self, to_recipients, cc_recipients = None, bcc_recipients = None):
        if cc_recipients is not None:
                self.cc_recipients.extend(cc_recipients)

        if bcc_recipients is not None:
                self.bcc_recipients.extend(bcc_recipients)

        self.to_recipients.extend(to_recipients)

    #Adding message subject & body function
    def add_message(self, subject, body):
        self.email = self.email
        self.subject = subject
        self.body = body

        self.mail_credentials = Credentials(username = self.username
                                , password = self.password)

        self.mail_config = Configuration(server = 'outlook.office365.com', credentials = self.mail_credentials)

        self.account = Account(primary_smtp_address = self.email
                                , config = self.mail_config
                                , autodiscover = False
                                , access_type = DELEGATE)
        try:
                if len(self.bcc_recipients) == 0 and len(self.cc_recipients) == 0 and len(self.to_recipients) != 0:
                        self.message = Message(account = self.account
                                                , folder = self.account.sent
                                                , subject = self.subject
                                                , body = self.body
                                                , to_recipients = self.to_recipients)

                elif len(self.cc_recipients) == 0:
                        self.message = Message(account = self.account
                                , folder = self.account.sent
                                , subject = self.subject
                                , body = self.body
                                , to_recipients = self.to_recipients
                                , bcc_recipients = self.bcc_recipients)

                elif len(self.bcc_recipients) == 0:
                        self.message = Message(account = self.account
                                , folder = self.account.sent
                                , subject = self.subject
                                , body = self.body
                                , to_recipients = self.to_recipients
                                , cc_recipients = self.cc_recipients)
        except MissingEmail:
                print('Missing recipients email addresses.')


    #Adding attachment
    def add_attachment(self, file, name):
        with open(file, 'rb') as f:
                content = f.read()
        self.myfile = FileAttachment(name = name, content = content)
        self.message.attach(self.myfile)

    #Sending mail
    def send_mail(self):
        self.message.send_and_save()`

**Comment by ecederstrand** [comment] 2020-01-15 23:30
A completely rewritten autodiscover implementation was added in https://github.com/ecederstrand/exchangelib/commit/d0a7c1dfed7937f1dad89a01c4b983009ddcdd4a.

I'm closing this issue as obsolete. Feel free to reopen a new issue if you have autodiscover problems with the new implementation.

**Closed by ecederstrand** 2020-01-15 23:30 UTC
Labels: hacktoberfest

**Comment by Nirmalnk05** [comment] 2022-04-21 11:22
Connect to mailbox

> try:

           my_account = Account(
            primary_smtp_address='msbehsva@xyxy.com', 
            credentials=credentials,
            autodiscover=True, access_type=DELEGATE
            )
         if(my_account):
              print(my_account)


Getting below error :
We have already tried this URL: https://autodiscover.micron.com/Autodiscover/Autodiscover.xml

Also tried other options

> from exchangelib import DELEGATE, Account, Credentials, Configuration

      creds = Credentials(username="msbehsva@xyxy.com", password="*****")
      config = Configuration(server='outlook.office365.com', credentials=creds)
      Account(primary_smtp_address='msbehsva@xyxy.com', autodiscover=False,config=config, access_type=DELEGATE)


Tried all possibilities, nothing works out.
