### ISSUE TITLE
Empty cache file condition has not been handled

### ISSUE THREAD

**Issue by h888866j** [ecederstrand/exchangelib#810] opened 2020-10-01 20:35 UTC
Today my app met this error, looks like it is caused by it is trying to unpickle something from an empty file. KeyError is expected but during handling the KeyError exception, EOFError exception occurred. Should this EOFError be captured to move on?

<details><summary>Click to View Error Details </summary>

```
======2020-10-01 23:59:43======
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'mydomain.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\app-v1.15.0\bin\bin.py", line 627, in <module>
    main()
  File "C:\Users\admin\app-v1.15.0\bin\bin.py", line 151, in main
    b.connect(settings.ET_FOLDER_NAME)
  File "C:\Users\admin\app-v1.15.0\module\email_check.py", line 25, in connect
    self.account = Account(self.username, config=self.config, autodiscover=True,access_type='delegate')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\account.py", line 92, in __init__
    email=self.primary_smtp_address, credentials=credentials, auth_type=auth_type, retry_policy=retry_policy
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\autodiscover.py", line 205, in discover
    protocol = _autodiscover_cache[autodiscover_key]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\autodiscover.py", line 127, in __getitem__
    endpoint, auth_type, retry_policy = db[str(domain)]  # It's OK to fail with KeyError here
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
EOFError: Ran out of input 

```
</details>

**Comment by ecederstrand** [comment] 2020-10-02 07:05
I'm having difficulty reproducing this. Can you post the exact binary file contents of the cache file here? The filename is contained in `exchangelib.autodiscover.cache.AUTODISCOVER_PERSISTENT_STORAGE`

**Comment by h888866j** [comment] 2020-10-02 12:32
On my laptop, the path should be `C:\Users\username\AppData\Local\Temp\exchangelibxxxxx`. But I dont have this issue, my colleague met this issue, but he left his laptop at another city. Once I get cache files from him, I will post here. 
Thank you for you quick response!

**Comment by ecederstrand** [comment] 2020-10-05 06:44
You may be able to attach the problematic file to this issue. If not, you can run this and post the output as text.

```python
from exchangelib.autodiscover.cache import AUTODISCOVER_PERSISTENT_STORAGE
with open(AUTODISCOVER_PERSISTENT_STORAGE, 'rb') as f:
    print(f.read())
```

**Comment by h888866j** [comment] 2020-10-06 16:09
[exchangelibCache.zip](https://github.com/ecederstrand/exchangelib/files/5335183/exchangelibCache.zip)
@ecederstrand , it is an empty file

**Comment by ecederstrand** [comment] 2020-10-08 07:42
Thanks. I can't reproduce this in my test setup with an empty file, but I have pushed a commit that I believe will fix this for you. Can you please try it out?

**Comment by ecederstrand** [comment] 2020-10-15 22:00
Assuming this is fixed by the referenced commit. Closing.

**Closed by ecederstrand** 2020-10-15 22:00 UTC

**Comment by h888866j** [comment] 2020-11-24 20:02
Sorry， I missed your reply.
Today, just now myself met this error as well. This error doesn't reoccur very often, it may be hard to reproduce in real world. 
I will upgrade to latest version.
