### ISSUE TITLE
newline bug in body when sending e-mails

### ISSUE THREAD

**Issue by jjhenson** [ecederstrand/exchangelib#595] opened 2019-06-05 13:32 UTC
when using `Message.send_and_save`, I get odd behavior around new lines.

A short example:
```python
def send_email(subject: str,
               body: str,
               recipients: List[str],
               address,
               password,
               server: str = SERVER_DEFAULT):
    account = get_email_account(server, address, password)
    to_mailboxes = [Mailbox(email_address=recipient) for recipient in recipients]
    message = Message(account=account,
                      folder=account.sent,
                      subject=subject,
                      body=body,
                      to_recipients=to_mailboxes)
    message.send_and_save()

content1 = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx\nxxx"
send_email('subject', content1, ['email@address.com'])
content2 = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxx\nxxx"
send_email('subject', content2, ['email@address.com'])
content3 = "xxxxxxxxxxxxx xxxxxx\nxxx"
send_email('subject', content3, ['email@address.com'])
```
The e-mail body I receive with content1 has no newline when there ought to be one:
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx xxx
```
It has a space instead.  The other two, content2 and content3, work fine and show a new line (so a shorter line or not having a space in the content before the newline seems to stop this problem from happening).

I can't say much more about the system setup without giving details about my e-mail setup, but the server is the standard office 365 one, 'outlook.office365.com'.  I've run the above code on both windows and Linux and the same thing happens.  The fact that the problem goes away depending on length of line and spaces makes it seem like a bug, rather than something I'm not understanding about encoding.  Is that right?

**Comment by ecederstrand** [comment] 2019-06-05 13:39
How are you fetching the received body? Please show the output of something like: `print(repr(account.inbox.get(subject='subject').body))`

**Comment by ecederstrand** [comment] 2019-06-06 05:58
I cannot reproduce using this example which sends an email to itself and verifies the body attribute in the failing case in your example above:

```python
import time
from exchangelib import Credentials, Account, Message

username, password = 'john@excample.com', 'SECRET'
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)
subject = 'XYZ'
body = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx\nxxx'
Message(account=a, to_recipients=[a.primary_smtp_address], subject=subject, body=body).send()
time.sleep(60)
m = a.inbox.all().only('body').get(subject=subject)
assert body == m.body, (repr(body), repr(m.body))
m.delete()
```

**Comment by ecederstrand** [comment] 2019-06-12 10:00
Closing. Feel free to reopen if you get time to post the results of the test code above :-)

**Closed by ecederstrand** 2019-06-12 10:00 UTC

**Comment by gabbobersi** [comment] 2022-04-14 11:47
I had a similar issue. [This post](https://stackoverflow.com/questions/16063312/new-lines-r-n-are-not-working-in-email-body) on StackOverflow explain how to use new line, based on how you are sending email (the format):

If you are sending HTML email then use <BR> (or <BR />, or </BR>) as stated.
If you are sending a plain text email then use %0D%0A
\r = %0D (Ctrl+M = carriage return)
\n = %0A (Ctrl+A = line feed)

NOTE: For me, since I'm send a mail in the "default" format which is HTML, <br> is working fine. I've tested the OOF in an Exchange server and also to a gmail.
