### ISSUE TITLE
Accessing public folders

### ISSUE THREAD

**Issue by michaelmontagne** [ecederstrand/exchangelib#396] opened 2018-04-27 14:41 UTC
I've heard that I can get to Public Folders using your library but I'm having a terrible time.  Except for that, the code you have developed is exactly what i needing right now.  I can get the object but there is nothing in it (total_count=0 and walk is empty.  There must be something simple that I am missing.
In Outlook I can see what I am searching for but in OWA I cannot.  I do not believe that public folders are shown in OWA though.

```python
credentials = Credentials('user', 'pw')
config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account(primary_smtp_address='user', config=config,
                  autodiscover=False, access_type=DELEGATE)
print (dir(account.public_folders_root))
print (account.public_folders_root.total_count)
print (account.public_folders_root.walk())
```

**Comment by ecederstrand** [comment] 2018-05-15 07:12
This may be related to #391. My spare time is scarce ATM, but I'll have a look as soon as possible.

**Comment by ecederstrand** [comment] 2018-05-16 19:46
Is the `user` in the credentials and the the account the same? If not, then due to the hack here: https://github.com/ecederstrand/exchangelib/blob/71def9d94220eb639241b6a56a164cf4b7b9b593/exchangelib/folders.py#L57

we may end up requesting the public root folder of the "credentials" user, not the "account" user.

**Comment by michaelmontagne** [comment] 2018-05-16 20:08
Yes.  Same account (if I understand the question).  It is my personal account and I have access to public folders in Outlook but NOT when logging in through OWA.

Mike Montagne | associate / IT Director | opsisarchitectureLLP | o:503.525.9511

**Comment by illyax** [comment] 2018-07-17 13:03
Hey @michaelmontagne have you managed to solve it?

**Comment by michaelmontagne** [comment] 2018-07-17 18:02
Nope.  Stumped. I moved all the contact items I had in PF to a “Public” user and shared it.  Then everything worked great.

Mike Montagne | associate / IT Director | opsisarchitectureLLP | o:503.525.9511

**Comment by rnk-de** [comment] 2018-09-07 10:15
I stumbled upon this issue and it seems that there isn't any search for subfolders when accessing special folders. After looking at the requests i can see that there is a FindFolder request for the root folder, but not for the public folders.

```xml
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="W. Europe Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:FindFolder Traversal="Deep">
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:ChildFolderCount"/>
          <t:FieldURI FieldURI="folder:EffectiveRights"/>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:ParentFolderId"/>
          <t:FieldURI FieldURI="folder:TotalCount"/>
          <t:FieldURI FieldURI="folder:UnreadCount"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:IndexedPageFolderView BasePoint="Beginning" MaxEntriesReturned="100" Offset="0"/>
      <m:ParentFolderIds>
        <t:DistinguishedFolderId Id="root">
          <t:Mailbox>
            <t:EmailAddress>example@example.com</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:ParentFolderIds>
    </m:FindFolder>
  </s:Body>
</s:Envelope>
```

```xml
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="W. Europe Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:GetFolder>
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:ChildFolderCount"/>
          <t:FieldURI FieldURI="folder:EffectiveRights"/>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:ParentFolderId"/>
          <t:FieldURI FieldURI="folder:TotalCount"/>
          <t:FieldURI FieldURI="folder:UnreadCount"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:FolderIds>
        <t:DistinguishedFolderId Id="publicfoldersroot"/>
      </m:FolderIds>
    </m:GetFolder>
  </s:Body>
</s:Envelope>

```
As a workaround putting the public folders object in a FolderCollection object and calling find_folders does seem to do the trick:

```python
public = account.public_folders_root
coll = FolderCollection(account=account, folders=[public])

for f in coll.find_folders(depth="Shallow"):
    print(f.name)

```

**Comment by ecederstrand** [comment] 2018-09-07 12:10
Ah, so the public folders tree is entirely separate from the root folder? I didn't know! This definitely needs to be fixed.

**Comment by ecederstrand** [comment] 2018-09-12 06:46
I just changed `account.public_folders_root` to fetch its own folder hierarchy, so `account.public_folders_root.walk()` should now find all the public folders. I don't have access to an account that has any public folders, so I can't test this myself, unfortunately.

**Comment by rnk-de** [comment] 2018-09-12 10:56
I tested your latest changes and I still can't find any folders when using the `walk()` function. Looking at the requests I can see a `GetFolder` request querying a bunch of WELLKNOWN folders, but I still can't see any `FindFolder` requests for the PublicFoldersRoot.

**Comment by ecederstrand** [comment] 2018-09-12 14:49
I think I see the problem. I'm working on a fix now.

**Comment by ecederstrand** [comment] 2018-09-20 11:05
It's a fairly complex change because we need to redesign parts of the folder hierarchy handling. I'll try to have it done sometime next week, but can't promise anything. If I don't make it, I'll post a status here.

**Comment by BenJoParadise** [comment] 2018-09-20 11:08
Awesome! Thanks you so much for everything you're doing, i very much appreciate it.

**Comment by ecederstrand** [comment] 2018-09-24 06:58
I pushed a fix that should support public and archive folders. Unfortunately, I don't have access to an account I can test this on. Please test and report back!

**Comment by michaelmontagne** [comment] 2018-09-24 16:52
Great news!  I’d love to test it.  Do I just pip install and it will pull the changes?  Should I be worried about my code breaking that doesn’t access public folders?


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by ecederstrand** [comment] 2018-09-24 20:14
The change is only on the master branch until someone verifies if the changes work as intended. Here's how to install directly from GitHub:

```
pip uninstall exchangelib
pip install git+https://github.com/ecederstrand/exchangelib.git
```

**Comment by michaelmontagne** [comment] 2018-09-24 20:30
Doesn't seem to be working for me.  walk() returns None.
`import os, sys
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, GSSAPI, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version, FolderCollection

credentials = Credentials('user', 'pw')
config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account(primary_smtp_address='user', config=config,
                  autodiscover=False, access_type=DELEGATE)

pf = account.public_folders_root
print (pf.total_count)
print (pf.walk().get_folders())`

` ~/Desktop : python testo365.py 
0
Traceback (most recent call last):
  File "testo365.py", line 14, in <module>
    print (pf.walk().get_folders())
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 283, in get_folders
    if not self.folders:
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 96, in folders
    return list(self._folders)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 413, in _walk
    for c in self.children:
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 102, in __iter__
    for f in self.folders:
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 96, in folders
    return list(self._folders)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 1432, in get_children
    for f in self._folders_map.values():
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 1497, in _folders_map
    for cls in self.WELLKNOWN_FOLDERS
TypeError: 'NoneType' object is not iterable`

If it helps, I attached what public folders looks like in Outlook.
![pf](https://user-images.githubusercontent.com/22603517/45977227-cc4c8c80-bffd-11e8-81e3-9c6a16d0481b.PNG)

**Comment by ecederstrand** [comment] 2018-09-24 20:35
Thanks for the test. That was an error on my part. I have pushed a fix now.

**Comment by michaelmontagne** [comment] 2018-09-24 20:51
different Error:
`0
Traceback (most recent call last):
  File "testo365.py", line 14, in <module>
    print (pf.walk().folders)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 96, in folders
    return list(self._folders)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 413, in _walk
    for c in self.children:
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 102, in __iter__
    for f in self.folders:
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/cached_property.py", line 73, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 96, in folders
    return list(self._folders)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 1432, in get_children
    for f in self._folders_map.values():
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/folders.py", line 1516, in _folders_map
    for f in FolderCollection(account=self.account, folders=[self]).find_folders(depth=DEEP):
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 1012, in call
    page_size=self.chunk_size,
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 374, in _paged_call
    parsed_pages = [self._get_page(message) for message in response]
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 419, in _get_page
    rootfolder = self._get_element_container(message=message, name='{%s}RootFolder' % MNS)
  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 287, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidOperation: Deep traversal queries are not allowed on public folders.`

**Comment by ecederstrand** [comment] 2018-09-24 20:55
Ok. I just pushed a fix for that :-)

**Comment by michaelmontagne** [comment] 2018-09-24 21:10
I think you've done it.  This is returned.  Now i just need to figure our what to do with that!
`[Messages(PublicFoldersRoot(<exchangelib.account.Account object at 0x102372f90>, u'[self]', 'IPM_SUBTREE', 0, 0, 2, None, 'AQEuAAADGkRzkKpmEc2byACqAC/EWgMA9XUdkf5VLUaSG0SJPcckqwAAAwIAAAA=', 'AQAAABYAAAD1dR2R/lUtRpIbRIk9xySrAAAl5t3s'), 'Project', 0, 0, 110, 'IPF.Note', 'AQEuAAADGkRzkKpmEc2byACqAC/EWgMAKKjxFZcwHkWr4WZfKCaBrAAAAxYAAAA=', 'AQAAABYAAAD1dR2R/lUtRpIbRIk9xySrAADIDLxE'), Messages(PublicFoldersRoot(<exchangelib.account.Account object at 0x102372f90>, u'[self]', 'IPM_SUBTREE', 0, 0, 2, None, 'AQEuAAADGkRzkKpmEc2byACqAC/EWgMA9XUdkf5VLUaSG0SJPcckqwAAAwIAAAA=', 'AQAAABYAAAD1dR2R/lUtRpIbRIk9xySrAAAl5t3s'), 'Office', 0, 0, 2, 'IPF.Note', 'AQEuAAADGkRzkKpmEc2byACqAC/EWgMAKKjxFZcwHkWr4WZfKCaBrAAAAxgAAAA=', 'AQAAABYAAAD1dR2R/lUtRpIbRIk9xySrAAAAAMeD')]`

**Comment by ecederstrand** [comment] 2018-09-24 21:18
Great! You now have two folders, "Project" and "Office", that you should be able to use like any other exchangelib folder. `account.public_root / 'Project'` should work and let you navigate to the "Project" folder, and `(account.public_root / 'Project').all()` would get all items in that folder.

I can't see from the screenshot if these two folders contain subfolders, but the error message "ErrorInvalidOperation: Deep traversal queries are not allowed on public folders." means we can't get the subfolders in one go. We may have to do some more modifications before you can access the subfolders easily, without resorting to the `FolderCollection` workaround posted above.

**Comment by michaelmontagne** [comment] 2018-09-24 21:31
I did have to resort to the workaround because there are indeed subfolders.  But it works wonderfully.  Good job!


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by ecederstrand** [comment] 2018-09-24 21:33
Ok. Thanks for all the testing! I may come up with a workaround for the subfolders. Let's keep this issue open for now.

**Comment by ecederstrand** [comment] 2018-09-25 07:37
Hi @michaelmontagne 

I'm curious whether deep folder traversal is only forbidden on the root public folder, or on all subfolders. Can you run this for me?:

```python
coll = FolderCollection(account=account, folders=[account.public_root / 'Project'])

# Should work
for f in coll.find_folders(depth="Shallow"):
    print(f.name)

# Will maybe fail
for f in coll.find_folders(depth="Deep"):
    print(f.name)
```

**Comment by michaelmontagne** [comment] 2018-09-25 16:34
With one small adjustment:

coll = FolderCollection(account=account, folders=[account.public_folders_root / 'Project'])


The top one works and the lower one fails:

Traceback (most recent call last):

  File "testo365.py", line 29, in <module>

    for f in coll.find_folders(depth="Deep"):

  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 1012, in call

    page_size=self.chunk_size,

  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 374, in _paged_call

    parsed_pages = [self._get_page(message) for message in response]

  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 419, in _get_page

    rootfolder = self._get_element_container(message=message, name='{%s}RootFolder' % MNS)

  File "/Users/michaelmontagne/.pyenv/versions/2.7.14/lib/python2.7/site-packages/exchangelib/services.py", line 287, in _get_element_container

    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)

exchangelib.errors.ErrorInvalidOperation: Deep traversal queries are not allowed on public folders.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

________________________________

**Comment by ecederstrand** [comment] 2018-09-27 10:37
Hi @michaelmontagne 

Thanks for your latest test. I attempted to fix the deep traversal issue now. Can you please update and test this?

```python
print(account.public_folders_root.tree())
```

It should print the full folder structure of the public folders. It may take a while if you have a lot of public folders.

**Comment by ecederstrand** [comment] 2018-09-27 18:49
Hmm, that's going to be difficult to debug without access to an actual account. Would you be able to provide me temporary access to an account that has public folders with subfolders? We can take it offline if need be.

**Comment by michaelmontagne** [comment] 2018-09-27 19:01
Let me work on that.  Might be next week though.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by michaelmontagne** [comment] 2018-09-27 22:03
Is readonly access OK?  There is a ViewOnly management group that might be a good fit if it is.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by ecederstrand** [comment] 2018-10-09 10:45
Hi @michaelmontagne Do you think you can arrange access so I can test this? I'd like to close the issue but would prefer confirmation of some sort that public folder access works correctly.

**Comment by michaelmontagne** [comment] 2018-10-09 16:17
Yes. Hold on.  Sorry.  Big weekend.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by michaelmontagne** [comment] 2018-10-09 18:05
I will get to it this afternoon.  How long do you think you will want access?


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by michaelmontagne** [comment] 2018-10-09 23:40
Login: pythondev@opsisarch.com<mailto:pythondev@opsisarch.com>
Pw: W31rdbl00d

Let me know when you are done so I can delete the account.  Good luck.


Mike Montagne | IT Director, associate | opsis architecture LLP | o:503.525.9511 d:503.943.6229 | www.opsisarch.com<http://www.opsisarch.com>

**Comment by ecederstrand** [comment] 2018-10-10 18:01
Latest fixes to public folders confirmed off-list to be working. Full listing and traversal of public folders is now possible.

**Closed by ecederstrand** 2018-10-10 18:01 UTC
