### ISSUE TITLE
exchangelib.errors.ErrorNoRespondingCASInDestinationSite: Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request.

### ISSUE THREAD

**Issue by hjain371** [ecederstrand/exchangelib#857] opened 2021-02-04 09:46 UTC
Getting an below error while fetching mails of last 3 month
exchangelib.errors.ErrorNoRespondingCASInDestinationSite: Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request.

Below are the config settings I am using to create the account (along with proxy):
config = Configuration(server=server, credentials=cred, auth_type="NTLM")
  Account(primary_smtp_address=email, autodiscover=False,config=config, access_type=DELEGATE)

PS: I can see many people suggested to add  service.getHttpHeaders().put("X-AnchorMailbox","smtpemailaddress");
but how and where to add this in python code

**Comment by ecederstrand** [comment] 2021-02-05 12:57
Which version of exchangelib is this? It was supposedly fixed quite a while ago: https://github.com/ecederstrand/exchangelib/commit/3b773ec924a6bed70cc0a4c410efeb28d3ed4994

**Comment by ecederstrand** [comment] 2021-02-10 08:18
@hjain371 Did upgrading exchangelib fix this issue for you?

**Comment by hjain371** [comment] 2021-02-11 15:39
Hi,

I requested the team to upgrade the version to 3+,it will take sometime to
see if it will work with new version

**Comment by ecederstrand** [comment] 2021-02-16 02:06
I'm assuming this will be fixed with an upgrade. Feel free to reopen the issue if you still see this with the newest version of exchangelib.

**Closed by ecederstrand** 2021-02-16 02:06 UTC

**Comment by hjain371** [comment] 2021-02-18 15:46
Hi,
I have installed the newest version 3.2.1 but I am still getting the same issue, strange thing is I dont get this issue if I fetch last 15 days mail only

**Comment by ecederstrand** [comment] 2021-02-18 15:49
In that case, I think your best option is to contact your Exchange admins and ask them to find out what the problem is.

Also, the latest version is actually 3.3.2. See https://pypi.org/project/exchangelib/
