### ISSUE TITLE
Access to shared custom calendar

### ISSUE THREAD

**Issue by AssassiaN** [ecederstrand/exchangelib#526] opened 2018-12-13 12:17 UTC
Hi,

I'm looking for how to access shared "custom" calendars.
Ex: we have 2 accounts: "ak" and "aj". "aj" shared with "ak" 2 calendars: "default" and new calendar called "test".
Access to "default" calendar works propertly:
```python
aj_account = Account(primary_smtp_address=aj_email,
                     credentials=ak_credentials, 
                     autodiscover=True,
                     access_type=DELEGATE)
for x in aj_account.calendar.all():
    print x.subject
```

but when i tried access "test" calendar:
```python
aj_account = Account(primary_smtp_address=aj_email,
                     credentials=ak_credentials, 
                     autodiscover=True,
                     access_type=DELEGATE)
for x in (aj_account.calendar / "test").all():
    print x.subject
```
got exception: `ErrorFolderNotFound: No subfolder with name 'test'`.
Tried both "Editor" and "Full details" permissions.

Is there a way to access shared calendars other then default calendar?

Thanks.

**Comment by AssassiaN** [comment] 2018-12-13 12:20
Also tried `account.protocol.get_free_busy_info`.
Got empty "calendar_events" field, when in "test" calendar was fullday meeting.

**Comment by ecederstrand** [comment] 2018-12-14 07:13
To access a shared calendar, you must access it through the account that owns the calendar. So you create an `Account` instance for the owner of the calendar.

It's possible that you can't access the "test" folder because it was not attached where you expect it to be. To find the location of the "test" folder, try printing your entire folder hierarchy (`print(root.tree())`).

**Comment by ecederstrand** [comment] 2018-12-14 07:14
It's possible that `get_free_busy_info()` only looks in the default calendar of an account. You will have to look up in Microsoft documentation to find the intended behaviour.

**Comment by AssassiaN** [comment] 2018-12-14 09:55
According to [Setup and connecting](https://github.com/ecederstrand/exchangelib#setup-and-connecting), i create `Account` instance where `primary_smtp_address` is email of calendar owner and `credentials` of account that has access to calendars. Is this correct?

For `aj_account.root.tree()`
i got:
```
u'root
└── Freebusy Data'
```

Also, tried `GetUserAvailabilityRequest` SOAP request and yes, it only looks  in the default calendar. Strange logic.

**Comment by ecederstrand** [comment] 2019-01-02 12:42
It looks like AK has insufficient permissions to list folders in AJ's account and to access non-default calendars of AJ.

**Comment by ecederstrand** [comment] 2019-01-09 11:56
Hi @AssassiaN Dod you find a solution to this problem?

**Comment by ecederstrand** [comment] 2019-01-10 20:55
Closing. Feel free to re-open if you have additional information.

**Closed by ecederstrand** 2019-01-10 20:55 UTC
