### ISSUE TITLE
`folder.parts` no longer returns root of hierarchy in list of parts (5.2.1)

### ISSUE THREAD

**Issue by jcalero** [ecederstrand/exchangelib#1295] opened 2024-04-15 15:23 UTC
**Describe the bug**
Unsure if this is a bug or intended behaviour, but `folder.parts is no longer returning the root of the hierarchy as part of the parts.

I've narrowed down the change to somewhere between 5.2.0 and 5.2.1 so this is a very recent change, but I can't see it documented nor can I spot what introduced this change in the code. Commit diff here: https://github.com/ecederstrand/exchangelib/compare/v5.2.0...v5.2.1

On 5.2.0 doing `folder.parts` returns this, see `Root(...)` as the first item in the parts list, and then the `AllCategorizedItems` folder:
```
[
  Root(<exchangelib.account.Account object at 0x7fef2668b410>, '[self]', 'root', 6, 0, 75, None, 'AAMkADgyODUyNjk3LTNiMGMtNDFjOC05MjNjLTU2Mzk2MDlkMjIzZQAuAAAAAAAXNFa2HBqhRpS7R15jTMr7AQB/3lh7Ez+rQI9hyH8O9PaHAAAAAAEBAAA=', 'AQAAABYAAAB/3lh7Ez+rQI9hyH8O9PaHAAIWoSDK'), 
  Messages(Root(<exchangelib.account.Account object at 0x7fef2668b410>, '[self]', 'root', 6, 0, 75, None, 'AAMkADgyODUyNjk3LTNiMGMtNDFjOC05MjNjLTU2Mzk2MDlkMjIzZQAuAAAAAAAXNFa2HBqhRpS7R15jTMr7AQB/3lh7Ez+rQI9hyH8O9PaHAAAAAAEBAAA=', 'AQAAABYAAAB/3lh7Ez+rQI9hyH8O9PaHAAIWoSDK'), 'AllCategorizedItems', 0, 0, 0, 'IPF.Note', 'AAMkADgyODUyNjk3LTNiMGMtNDFjOC05MjNjLTU2Mzk2MDlkMjIzZQAuAAAAAAAXNFa2HBqhRpS7R15jTMr7AQB/3lh7Ez+rQI9hyH8O9PaHAAA4aLayAAA=', 'BwAAABYAAAB/3lh7Ez+rQI9hyH8O9PaHAAA4aB2d')
]
```

On 5.2.1 doing `folder.parts` returns this, note only `AllCategorizedItems` is returned.
```
[
  AllCategorizedItems(Root(<exchangelib.account.Account object at 0x7fa9fc280550>, '[self]', 'root', 6, 0, 75, None, 'AAMkADgyODUyNjk3LTNiMGMtNDFjOC05MjNjLTU2Mzk2MDlkMjIzZQAuAAAAAAAXNFa2HBqhRpS7R15jTMr7AQB/3lh7Ez+rQI9hyH8O9PaHAAAAAAEBAAA=', 'AQAAABYAAAB/3lh7Ez+rQI9hyH8O9PaHAAIWoSDK'), 'AllCategorizedItems', 0, 0, 0, 'IPF.Note', 'AAMkAGRmNjNkODNmLTZlNjctNDE4My1iY2FjLTU2MzBjMThkMDY5NwAuAAAAAAD33TBqFrORTIO7B5TTtus6AQCfzJfBcrZbQK0CxYz/337dAABIdV7BAAA=', 'BwAAABYAAACfzJfBcrZbQK0CxYz/337dAABIdCHB')
]
```

**To Reproduce**
Install 5.2.1 and do Folder.parts on any folder, compare with 5.2.0 to see that 5.2.1 doesn't return the root item.

**Expected behavior**
I didn't expect the behaviour to change between 5.2.0 and 5.2.1, if it has intentionally it would be good to understand the reasoning.

**Comment by ecederstrand** [comment] 2024-04-15 17:05
That's weird. I cannot reproduce this, and it's also covered by the test suite:

```python
>>> from exchangelib.folders import AllCategorizedItems
>>> print([f.name for f in account.calendar.parts])
['root', 'Informationslagerets øverste niveau', 'Kalender']
>>> print([f.name for f in account.root.get_default_folder(AllCategorizedItems).parts])
['root', 'AllCategorizedItems']
```

**Comment by jcalero** [comment] 2024-04-16 09:40
Hmm, strange, the version update is literally the only change I made, but let me dig into our code a bit more, the issue might be further up the chain.

**Comment by jcalero** [comment] 2024-04-16 15:39
Ok, @ecederstrand, so I've followed our code up to try to close in on where the difference is, and it seems to be happening in this case on a query with `FolderCollection.find_folders()`.

Here's a reproduction:
```
>>> from exchangelib import Account, FolderCollection
>>> print(exchangelib.__version__)
5.2.1
>>> account = Account(...)
>>> folder = next(FolderCollection(account=account, folders=[account.root]).find_folders())
>>> [f.name for f in folder.parts]
['AllCategorizedItems']
```
```
>>> from exchangelib import Account, FolderCollection
>>> print(exchangelib.__version__)
5.2.0
>>> account = Account(...)
>>> folder = next(FolderCollection(account=account, folders=[account.root]).find_folders())
>>> [f.name for f in folder.parts]
['root', 'AllCategorizedItems']
```

Let me know if we're doing something odd here?

**Comment by ecederstrand** [comment] 2024-04-23 18:08
@jcalero Did you get a chance to debug this?

**Comment by jcalero** [comment] 2024-04-24 09:36
I haven't no, sorry, had to shift my focus onto something else for now. Feel free to close this, I can re-open if I get time to debug this.

**Comment by ecederstrand** [comment] 2024-04-24 09:56
Actually, there's a slight possibility that https://github.com/ecederstrand/exchangelib/commit/d9035d03960797f9277381845e4ec98f837798ea fixes this. Can you give it a try?

**Comment by ecederstrand** [comment] 2024-04-29 09:30
Closing, but feel free to update here if you get a chance to look at it again.

**Closed by ecederstrand** 2024-04-29 09:30 UTC

**Comment by jcalero** [comment] 2024-05-02 08:14
Had a chance to test 5.3.0 now and it has indeed fixed the issue, thanks!
