### ISSUE TITLE
Cannot update calendar start/end time, "StartTimeZone is invalid"

### ISSUE THREAD

**Issue by poskadesign** [ecederstrand/exchangelib#243] opened 2017-09-12 12:55 UTC
Hi,

this is a pretty self-explanatory piece of code. 

```python
from django.utils import timezone

calendar_item.start = EWSDateTime.from_datetime(timezone.now())
calendar_item.save(update_fields=['start'])
```

The problem is when i run it, I get the following error:
```python
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:StartTimeZone" />)
```

The `timezone.now()` returns a timezone-aware timestamp and I double-checked, that the `EWSDateTime` constructed from is also aware.
What could be the problem?

**Comment by ecederstrand** [comment] 2017-09-12 13:02
You need to use the timezone class provided by exchangelib. See https://github.com/ecederstrand/exchangelib#dates-datetimes-and-timezones

**Comment by poskadesign** [comment] 2017-09-12 13:17
I just tried this code though it gave the same result.

```
from django.utils import timezone
from exchangelib import UTC, UTC_NOW

now = timezone.now()
ex_item.start = UTC.localize(EWSDateTime(year=now.year, month=now.month, day=now.day, hour=now.hour, minute=now.minute))
ex_item.save(update_fields=['start'])
```

**Comment by ecederstrand** [comment] 2017-09-12 13:32
Hmm. Which Exchange version is this? `print(your_account.version)`

**Comment by poskadesign** [comment] 2017-09-12 13:34
The version is `Build=15.20.56.11, API=Exchange2016, Fullname=Microsoft Exchange Server 2016`. I'm using Office 365.

**Comment by poskadesign** [comment] 2017-09-13 06:47
If it helps this is the request and response from the debug log after querying a calendar item and executing `item.save(update_fields=['start'])`:

request:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2016"/>
    <t:ExchangeImpersonation>
      <t:ConnectingSID>
        <t:PrimarySmtpAddress>Room1@someprovider.onmicrosoft.com</t:PrimarySmtpAddress>
      </t:ConnectingSID>
    </t:ExchangeImpersonation>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="FLE Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:UpdateItem ConflictResolution="AutoResolve" MessageDisposition="SaveOnly" SendMeetingInvitationsOrCancellations="SendToNone" SuppressReadReceipts="true">
      <m:ItemChanges>
        <t:ItemChange>
          <t:ItemId ChangeKey="XXXXXXXXXXXX+XXXXXXXXXXXXXXXX/XXXXXXXXXX" Id="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="/>
          <t:Updates>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:Start"/>
              <t:CalendarItem>
                <t:Start>2017-09-13T08:00:00Z</t:Start>
              </t:CalendarItem>
            </t:SetItemField>
            <t:SetItemField>
              <t:FieldURI FieldURI="calendar:StartTimeZone"/>
              <t:CalendarItem>
                <t:StartTimeZone Id="UTC" Name=""/>
              </t:CalendarItem>
            </t:SetItemField>
          </t:Updates>
        </t:ItemChange>
      </m:ItemChanges>
    </m:UpdateItem>
  </s:Body>
</s:Envelope>
```

response:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="20" MajorBuildNumber="35" MinorBuildNumber="21" Version="V2017_07_11"/>
  </s:Header>
  <s:Body>
    <m:UpdateItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:UpdateItemResponseMessage ResponseClass="Error">
          <m:MessageText>Set action is invalid for property.</m:MessageText>
          <m:ResponseCode>ErrorInvalidPropertySet</m:ResponseCode>
          <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          <m:MessageXml>
            <t:FieldURI FieldURI="calendar:StartTimeZone"/>
          </m:MessageXml>
          <m:Items/>
        </m:UpdateItemResponseMessage>
      </m:ResponseMessages>
    </m:UpdateItemResponse>
  </s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment] 2017-09-13 07:38
Hmm. This is supposed to work ,and I see no obvious errors. Until I have more time to look into this, here are some MSDN docs on [setting](https://msdn.microsoft.com/en-us/library/office/dn789029(v=exchg.150).aspx) and [updating](https://msdn.microsoft.com/en-us/library/office/dn789030(v=exchg.150).aspx) timezones via EWS.

**Comment by poskadesign** [comment] 2017-09-13 07:43
Thanks, I'll take a look. I am just having some trouble understanding, whether the EWS is supposed to have the same interface with all versions of Exchange or not. Because most documentation pages state that they apply to Exchange 2013 but no links to version 2016 documents.

**Comment by ecederstrand** [comment] 2017-09-13 07:55
No, EWS has different behaviour depending on the version. Usually, the supported versions for an XML element are stated at the top of an MSDN page. Timezones are a mess because there are 3 different fields, supported in various combinations on different EWS versions, and additionally you can state the timezone of any given datetime value by using ISO 8601 format.

**Comment by ecederstrand** [comment] 2017-09-13 18:37
Hmm, this is strange. I just tested against an Office365 account and have no problems:

```python
from exchangelib import DELEGATE, Credentials, Account, UTC_NOW, CalendarItem

c = Credentials('username', 'password')
a = Account(
    primary_smtp_address=c.username, credentials=c, 
    access_type=DELEGATE, autodiscover=True
)

c = CalendarItem(
    folder=a.calendar, 
    start=UTC_NOW(), 
    end=UTC_NOW() + timedelta(hours=2), 
    subject='test'
)
c.save()
c.start = UTC_NOW() - timedelta(hours=3)
c.save(update_fields=['start'])
print(a.version)
# Build=15.20.35.23, API=Exchange2016, Fullname=Microsoft Exchange Server 2016
```

The last `save()` produces:

Request:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
            xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
            xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
    <s:Header>
        <t:RequestServerVersion Version="Exchange2016"/>
        <t:TimeZoneContext>
            <t:TimeZoneDefinition Id="Romance Standard Time"/>
        </t:TimeZoneContext>
    </s:Header>
    <s:Body>
        <m:UpdateItem ConflictResolution="AutoResolve" MessageDisposition="SaveOnly"
                      SendMeetingInvitationsOrCancellations="SendToNone" 
                      SuppressReadReceipts="true">
            <m:ItemChanges>
                <t:ItemChange>
                    <t:ItemId ChangeKey="AAA5tFsG" Id="9nIAAA="/>
                    <t:Updates>
                        <t:SetItemField>
                            <t:FieldURI FieldURI="calendar:Start"/>
                            <t:CalendarItem>
                                <t:Start>2017-09-13T15:29:02Z</t:Start>
                            </t:CalendarItem>
                        </t:SetItemField>
                        <t:SetItemField>
                            <t:FieldURI FieldURI="calendar:StartTimeZone"/>
                            <t:CalendarItem>
                                <t:StartTimeZone Id="UTC" Name=""/>
                            </t:CalendarItem>
                        </t:SetItemField>
                    </t:Updates>
                </t:ItemChange>
            </m:ItemChanges>
        </m:UpdateItem>
    </s:Body>
</s:Envelope>
```
Response:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="15" MinorVersion="20" 
                             MajorBuildNumber="35" MinorBuildNumber="23"
                             Version="V2017_07_11" 
                             xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
    </s:Header>
    <s:Body>
        <m:UpdateItemResponse 
                              xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                              xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                              xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:UpdateItemResponseMessage ResponseClass="Success">
                    <m:ResponseCode>NoError</m:ResponseCode>
                    <m:Items>
                        <t:CalendarItem>
                            <t:ItemId
                                    Id="9nIAAA=" ChangeKey="AAA5tFsH"/>
                        </t:CalendarItem>
                    </m:Items>
                    <m:ConflictResults>
                        <t:Count>0</t:Count>
                    </m:ConflictResults>
                </m:UpdateItemResponseMessage>
            </m:ResponseMessages>
        </m:UpdateItemResponse>
    </s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment] 2017-09-13 18:40
Maybe your server does not have the `UTC` timezone installed? You can test with `account.protocol.get_timezones()`

**Comment by poskadesign** [comment] 2017-09-14 06:50
I changed the timestamp construction from `EWSDateTime.from_datetime(timezone.now())` to `UTC_NOW()` and it works. I think there is a distinction of how `from_datetime` and `UTC_NOW` form the tzinfo parameter. Anyway, thanks for the help, I'll keep on experimenting.

**Comment by ecederstrand** [comment] 2017-09-17 12:24
I tried this example but am unable to reproduce:

```python
import os
from exchangelib import Account, Credentials, CalendarItem, EWSDateTime

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_project.settings")
from django.utils import timezone

a = Account(email, credentials=Credentials('email', 'password'), autodiscover=True)
start = EWSDateTime.from_datetime(timezone.now())
end = start + timedelta(hours=2)
c = CalendarItem(
    folder=a.calendar, 
    subject='django timezone test', 
    start=start, 
    end=end,
)
c.save()
c.start = EWSDateTime.from_datetime(timezone.now())
c.save(update_fields=['start'])
```

**Comment by poskadesign** [comment] 2017-09-18 07:55
I've found a scenario when this happens. This is how to reproduce:

- You have an account (A1) and a room (R1).
- Create a calendar item for A1 and add R1 to resource list
- Fetch the calendar item **from R1 mailbox**.
- Attempt to save it.

So this happens when you attempt to edit a calendar item not by impersonating the organizer but the attendee/resource instead.

**Comment by ecederstrand** [comment] 2017-09-18 13:17
Hmm. My test account doesn't have access to resources, so I have no easy way to debug this.

**Comment by poskadesign** [comment] 2017-09-18 13:53
The same holds for attendees, you can try fetching the calendar item as an attendee.

**Comment by ecederstrand** [comment] 2017-09-18 14:38
Maybe it's not possible to edit appointments you have been invited to as a required attendee? Although the `effective_rights` field on the ones I have in my calendar seem to indicate otherwise.

**Comment by poskadesign** [comment] 2017-09-18 14:48
I am too, almost certain that the problem is permission related. Still the error returned by the Exchange server is not by far indicative of that. This is why sometimes I'm frustrated with Microsoft-branded software.

**Comment by ecederstrand** [comment] 2017-09-19 09:10
Yeah, if this is indeed a permission error, then the error message is quite misleading.

Can you try updating another field, e.g. `subject`? That would indicate whether this is a general problem, or specific to `calendar:StartTimeZone`.

**Comment by poskadesign** [comment] 2017-09-19 13:07
I tried modifying other attributes but this error only occurs when I add `start` or `end` in the `update_fields` list on save. I get a different error when I try to modify the attendee list but that's another story.

**Comment by ecederstrand** [comment] 2017-10-25 08:08
Closing. I'm not sure we can do anything here to improve exchangelib, at least until we understand the exact rules of what is editable and what isn't. Feel free to reopen if you have more info :-)

**Closed by ecederstrand** 2017-10-25 08:08 UTC
