### ISSUE TITLE
How do I get users in a Distribution List

### ISSUE THREAD

**Issue by sunilsunderrajdev** [ecederstrand/exchangelib#552] opened 2019-01-30 14:19 UTC
I get this error when I provide a DL as primary_smtp_address
exchangelib.errors.ErrorNonExistentMailbox: The SMTP address has no mailbox associated with it.

**Comment by ecederstrand** [comment] 2019-01-30 14:33
You cannot connect to a distribuiton list, AFAIK. You need to find the distribution list item in your contacts folder, and then check the `members` attribute:

```python
from exchangelib.items import DistributionList
for items in account.contacts.all():
    if isinstance(item, DistributionList):
        print(item.display_name)
        for member in item.members:
            print('\t', member)
```

**Comment by sunilsunderrajdev** [comment] 2019-01-30 14:53
That doesn't help. This is for a Production application and hence cannot query personal mailboxes.

Any other exchange library you are aware of which would allow me to query DL's?

**Comment by ecederstrand** [comment] 2019-01-31 06:17
If you can do it via EWS, then there's a good chance that it's easy to add to exchangelib if it isn't already possible. But first, please look for the EWS documentation describing how to do this.

**Comment by sunilsunderrajdev** [comment] 2019-01-31 15:06
I tried using a few client libraries and get this error. The same credentials worked in exchangelib. Has it something to do with the way Exchange authenticates

url = "https://XXX.com/EWS/Services.wsdl"
location = "https://XXX.com"

ntlm = WindowsHttpAuthenticated(username=username,password=password)
client = Client(url=url,location=location,transport=ntlm)

urllib.error.HTTPError: HTTP Error 401: Anonymous Request Disallowed

**Comment by ecederstrand** [comment] 2019-01-31 15:11
I have no idea which package you're using there, but I would suggest to ask for help in the issue tracker for that package instead.

**Comment by sunilsunderrajdev** [comment] 2019-01-31 15:39
Thanks

**Comment by ecederstrand** [comment] 2019-02-05 07:00
I researched a bit, and it's supposedly possible to get DL members by using the ExpandDL service.

Somebody dumped a patch to add this service to exchangelib at https://github.com/ecederstrand/exchangelib/issues/505#issuecomment-442795760

**Comment by ecederstrand** [comment] 2019-02-06 13:23
Closing as duplicate of #505 which also has a solution.

**Closed by ecederstrand** 2019-02-06 13:23 UTC
