### ISSUE TITLE
EWSDateTime to datetime (strftime)

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#462] opened 2018-08-17 14:19 UTC
Hi, I'm using your library to work with my exchange calendar events.
I love the from_datetime() function. I have not found any to_datetime() function
though. That would make a lot of things much easier. Maybe one could use that
like this: `some_ewsdatetime.astimezone(tz).to_datetime()` or
`some_ewsdatetime.astimezone(tz).to_datetime().strftime('%Y-%m-%d')`

**Comment by ecederstrand** [comment] 2018-08-17 16:50
`EWSDateTime` inherits from `datetime.datetime`, so for all practical purposes it already *is* a datetime. Is there anything you want to do that you can only do with a pristine datetime?

**Comment by ecederstrand** [comment] 2018-08-20 08:49
Closing. Feel free to reopen if you have additional issues  :-)

**Closed by ecederstrand** 2018-08-20 08:49 UTC

**Comment by madhwaraj1986** [comment] 2020-10-20 03:24
Nice explanation. Totally with it. Thanks.

**Comment by pbuzulan** [comment] 2021-04-14 11:13
Reopen this issue.
When you want to save the datetime information directly to MySQL you get error.

`    return value.translate(_escape_table)
AttributeError: 'EWSDateTime' object has no attribute 'translate'`

**Comment by ecederstrand** [comment] 2021-04-14 11:40
@pbuzulan I need some more context here. Which MySQL library is this? And can you provide a full example? I can't reproduce wit the code you posted alone.

**Comment by pbuzulan** [comment] 2021-04-15 05:52
> @pbuzulan I need some more context here. Which MySQL library is this? And can you provide a full example? I can't reproduce wit the code you posted alone.
> 
> [datetime.datetime](https://docs.python.org/3/library/datetime.html) does not have a `translate()` method so I suspect the issue is with your own code, not exchangelib.

@ecederstrand 
`    def add(self, received_datetime: datetime, subject: str, email_hash: str):
        return self.insert({
            'received_datetime': received_datetime,
            'subject': subject,
            'email_hash': email_hash,
            'create_time': datetime.now()
        })`

If received_datetime is datetime, pymysql library convert it.

This is the traceback:


`Traceback (most recent call last):
  File "/Documents/work/workspace/core/service/Emails.py", line 69, in sync
    email_id = EmailDao(mysql).add(received_datetime=mail.received_date, subject=mail.subject,
  File "/Documents/work/workspace/core/dao/lf_email_dao.py", line 42, in add
    return self.insert({
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/dbs/basedao.py", line 11, in insert
    return self.con.insert(self.table, param,insert_id=insert_id)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/dbs/mysqlwrap.py", line 27, in insert
    return super(MysqlWrap, self).insert(table, record, self._inesrt_id if insert_id else None, insert_id)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/dbs/basedbwrap.py", line 98, in insert
    return self.execute(sql, tuple(record.values()), cb)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/dbs/basedbwrap.py", line 92, in execute
    cursor.execute(sql, args and tuple(args))
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/dbutils/steady_db.py", line 598, in tough_method
    result = method(*args, **kwargs)  # try to execute
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 122, in _escape_args
    return tuple(conn.literal(arg) for arg in args)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 122, in <genexpr>
    return tuple(conn.literal(arg) for arg in args)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/Documents/work/workspace/venv/lib/python3.8/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'EWSDateTime' object has no attribute 'translate'`

**Comment by ecederstrand** [comment] 2021-04-15 06:22
This is a bug in pymysql. It only handles precisely `datetime` objects, not subclasses of `datetime`.

The recommendation in pymysql is apparently to convert the value to string before inserting. See e.g. https://github.com/PyMySQL/PyMySQL/issues/499

BTW, the bug is here (using `type()` instead of `isinstance()`): https://github.com/PyMySQL/PyMySQL/blob/6ccbecc1a0dfd04065b081950d2d35b1dac0aaa8/pymysql/converters.py#L13

If you want, you can insert `EWSDateTime` into this dict to define the translation function you want to happen for `EWSDateTime`: https://github.com/PyMySQL/PyMySQL/blob/6ccbecc1a0dfd04065b081950d2d35b1dac0aaa8/pymysql/converters.py#L314
