### ISSUE TITLE
ErrorInvalidPropertySet item:Attachments

### ISSUE THREAD

**Issue by cyberion1985** [ecederstrand/exchangelib#290] opened 2017-11-09 08:46 UTC
I tried to attach log files to an email. The sending the email without attachment works 100%. As soon as I add attachments, I get an error. My code for the sending is as follows 

```
def send_email(account, subject, body, recipients, attachments=None):

    to_recipients = []
    for recipient in recipients:
        to_recipients.append(Mailbox(email_address=recipient))
		
    m = Message(account=account,
                folder=account.sent,
                subject=subject,
                body=body,
                to_recipients=to_recipients)
    
    for attachment_name, attachment_content in attachments or []:
        file = FileAttachment(name=attachment_name, content=attachment_content)
        m.attach(file)

    m.send_and_save()
```

```
attachments = []
with open('C:\myfile1.log', 'rb') as f:
    content = f.read()
attachments.append(('myfile1.log', content))
f.close()

with open('C:\myfile2.log', 'rb') as f:
    content = f.read()
attachments.append(('myfile2.log', content))
f.close()

send_email(account, 'test', msg, ['test@email.com], attachments=attachments)
```

The error message I am getting is as follows 

>   File "C:\ProgramData\Anaconda2\lib\site-packages\exchangelib\services.py", line 256, in _get_element_container
    self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)

>   File "C:\ProgramData\Anaconda2\lib\site-packages\exchangelib\services.py", line 273, in _raise_errors
    raise vars(errors)[code](text)

>   ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="item:Attachments" />)

I also tried searching for similar posts about attaching files but it always gives the same error.
I also updated the program (using the latest version from here).
I can download an attachment from an email with a specific subject without problem.

@ecederstrand , pls let me know what I am doing wrong

**Comment by ecederstrand** [comment] 2017-11-09 08:57
Are You connecting to an Exchange 2007 server? In that case, this is a duplicate of https://github.com/ecederstrand/exchangelib/issues/150. I believe the workaround there is to save the message without sending, then add attachments, and finally send the message.

**Comment by cyberion1985** [comment] 2017-11-09 08:58
I see, thanks a lot ! Will check it out !

**Comment by cyberion1985** [comment] 2017-11-09 09:05
ok just to clarify, do you mean to add the attachments manually or using python to add them after the message has been saved ?

**Comment by ecederstrand** [comment] 2017-11-09 09:06
No, I meant attach using exchangelib. Something like:

```python
m = Message(...)
m.save()
for a in attachments:
    m.attach(a)
m.send()
```

**Comment by cyberion1985** [comment] 2017-11-09 09:15
Thanks a lot, that worked perfectly !

```
'''def send_email(account, subject, body, recipients, attachments=None):

    to_recipients = []
    for recipient in recipients:
        to_recipients.append(Mailbox(email_address=recipient))
		
    m = Message(account=account,
                folder=account.sent,
                subject=subject,
                body=body,
                to_recipients=to_recipients)
    
    m.save()

    for attachment_name, attachment_content in attachments or []:
        file = FileAttachment(name=attachment_name, content=attachment_content)
        m.attach(file)

    m.send()'''
```

**Comment by ecederstrand** [comment] 2017-11-09 09:29
Great!

A small tip for GitHub markdown. Write 3 backticks and 'python', and then your code, to have it syntax highlighted as python code. Like this:

````
```python
for i in range(10):
    print('Hello GitHub')
```
````
which renders as:
```python
for i in range(10):
    print('Hello GitHub')
```

**Closed** 2017-11-16 09:11 UTC
Labels: duplicate
