### ISSUE TITLE
public folder access

### ISSUE THREAD

**Issue by illyax** [ecederstrand/exchangelib#444] opened 2018-07-18 13:13 UTC
Hey, is it possible to get contacts from public folder through exchangelib? 
I am able to get personal contacts but nothing from public folder.

**Comment by ecederstrand** [comment] 2018-07-31 07:14
I'm not very familiar with how contacts work in Exchange. You can access the GAL if you have see it in your `account.root.tree()` listing, if that's what you meant.

**Comment by ecederstrand** [comment] 2018-08-03 08:39
Closing as duplicate of #396

**Closed by ecederstrand** 2018-08-03 08:39 UTC
