### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sharon8811** [ecederstrand/exchangelib#134] opened 2017-05-14 08:14 UTC
i noticed a memory leak problem the code i am running is:
```
for email in account.inbox.all().iterator():
    if not isinstance(email, Message): continue
    i += 1
    if i > 150: break
    print email.subject

email = None
```

and then when i get all objects from python garbage collector all the emails still in memory
this is my garbage collector test:
```
import gc
objs = gc.get_objects()
for o in objs: 
   if 'HTMLBody' in str(type(o)):
      print o
```

i get 146 email body that is still in memory
any idea how can i remove the references to them so they will be garbage collected?

**Comment by ecederstrand** [comment] 2017-05-15 07:24
Thanks for the report! This is definitely not intended.

Do you have any idea where the references are located? I can take a stab at this myself but am bogged down by contract work and cannot promise when I'll have time.

**Comment by udiNur** [comment] 2017-12-25 15:01
I was trying to finding the reference by my self... but without any succeded.
it no passable to download large folder. because of the ram that in use by the script grow with all of the data that you download...
heaven that I don't save the items in the script (not in list, dict ext...) the only use that I'm doing is to save the mime_content. I don't put him in any var.

the strangest things that I'm found is even when you call again to the func that download, that make the ram grow even more...

`
def foron(gen):
    [x for x in gen]
input() #chek youer mem here..
foron(ac.inbox.all())
input() #and here
foron(ac.inbox.all())
#and here
`

**Comment by ecederstrand** [comment] 2018-08-26 13:44
Using `pympler`, I did a quick test by creating, listing and deleting 1000 messages, using the latest code:

```python
from operator import itemgetter
from pympler import tracker
from exchangelib import Account, Credentials, Message

mem = tracker.SummaryTracker()

print('\nBefore Account creation')
for n, c, s in sorted(mem.create_summary(), reverse=True, key=itemgetter(2))[:10]:
    print(n, c, s)

email = 'john@example.com'
password = 'secret'
a = Account(email, credentials=Credentials(email, password), autodiscover=True)

print('\nAfter Account creation')
for n, c, s in sorted(mem.create_summary(), reverse=True, key=itemgetter(2))[:10]:
    print(n, c, s)

a.bulk_create(a.inbox, [Message(subject='XXX', body='X'*10000) for _ in range(1000)])

print('\nAfter creating items')
for n, c, s in sorted(mem.create_summary(), reverse=True, key=itemgetter(2))[:10]:
    print(n, c, s)

for m in a.inbox.filter(subject='XXX'):
    pass

print('\nAfter iteration')
for n, c, s in sorted(mem.create_summary(), reverse=True, key=itemgetter(2))[:10]:
    print(n, c, s)

a.inbox.filter(subject='XXX').delete()

print('\nAfter deletion')
for n, c, s in sorted(mem.create_summary(), reverse=True, key=itemgetter(2))[:10]:
    print(n, c, s)
```

This prints:
```
Before Account creation
<class 'str 33516 3715195
<class 'dict 4546 2390848
<class 'type 1880 1994592
<class 'code 8849 1277664
<class 'list 6267 652384
<class 'tuple 6959 482336
<class 'set 420 298880
<class '_io.BufferedWriter 2 262496
<class 'weakref 2864 229120
<class 'int 5482 166608

After Account creation
<class 'str 34786 3831963
<class 'dict 5056 2722864
<class 'type 2077 2210304
<class 'code 9475 1367904
<class 'list 6381 673312
<class 'tuple 7497 518736
<class 'set 583 343584
<class 'weakref 3477 278160
<class '_io.BufferedWriter 2 262496
<class 'builtin_function_or_method 2888 207936

After creating items
<class 'str 34849 3836790
<class 'dict 5137 2740360
<class 'type 2077 2212584
<class 'code 9475 1367904
<class 'list 6440 690512
<class 'tuple 7497 518736
<class 'set 593 345824
<class 'weakref 3490 279200
<class '_io.BufferedWriter 2 262496
<class 'builtin_function_or_method 2906 209232

After iteration
<class 'str 34895 3851665
<class 'dict 5150 2746568
<class 'type 2077 2213120
<class 'code 9475 1367904
<class 'list 6487 694384
<class 'tuple 7497 518736
<class 'set 598 346944
<class 'weakref 3495 279600
<class '_io.BufferedWriter 2 262496
<class 'builtin_function_or_method 2906 209232

After deletion
<class 'str 34897 3851930
<class 'dict 5150 2746568
<class 'type 2077 2213120
<class 'code 9475 1367904
<class 'list 6489 694576
<class 'tuple 7497 518736
<class 'set 598 346944
<class 'weakref 3495 279600
<class '_io.BufferedWriter 2 262496
<class 'builtin_function_or_method 2906 209232
```

Closing, as I don't see anything suspicious here. If you still have memory leak issues, please post example code that reproduces the problem.

**Closed by ecederstrand** 2018-08-26 13:44 UTC
