### ISSUE TITLE
Cannot access calendar due to "Access denied"

### ISSUE THREAD

**Issue by agronholm** [ecederstrand/exchangelib#668] opened 2019-11-07 10:29 UTC
Exchangelib v1.12.3 broke our Exchange integration and it's still broken in v2.1.0.
The difference in the requests is that newer than v1.12.2 include the `PermissionSet` field in the query when trying to access the calendar. This causes the request to fail with `exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again., Wrapped mapi call failed`.

This snippet (with the right credentials filled in) reproduces the issue:

```python
import logging

from exchangelib import Configuration, Account, BASIC, Credentials

logging.basicConfig(level=logging.DEBUG)


credentials = Credentials('redacted', 'redacted')
config = Configuration(credentials=credentials, server= 'outlook.office365.com', auth_type=BASIC)
account = Account('redacted', credentials=config.credentials, config=config)
calendar = account.calendar
```
Is there any way we can get around this?

**Comment by ecederstrand** [comment] 2019-11-07 11:02
This looks like a duplicate of https://github.com/ecederstrand/exchangelib/issues/610. Please post your Exchange version in that issue, so we can get a better understanding of which Exchange versions don't support this field.

**Comment by agronholm** [comment] 2019-11-07 12:19
I figured it out. I had my version pinned to v2.0.1 but I really just needed to upgrade to v2.1.0 which works again. Sorry for the trouble.

**Comment by agronholm** [comment] 2019-11-07 12:22
Heh, I didn't realize v2.1.0 was fresh out of the oven, that explains everything :)

**Comment by ecederstrand** [comment] 2019-11-07 14:45
Yeah, sorry about that. I forgot the PermissionSet fix was never released.

**Closed by ecederstrand** 2019-11-07 14:45 UTC
