### ISSUE TITLE
Saving entire email with attachments as .msg file

### ISSUE THREAD

**Issue by bakarep** [ecederstrand/exchangelib#671] opened 2019-11-12 05:38 UTC
I wanted to know if there is functionality to save email as .msg file to local filesystem. Could not find anything in api or on web. Please guide to the page if functionality already exists.

**Comment by ecederstrand** [comment] 2019-11-12 06:30
Duplicate of https://github.com/ecederstrand/exchangelib/issues/475

**Closed by ecederstrand** 2019-11-12 06:30 UTC

**Comment by MarcAllain** [comment] 2023-11-10 11:01
Hi everybody,
I do not agree with the "duplicate" action on this issue.
The [#475](https://github.com/ecederstrand/exchangelib/issues/475) deals with generating "*.eml" file, the question was about generatin "*.msg" files ... ?

**Comment by ecederstrand** [comment] 2023-11-10 11:22
There's no standard for neither .msg nor .eml files. Tools can dump whatever they like in a file and give it either suffix. But usually it will be the MIME content in both cases. Hence the duplicate.
