### ISSUE TITLE
Empty compressed zipped file in attachment

### ISSUE THREAD

**Issue by Abhi-1504** [ecederstrand/exchangelib#803] opened 2020-09-04 03:58 UTC
Hi @ecederstrand ,

While trying to send compressed file as an attachment, I am only receiving the compressed shell folder but not files inside the compressed folder. I have checked the server and the compressed folder in it do consist of files.  I am not getting any error. PFA the function and the calling part used in the program. Kindly let me know if you need more information.

**Calling part:**
```
    sh.make_archive(base_dir = 'unprocessed', format='zip', base_name = 'unprocessed')

    # sending teh compressed zip file of unprocessed invoices in mail
    logger.info('Sending mail comprising of unprocessd invoices in attachment')
    send_mails(account = account,
               subject = 'Unprocessed Invoices',
               message = "PFA Unprocessed Invoices for yesterday's manual run",
               excel_file = folder+'.zip',
               to_emails=to_email_ids)
```

**Function:**
```
def send_mails(account, message, excel_file, subject, to_emails):
    """
    Send generated excel report in an email to the recipents
    Parameters:
        account (object): Account object of master mailbox
        excel_file (str): path to the generated excel file report
        to_emails (list): list of recipents' email
    """
    # Creating list of Mailbox objects from the list of recipents' email and sending email from master mailbox
    try:
        to_recipients =[Mailbox(email_address=mail) for mail in to_emails]
        #Create message
        create_message = Message(account=account,
                             folder = account.sent,
                             subject=subject,
                             body=message,
                             to_recipients=to_recipients)
        attachments = []
        if excel_file != None:
            print(excel_file)
            with open(excel_file, 'rb') as f:
                content = f.read()
            index = excel_file.rfind('/')
            filename = excel_file[index+1:]
            attachments.append((filename,content))

            #attach files
            for attachment_name, attachment_content in attachments:
                print(attachment_content)
                file = FileAttachment(name=attachment_name, content=attachment_content)
                print(file)
                create_message.attach(file)
        create_message.send_and_save()
```

**Comment by ecederstrand** [comment] 2020-09-04 05:22
When you receive the email, does the attachment size match the size of the file you are sending?

You may have more luck if you inform the server of the content type of your file. See https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/attachments.py#L38 and https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/fileattachment

**Comment by Abhi-1504** [comment] 2020-09-04 05:50
@ecederstrand yes the attachment size looks the same as the file on server. I believe I need to pass _content type_ param in the FileAttachment function ? What should be the value of the parameter?

**Comment by ecederstrand** [comment] 2020-09-04 05:54
Here's a list of common tontent type values for different file types: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

**Comment by Abhi-1504** [comment] 2020-09-04 06:09
@ecederstrand : I tried passing the below content type value but getting the same result. Am I doing anything incorrectly ?

**Function call**
```
send_mails(account = account,
               subject = 'Unprocessed Invoices',
               message = "PFA Unprocessed Invoices for yesterday's manual run",
               excel_file = folder+'.zip',
               to_emails=to_email_ids,
               content_type = 'application/zip')
```

**Function body**
```
def send_mails(account, message, excel_file, subject, to_emails, content_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'):
.
.
.
    for attachment_name, attachment_content in attachments:
                print(attachment_content)
                file = FileAttachment(name=attachment_name, content=attachment_content, content_type = content_type)
                print(file)
                create_message.attach(file)
        create_message.send_and_save()
```

**Comment by ecederstrand** [comment] 2020-09-04 07:29
I haven't worked with zip file attachments before, so you'll have to experiment some more.

Try creating an email with a zip file attachment with a different Exchange client, e.g. Outlook, and check that this message works as intended. Then use exchangelib to inspect that message to see how the attachment fields (and attachment-related fields on the message object) are set. Finally, set the parameters on the new message accordingly and send it.

**Comment by ecederstrand** [comment] 2020-09-14 11:17
Did you get anywhere with this issue?

**Comment by ecederstrand** [comment] 2020-10-08 07:47
Closing due to timeout. Feel free to reopen if you have additional information on this issue.

**Closed by ecederstrand** 2020-10-08 07:47 UTC
