### ISSUE TITLE
Reverse Ordering of datetime_received not working

### ISSUE THREAD

**Issue by lsabi** [ecederstrand/exchangelib#853] opened 2021-01-26 17:48 UTC
OS: Ubuntu server 21.04
Python: 3.8.6
Exchangelib: 3.3.2
Exchange: 2016 on-premise

I'm querying the exchange server via the library and would like to display the _n_ most recent emails, as in the code below

```
q = Q(author=query)
res = emails.filter(q).order_by("datetime_received").values("id", "datetime_received", "subject", "body")
print(res[0]["datetime_received"]
print(res[-1]["datetime_received"]
```

The above code, then returns the following:
```
2011-02-24 07:36:08+00:00
2020-07-30 07:39:18+00:00
```
So, I tried with reversing the sorting, by adding a minus before the `"datetime_received"` in the `order_by` function and gives me the same result as above.

I've checked and the (basically) same code works when sorting and reversing order with `subject` and `-subject`.

I'll try to dig into the code in order to find the root of the cause, though my knowledge about the server is limited.

**Comment by ecederstrand** [comment] 2021-01-26 20:39
Thanks for the report! There's some optimization going on when you do `res[0]` and `res[`-1]`. They end up being two distinct queries because we don't need to fetch all items in between. This happens in https://github.com/ecederstrand/exchangelib/blob/db3d2a8dbd1ef0551ca431d8138e036698c27579/exchangelib/queryset.py#L306

Do you get the same results if you do `res = list(res)` before accessing `res[0]` and `res[`-1]`?

**Comment by lsabi** [comment] 2021-01-26 21:14
Yes, I do get the same result, because I forget to write that in the code (though I was using it with `[0:x]` before investigating the problem and wasn't working).

**Comment by ecederstrand** [comment] 2021-01-27 13:19
I cannot reproduce this:

```python
res = account.inbox.all().values('datetime_received').order_by('datetime_received')
print(res[0]['datetime_received'])
print(res[-1]['datetime_received'])
# 2021-01-18 23:05:39+00:00
# 2021-01-18 23:05:41+00:00

res = account.inbox.all().values('datetime_received').order_by('-datetime_received')
print(res[0]['datetime_received'])
print(res[-1]['datetime_received'])
# 2021-01-18 23:05:41+00:00
# 2021-01-18 23:05:39+00:00
```

**Comment by lsabi** [comment] 2021-01-27 14:46
When I use the `all()` works, but when I use filter it does not work and returns only a partial result.

`emails.all().filter(sender="email@domain.domain").values("datetime_received").order_by("-datetime_received")[0]["datetime_received"]`

The same result without `all()`.

Could it be due to the lazy loader of the queryset that only the first `n` emails are retrieved, and sorted only after it?

In my case I only need to fetch the first n emails sorted in descending datetime_received order sent from a certain email address. If someone wants to further view emails, then I'll do the same query but offsetting the res (i.e. `res[offset:offset + limit]`)

**Comment by ecederstrand** [comment] 2021-02-12 21:52
I still cannot reproduce this, with a filter and a small page size that definitely does not fit the result. Here's what I tried:

```python
res = a.inbox.filter(subject__contains='something').values('datetime_received').order_by('datetime_received')
res.page_size = 2
print(res[0]['datetime_received'])
print(res[-1]['datetime_received'])
print(res.count())
# 2021-02-11 11:15:45+00:00
# 2021-02-11 11:28:16+00:00
# 35

res = a.inbox.filter(subject__contains='something').values('datetime_received').order_by('-datetime_received')
res.page_size = 2
print(res[0]['datetime_received'])
print(res[-1]['datetime_received'])
print(res.count())
# 2021-02-11 11:28:16+00:00
# 2021-02-11 11:15:45+00:00
# 35
```

**Comment by ecederstrand** [comment] 2021-02-16 09:57
Closing since I can't reproduce, but feel free to reopen if you find out what's going on.

**Closed by ecederstrand** 2021-02-16 09:57 UTC

**Comment by lsabi** [comment] 2021-02-16 16:34
Sorry for the late reply, but these days I've been super busy.

Anyways, yes it works with the suggested code of yours. Below the results.

```
2020-09-01 07:05:33+00:00
2021-02-16 07:53:38+00:00
484
2021-02-16 07:53:38+00:00
2020-09-01 07:05:33+00:00
484
```

The only problem is, I need to search in subfolders as well, since this is an archive, divided by year. In this case, I'm finding emails from far before the date I get as a result. Is there any possibility to extend the search to include subfolders as well?

**Comment by ecederstrand** [comment] 2021-02-16 18:36
Filters work on subfolder searches as well:

```python
a.inbox.children.filter(subject='foo')
a.inbox.walk().filter(subject='foo')
a.inbox.glob('foo*').filter(subject='foo')
```

See https://ecederstrand.github.io/exchangelib/#searching

**Comment by lsabi** [comment] 2021-02-16 21:50
I tried with the `glob` for filtering on the subfolders as well and here's the result:

```
2011-02-24 07:35:54+00:00
2011-12-15 07:34:56+00:00
60
2011-12-15 07:34:56+00:00
2011-02-24 07:35:54+00:00
60
```

It is odd since with my email (which did not existing since a couple of years ago), it takes only the most recent ones and with this other email (which has not been used since last year), it takes the oldest emails.

I've been using the following code

```
emails = my_account.public_folders_root.glob("My Folder*/**")
res = emails.filter(sender="xxxx@xxxx.xxx").order_by("datetime_sent").values("-datetime_sent")
```

My folders are structured as follows

```
Public folder
    - My folder (with emails at the same level of folders)
          - Folder1
          - Folder2
```
