### ISSUE TITLE
Understanding filter(sender__contains)

### ISSUE THREAD

**Issue by aylbert** [ecederstrand/exchangelib#854] opened 2021-01-26 22:59 UTC
I am having difficulties understanding how to properly use the filter where I am looking for a partial e-mail address - such as all e-mails from the domain  "bar.com"   that contains  "TEST" in the subject line.

This will produce results if I am explicit with the exact sender:
```
for item in account.inbox.filter(sender__icontains='foo@bar.com', subject__icontains='TEST'):
    print(item.sender)
```

Whereas this will not produce any results:
```
for item in account.inbox.filter(sender__icontains='bar.com', subject__icontains='TEST'):
    print(item.sender)
```

When I examine the query set this seems to make sense to me: 
`QuerySet(q=sender icontains 'bar.com' AND subject icontains 'TEST', folders=[Inbox (Inbox)])`

If I were to run it with just the sender__icontains  but without the subject, I get results.   So I am not sure why combining them does not give me the desired results.

Are you able to assist me or point me in the right direction?
Thanks!
-Al

**Comment by ecederstrand** [comment] 2021-01-27 09:40
This came up recently in a SO question: https://stackoverflow.com/questions/65695387/how-to-filter-by-email-address-domain-with-exchangelib

It seems that EWS simply does not support `contains` for the `sender` field.

**Comment by aylbert** [comment] 2021-01-27 15:59
I am able to use `contain` with the `sender` field - but it is not producing the desired results.

If I use `contain` with the `sender` field by itself, it appears to be checking all attributes of `sender` and I get results using 'bar.com'

If I add another criteria, such as `subject`, the `contain` for sender no longer produces results for 'bar.com'.   When I change the `contains` for `sender` to 'foo@bar.com' - I get results.   This would omit 'x@bar.com'.  

Ultimately I am trying to filter the inbox for all e-mails from a specified domain that contains a subject keyword.

**Comment by ecederstrand** [comment] 2021-02-12 21:44
Hmm. I cannot reproduce this on my test server. This works just fine and uses both filters:

```python
for item in a.inbox.filter(sender__icontains='example.com', subject__icontains='something'):
    print(item.sender, item.subject)
```

**Comment by ecederstrand** [comment] 2021-02-16 09:56
You can enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) to see the exact XML of the query your queryset is sending, and the entire interaction with the server. That may give you a hint about what is going on.

Closing, but feel free to reopen if you find out what's wrong on your side.

**Closed by ecederstrand** 2021-02-16 09:56 UTC
