### ISSUE TITLE
Need help with key error, maybe SLL error?

### ISSUE THREAD

**Issue by mellexpro** [ecederstrand/exchangelib#1034] opened 2022-01-12 17:05 UTC
**Describe the bug**
Errors occur when invoking Account.inbox (or any other) method.

- KeyError: 'inbox'
- ERROR:exchangelib.util:TransportError: HTTPSConnectionPool(host='mail.domain.co.za', port=443): Max retries exceeded with url: /ows/EWS/Exchange.asmx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**To Reproduce**
Used the same code as the readme example, except that a separate config was provided as auto discovery did not work.

**Expected behavior**
Expecting a collection of some sorts of my inbox.

**Log output**
```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://mail.domain.co.za/ows/EWS/Exchange.asmx', Credentials('domain-name\\username', '********'))'
DEBUG:exchangelib.account:Added account: username@domain.co.za
DEBUG:exchangelib.services.common:Processing chunk 1 containing 1 items
DEBUG:exchangelib.services.common:Calling service GetFolder
DEBUG:exchangelib.services.common:Trying API version Exchange2010_SP2
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Increasing session pool size from 0 to 1
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Created session 26842
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Waiting for session
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Got session 26842
DEBUG:exchangelib.util:Session 26842 thread 24724: retry 0 timeout 120 POST'ing to https://mail.domain.co.za/ows/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mail.domain.co.za:443
ERROR:exchangelib.util:TransportError: HTTPSConnectionPool(host='mail.domain.co.za', port=443): Max retries exceeded with url: /ows/EWS/Exchange.asmx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
Retry: 0
Waited: 10
Timeout: 120
Session: 26842
Thread: 24724
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x000002097E39DB70>
URL: https://mail.domain.co.za/ows/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x000002097E39DAB0>
Allow redirects: False
Streaming: False
Response time: 0.3440000000409782
Status code: 503
Request headers: {'X-AnchorMailbox': 'username@domain.co.za'}
Response headers: {}
Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2"/><t:TimeZoneContext><t:TimeZoneDefinition Id="South Africa Standard Time"/></t:TimeZoneContext></s:Header><s:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount"/><t:FieldURI FieldURI="folder:DisplayName"/><t:FieldURI FieldURI="folder:EffectiveRights"/><t:FieldURI FieldURI="folder:FolderClass"/><t:FieldURI FieldURI="folder:FolderId"/><t:FieldURI FieldURI="folder:ParentFolderId"/><t:FieldURI FieldURI="folder:TotalCount"/><t:FieldURI FieldURI="folder:UnreadCount"/></t:AdditionalProperties></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>username@domain.co.za</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></s:Body></s:Envelope>'
Response XML: b''
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Retiring session 26842
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Created session 25904
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Releasing session 25904
WARNING:exchangelib.services.common:Account username@domain.co.za: Exception in _get_elements: Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'
```

**Additional context**
Python 3.10
Exchangelib: latest

**Comment by ecederstrand** [comment] 2022-01-12 17:14
The `KeyError` is misleading - it's an artifact of the way the `cached_property` package works. Th actal error is the `SSLError`, as you posted.

The reason for the exception is that the SSL certificate for `mail.domain.co.za` cannot be validated on your machine. This is outside the control of exchangelib.

**Comment by mellexpro** [comment] 2022-01-12 17:17
Ok, that's a good start.

So would this mean that my certificate is invalid?
Is there a way to accept the certificate somehow?

Thank you

**Comment by mellexpro** [comment] 2022-01-12 17:51
So I just tried a couple of things:

- I logged onto the companies VPN and it seemed to work but with a different error now being returned.
- I tried logging into the WEB client and it worked in all browsers.
- I logged off from the VPN and the error returned and the web client stopped working.

So it seems I need to use the VPN to make use of the library, which I can deal with.

If you ae interested in the new error here it is:

```
DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://mail.domain.co.za/ows/EWS/Exchange.asmx', Credentials('domain-pe\\username', '********'))'
DEBUG:exchangelib.account:Added account: username@domain.co.za
DEBUG:exchangelib.services.common:Processing chunk 1 containing 1 items
DEBUG:exchangelib.services.common:Calling service GetFolder
DEBUG:exchangelib.services.common:Trying API version Exchange2010_SP2
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Increasing session pool size from 0 to 1
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Created session 24246
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Waiting for session
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Got session 24246
DEBUG:exchangelib.util:Session 24246 thread 23000: retry 0 timeout 120 POST'ing to https://mail.domain.co.za/ows/EWS/Exchange.asmx after 10s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mail.domain.co.za:443
DEBUG:urllib3.connectionpool:https://mail.domain.co.za:443 "POST /ows/EWS/Exchange.asmx HTTP/1.1" 404 1245
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 24246
Thread: 23000
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000019A40F05DB0>
URL: https://mail.domain.co.za/ows/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000019A40F05CF0>
Allow redirects: False
Streaming: False
Response time: 0.14100000000325963
Status code: 404
Request headers: {'User-Agent': 'exchangelib/4.6.2 (python-requests/2.27.1)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': 'username@domain.co.za', 'Content-Length': '1171'}
Response headers: {'Content-Type': 'text/html', 'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 12 Jan 2022 17:39:05 GMT', 'Content-Length': '1245'}
DEBUG:exchangelib.util.xml:Request XML: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="South Africa Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:GetFolder>
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:ChildFolderCount"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:EffectiveRights"/>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:FolderId"/>
          <t:FieldURI FieldURI="folder:ParentFolderId"/>
          <t:FieldURI FieldURI="folder:TotalCount"/>
          <t:FieldURI FieldURI="folder:UnreadCount"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:FolderIds>
        <t:DistinguishedFolderId Id="root">
          <t:Mailbox>
            <t:EmailAddress>username@domain.co.za</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:FolderIds>
    </m:GetFolder>
  </s:Body>
</s:Envelope>
Response XML: b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 
- File or directory not found.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'
DEBUG:exchangelib.protocol:No retry: wrong status code 404
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Retiring session 24246
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Created session 25288
DEBUG:exchangelib.protocol:Server mail.domain.co.za: Releasing session 25288
ERROR:exchangelib.util:MalformedResponseError: Unknown failure in response. Code: 404 headers: {'Content-Type': 'text/html', 'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 12 Jan 2022 17:39:05 GMT', 'Content-Length': '1245'} content: <!DOCTYPE html 
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

Retry: 0
Waited: 10
Timeout: 120
Session: 24246
Thread: 23000
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000019A40F05DB0>
URL: https://mail.domain.co.za/ows/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x0000019A40F05CF0>
Allow redirects: False
Streaming: False
Response time: 0.14100000000325963
Status code: 404
Request headers: {'User-Agent': 'exchangelib/4.6.2 (python-requests/2.27.1)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': 'username@domain.co.za', 'Content-Length': '1171'} 
Response headers: {'Content-Type': 'text/html', 'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 12 Jan 2022 17:39:05 GMT', 'Content-Length': '1245'}
Request XML: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2010_SP2"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="South Africa Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:GetFolder>
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:ChildFolderCount"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:EffectiveRights"/>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:FolderId"/>
          <t:FieldURI FieldURI="folder:ParentFolderId"/>
          <t:FieldURI FieldURI="folder:TotalCount"/>
          <t:FieldURI FieldURI="folder:UnreadCount"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:FolderIds>
        <t:DistinguishedFolderId Id="root">
          <t:Mailbox>
            <t:EmailAddress>username@domain.co.za</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:FolderIds>
    </m:GetFolder>
  </s:Body>
</s:Envelope>
Response XML: b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 
- File or directory not found.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'
WARNING:exchangelib.services.common:Account username@domain.co.za: Exception in _get_elements: Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 226, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 190, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 312, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 266, in _get_response
    r, session = post_ratelimited(
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\util.py", line 877, in post_ratelimited
    protocol.retry_policy.raise_response_errors(r)  # Always raises an exception
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\protocol.py", line 694, in raise_response_errors
    raise MalformedResponseError(
exchangelib.errors.MalformedResponseError: Unknown failure in response. Code: 404 headers: {'Content-Type': 'text/html', 'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 12 Jan 2022 17:39:05 GMT', 'Content-Length': '1245'} content: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>


Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\PythonCode\try-exchangewebservices\main.py", line 38, in <module>
    main()
  File "c:\PythonCode\try-exchangewebservices\main.py", line 32, in main
    print(account.inbox())
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\account.py", line 217, in inbox
    return self.root.get_default_folder(Inbox)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\account.py", line 281, in root
    return Root.get_distinguished(account=self)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\folders\roots.py", line 109, in get_distinguished
    return cls.resolve(
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\folders\base.py", line 459, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\folders\collections.py", line 326, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\folders\collections.py", line 391, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\get_folder.py", line 40, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 206, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 226, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 190, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 312, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\services\common.py", line 266, in _get_response
    r, session = post_ratelimited(
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\util.py", line 877, in post_ratelimited
    protocol.retry_policy.raise_response_errors(r)  # Always raises an exception
  File "C:\PythonCode\try-exchangewebservices\try-ews\lib\site-packages\exchangelib\protocol.py", line 694, in raise_response_errors
    raise MalformedResponseError(
exchangelib.errors.MalformedResponseError: Unknown failure in response. Code: 404 headers: {'Content-Type': 'text/html', 'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 12 Jan 2022 17:39:05 GMT', 'Content-Length': '1245'} content: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

DEBUG:exchangelib.protocol:Server mail.domain.co.za: Closing sessions
```

**Comment by mellexpro** [comment] 2022-01-13 09:08
Hey @ecederstrand, I am not sure how I can use your library effectively if I am getting the error such as the one above, this is not something I understand and the error messages are very cryptic. Could you be so kind as to point me in the right direction?

**Comment by ecederstrand** [comment] 2022-01-13 10:19
According to the logs you posted, it looks like the server you are talking to is not an Exchange server, or the URL you specified does not point to the EWS service. I'd suggest aither using autodiscover to get the correct server, og asking your Exchange admins which URL to use.

**Comment by bschnei** [comment] 2022-01-14 19:05
I am getting similar errors when calling `account.inbox` and they do not appear in version 4.6.2 so this does seem like a regression. Here is the traceback for me:

```
Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 196, in get_session
    session = self._session_pool.get(block=False)
  File "C:\Program Files\Python38\lib\queue.py", line 167, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 246, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 208, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 332, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 282, in _get_response
    session = self.protocol.get_session()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 200, in get_session
    self.increase_poolsize()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 170, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 271, in create_session
    if self.auth_type == NTLM and self.credentials.type == self.credentials.EMAIL:
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 81, in auth_type
    self.config.auth_type = self.get_auth_type()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 107, in get_auth_type
    auth_type, api_version_hint = get_service_authtype(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\transport.py", line 137, in get_service_authtype
    _back_off_if_needed(retry_policy.back_off_until)
AttributeError: 'NoneType' object has no attribute 'back_off_until'
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'inbox'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'root'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 196, in get_session
    session = self._session_pool.get(block=False)
  File "C:\Program Files\Python38\lib\queue.py", line 167, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\account.py", line 221, in inbox
    return self.root.get_default_folder(Inbox)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\cached_property.py", line 74, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\account.py", line 285, in root
    return Root.get_distinguished(account=self)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\roots.py", line 109, in get_distinguished
    return cls.resolve(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\base.py", line 430, in resolve
    folders = list(FolderCollection(account=account, folders=[folder]).resolve())
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\collections.py", line 313, in resolve
    yield from self.__class__(account=self.account, folders=resolveable_folders).get_folders(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\folders\collections.py", line 376, in get_folders
    yield from GetFolder(account=self.account).call(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\get_folder.py", line 39, in _elems_to_objs
    for folder, elem in zip(self.folders, elems):
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 226, in _chunked_get_elements
    yield from self._get_elements(payload=payload_func(chunk, **kwargs))
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 246, in _get_elements
    yield from self._response_generator(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 208, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 332, in _get_response_xml
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\services\common.py", line 282, in _get_response
    session = self.protocol.get_session()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 200, in get_session
    self.increase_poolsize()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 170, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 271, in create_session
    if self.auth_type == NTLM and self.credentials.type == self.credentials.EMAIL:
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 81, in auth_type
    self.config.auth_type = self.get_auth_type()
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\protocol.py", line 107, in get_auth_type
    auth_type, api_version_hint = get_service_authtype(
  File "C:\Users\bschneid\repos\pmxls\venv\lib\site-packages\exchangelib\transport.py", line 137, in get_service_authtype
    _back_off_if_needed(retry_policy.back_off_until)
AttributeError: 'NoneType' object has no attribute 'back_off_until'
```

**Comment by ecederstrand** [comment] 2022-01-14 21:25
@bschnei That's a different problem. Can you please open a new issue for this?

**Comment by ecederstrand** [comment] 2022-01-18 14:04
I'm closing this issue since I don't think there's anything to be fixed in exchangelib. Feel free to reopen if you disagree.

**Closed by ecederstrand** 2022-01-18 14:04 UTC
