### ISSUE TITLE
Max attachments size

### ISSUE THREAD

**Issue by groshevpavel** [ecederstrand/exchangelib#590] opened 2019-05-17 11:49 UTC
hi Erik
i have problem with send attachment of size about 54Mb..
exchangelib throws "Unknown failure" exception (text below)
but i can send that large file via Outlook... and i can send file about 30Mb via exchangelib

thank you!

start part of exception text:
Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 26836
Thread: 104
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x0000022439E07908>
URL: https://my.url.here/EWS/Exchange.asmx
HTTP adapter: <utils.exchange_wrapper.SSLContextAdapter object at 0x0000022439E073C8>
Allow redirects: False
Response time: 0.7190000000409782
Status code: 507
Request headers: {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Cookie': 'X-BackEndCookie=S-1-5-21-564074959-1810644771-7473742-7608912=u56Lnp2ejJqByJ7InsjNycnSxsmbnNLLm8jK0p7Lm87SmpnMyM3JnZyeys7PgYHNz87G0s/J0s7Kq87KxcvKxcrI; ClientId=SCSXYCZUOFEJXWBPA; exchangecookie=a033e4219f3646b3843f98da741e789a', 'Content-Length': '76018234'}
Response headers: {'Server': 'Microsoft-IIS/8.5', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'EXCAS-NODE06', 'Date': 'Thu, 16 May 2019 15:49:07 GMT', 'Connection': 'close', 'Content-Length': '0'}

**Comment by ecederstrand** [comment] 2019-05-17 18:56
Your server is returning an HTTP 507 (Insufficient Storage) status code with no additional explanation. This could be due to insufficient disk storage on the server or caused by policy restrictions on the user. I don’t think there’s anything exchangelib can do to fix this.

**Comment by ecederstrand** [comment] 2019-05-20 05:46
Closing. Feel free to reopen if you think there's something we can do to fix the issue :-)

**Closed by ecederstrand** 2019-05-20 05:46 UTC
