### ISSUE TITLE
Sender's Information

### ISSUE THREAD

**Issue by DeepakLabh** [ecederstrand/exchangelib#298] opened 2017-11-20 11:50 UTC
Hi all,

I was wondering if there are any methods to get sender's information (specifically country) via EWS or any other services.

As there is option from Microsoft Outlook account where you can view everyone's infos.

Thanks.

**Comment by ecederstrand** [comment] 2017-11-20 11:52
I think that would require an implementation of https://github.com/ecederstrand/exchangelib/issues/93

It would only work for in-house users, of course.

**Comment by ecederstrand** [comment] 2017-11-23 10:19
Closing as duplicate of #93

**Closed by ecederstrand** 2017-11-23 10:19 UTC
