### ISSUE TITLE
bulk_move fails with impersonation

### ISSUE THREAD

**Issue by vikramarsid** [ecederstrand/exchangelib#304] opened 2017-11-29 12:36 UTC
Hi,

I am trying to bulk move messages between different mailboxes with impersonation access type. During this operation, I get an internal server error.
`{ErrorInternalServerError}An internal server error occurred. The operation failed.`

SOAP Response:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <s:Fault>
            <faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInternalServerError
            </faultcode>
            <faultstring xml:lang="en-US">An internal server error occurred. The operation failed.</faultstring>
            <detail>
                <e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">
                    ErrorInternalServerError
                </e:ResponseCode>
                <e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">An internal server error
                    occurred. The operation failed.
                </e:Message>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```
- Autodiscover is set to true.
- Bulk move works fine with delegation but, fails under impersonation.
@ecederstrand Please let me know if I am doing anything wrong. I would really appreciate any guidance you can provide on how I can troubleshoot this issue?
Thank you!!

**Comment by ecederstrand** [comment] 2017-11-29 13:09
Are you using the latest version of exchangelib? If not, try to update.

`ErrorInternalServerError` may be an intermittent error due to server overload, or it may be caused by malformed XML in the request. You could capture the request XML and post it here.

**Comment by vikramarsid** [comment] 2017-11-29 13:57
Here is the request xml
```
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /><t:ExchangeImpersonation><t:ConnectingSID><t:PrimarySmtpAddress>test@dev.com</t:PrimarySmtpAddress></t:ConnectingSID></t:ExchangeImpersonation><t:TimeZoneContext><t:TimeZoneDefinition Id="Eastern Standard Time" /></t:TimeZoneContext></s:Header><s:Body><m:MoveItem><m:ToFolderId><t:DistinguishedFolderId Id="inbox"><t:Mailbox><t:EmailAddress>qd@dev.com</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:ToFolderId><m:ItemIds><t:ItemId ChangeKey="CQAAABYAAABNZJ5OdoWfRY/kSOProSxqAAADvnR5" Id="AAMkADViMDUxNmEyLWEzN2QtNDhmYi1hZjVjLWQ0OWExYjg4M2VlYwBGAAAAAABKhkpwwDgzQrRlPdCh3fTVBwBNZJ5OdoWfRY/kSOProSxqAAAAqnULAABNZJ5OdoWfRY/kSOProSxqAAADvcrtAAA=" /><t:ItemId ChangeKey="CQAAABYAAABNZJ5OdoWfRY/kSOProSxqAAADvnR7" Id="AAMkADViMDUxNmEyLWEzN2QtNDhmYi1hZjVjLWQ0OWExYjg4M2VlYwBGAAAAAABKhkpwwDgzQrRlPdCh3fTVBwBNZJ5OdoWfRY/kSOProSxqAAAAqnULAABNZJ5OdoWfRY/kSOProSxqAAADvcrsAAA=" /></m:ItemIds></m:MoveItem></s:Body></s:Envelope>

```

**Comment by vikramarsid** [comment] 2017-12-01 13:57
@ecederstrand Do you find anything wrong in the above request XML?

**Comment by ecederstrand** [comment] 2017-12-01 14:08
No, I don't see anything wrong with it :-/

**Comment by ecederstrand** [comment] 2018-01-25 17:08
@vikramarsid Do other operations succeed when you use impersonation?

It looks like you're trying to move an item from the mailbox of `test@dev.com` to the inbox of `qd@dev.com`. It's possible that Exchange, or your version of exchange, simply does not support this operation, or that the connecting account does not have sufficient privileges.

**Comment by ecederstrand** [comment] 2018-08-03 08:38
Closing. My best bet is that moving items between accounts is not supported. Feel free to reopen if you disagree or have additional information.

**Closed by ecederstrand** 2018-08-03 08:38 UTC
