### ISSUE TITLE
Errors with Exchange2010_SP2

### ISSUE THREAD

**Issue by joanrodriguezr** [ecederstrand/exchangelib#672] opened 2019-11-12 17:23 UTC
Hi Erik!

I've been told to fix some errors in one script that uses your library. 

First thing I did was to keep all python dependencies but for your library (which I have upgraded from 1.11.4 to 2.1.0 + defusedxml from 0.5.0 to 0.6.0). The remaining versions that exchangelib would bring I have kept with the a requirements.txt file. After that and seeing that the current scripts were not working I investigated in your doc and another similar issues and I have added this to the script:

```python
  from exchangelib.util import PrettyXmlHandler
  . . .
  logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
```

To get more information for the SOAP messages that are send and received from the ExchangeServer. I also dived into your source code and added some prints but I don't really get more info for the message that is failing nor for their children items (or may am I doing something wrong)

After that I have added:

```python
  from exchangelib.folders import ArchiveInbox, AllItems,Inbox
  from exchangelib.version import EXCHANGE_2010_SP2
  . . .
  ArchiveInbox.supported_from = EXCHANGE_2010_SP2
  AllItems.supported_from = EXCHANGE_2010_SP2
  Inbox.supported_from = EXCHANGE_2010_SP2
   . . .
```

Before creating the Configuration and Account for our email.

The issues I have right now are this two:

*[1] exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
*[2] AttributeError: 'ErrorMimeContentConversionFailed' object has no attribute 'datetime_received'

Those 2 exceptions I want to treat in an except block and trying to move that concrete MailItem to an ERROR folder that I have created to move the all those emails that have this 2 or any other kind of exception.

This error occurs after I do something like this:

```python
  . . .
  allitems = account.inbox.all()
  FilteredMail = allitems.order_by('datetime_received')[startPos:endPos]
  currentMail = None
  try:
     for MailItem in FilteredMail:
         currentMail = MailItem
         . . .
  except Exception as exc:
     # Try to move to ERROR folder
      currentMail.move(to_the_ERROR_folder)
     pass
```

In all the cases currentMail is None so I can't move them to the custom ERROR folder.

Could you shed some light to me please? Why the MailItem in the for loop are None when I really have Items from the inbox?

Thanks in advance!

**Comment by ecederstrand** [comment] 2019-11-12 17:48
You are getting the `AttributeError` because you are trying to access the `datetime_received` attribute of something that is actually an exception instance. Your example code doesn't contain that code, so you'll have to dig for that access in your actual code.

The problem is that the stream of results returned by iterating a queryset *may* contain exception instances. This is because we don't want to fail the entire query just because one item failed to be fetched. You can fix this by doing:

```python
for item in account.inbox.all():
    if isinstance(item, Exception):
        print('Got an error', e)
    else:
        # Do something with the item
```
The `ErrorInternalServerError` is difficult to say anything about without more context. Your best bet is to enable debug logging (see https://github.com/ecederstrand/exchangelib#troubleshooting) to find out see the content of the XML request that triggered this error on the server.

**Comment by ecederstrand** [comment] 2019-11-12 17:51
There are two other closed issues about `ErrorMimeContentConversionFailed` but with no explanatino. I assume it's caused by a broken item in the Exchange database.

**Comment by ecederstrand** [comment] 2019-11-19 07:54
Closing. Feel free to reopen if you have additional questions.

**Closed by ecederstrand** 2019-11-19 07:54 UTC
