### ISSUE TITLE
Implement FindPeople / PersonaShape

### ISSUE THREAD

**Issue by sbuser** [ecederstrand/exchangelib#93] opened 2017-03-05 12:41 UTC
It would be useful to have the ability to find people in the GAL on EWS using FindPeople and Personas. https://msdn.microsoft.com/en-us/library/office/jj191039(v=exchg.150).aspx

I can take those examples and create individual requests, but you seem to have a more robust framework already in place. Would it be possible to add FindPeople easily?

Thanks

**Comment by ecederstrand** [comment] 2017-03-06 11:19
It would certainly be possible to add support for `FindPeople` and `Personas`. Most of the functionality can be re-used from existing code. I think this would be a great enhancement.

**Comment by webratz** [comment] 2017-04-05 10:25
I also could use that feature very well, as the contacts folder only shows the local contacts.

**Comment by rbnvrw** [comment] 2017-05-24 09:30
@ecederstrand Do you have an update on when this will be implemented?

**Comment by ecederstrand** [comment] 2017-05-24 10:31
No, sorry. I'm not working on this actively and I don't have an urgent need myself.

**Comment by fcuencamargalef** [comment] 2018-01-26 09:50
+1

**Comment by akaduri75** [comment] 2018-02-01 10:45
I understand that this is not going to be implemented soon, but at least I'll be happy to get a good advice.
My application, that is based on (great) exchangelib, fetches all contacts and then does some analysis.
The problem is. that every time I want to get the contacts directory updated, I do the following in Outlook:
1. Delete all contacts in my Contacts folder.
2. Open the "Address Book", choose "Global Address List", mark all contacts, right-click, choose "Add to contacts" and wait about 5 minutes.
The problem is that I have to do it manually every time.
After some googling, I found this page, that I hoped will help me to periodically synchronize the contacts folder automatically:
https://www.howto-outlook.com/howto/oabupdate.htm#oabregistryoutlook
Unfortunately, it didn't help. The contacts folder is not synchronized as I hoped.

Can anyone suggest a simple way to automate the population of the contacts folder?

**Comment by ecederstrand** [comment] 2018-03-14 14:20
I just committed a rough implementation of this. My test server doesn't have the 'directory' distinguished folder, and I'm not certain how to access the GAL on my test server. But please play around and report issues! There are further instructions in the commit message.

**Closed** 2018-04-04 20:05 UTC
Labels: enhancement, help wanted

**Comment by thefedoration** [comment] 2021-05-17 16:43
I'm having an issue with the filter functionality from this feature. Looks like I can see contacts and iterate over them all, but not able to filter.
<img width="921" alt="Screen Shot 2021-05-17 at 9 39 55 AM" src="https://user-images.githubusercontent.com/6766645/118525668-4d4b7b80-b6f4-11eb-8c38-c62b9d36380d.png">

**Comment by ecederstrand** [comment] 2021-05-18 19:40
It's possible that EWS simply doesn't support filtering in combination with the `FindPeople` service.

Can you enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and see if we are at least generating a sane request?

**Comment by thefedoration** [comment] 2021-05-21 18:31
BTW I found a way around this filtering issue, explained in this comment:
https://github.com/ecederstrand/exchangelib/issues/162#issuecomment-843308245
