### ISSUE TITLE
[BUG] Filter and Get class methods are hanging without response - DEBUG - Waiting for session

### ISSUE THREAD

**Issue by blueteamzone** [ecederstrand/exchangelib#881] opened 2021-03-24 21:52 UTC
**Describe the bug**
The filter and get class methods are not giving any response.

**To Reproduce**
```
from exchangelib import Account, Credentials, Configuration, DELEGATE
credentials = Credentials(username=username,password=password)
config = Configuration(server='outlook.office365.com',credentials=credentials)
account = Account(primary_smtp_address=smtp_address,config=config,autodiscover=False,access_type=DELEGATE)

email = account.inbox.get(subject='unique_subject') ##hangs without response
email = account.inbox.filter(subject='unique_subject') ##hangs without response
email = account.inbox.get(subject__exact='unique_subject') ##hangs without response
```

**Expected behavior**
I would like to get a response from these functions or timeout after certain minutes.

**Log output**
```
DEBUG:exchangelib.queryset:Initializing cache
DEBUG:exchangelib.folders.collections:Finding [Inbox(Root(<exchangelib.account.Account object at 0x7f9ba0c1add8>, '[self]', 'root', 13, 0, 91, None, 'BASE64_CODE', 'BASE64_CODE', 'BASE64_CODE')] items in folders TEST@TEST.com (shape: IdOnly, depth: Shallow, additional_fields: None, restriction: subject exact '136241384')
DEBUG:exchangelib.services.common:EWS https://outlook.office365.com/EWS/Exchange.asmx, service FindItem: Getting items at offset 0 (max_items None)
DEBUG:exchangelib.services.common:Trying API version Exchange2016
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
DEBUG:exchangelib.protocol:Server outlook.office365.com: No sessions available for 60 seconds
DEBUG:exchangelib.protocol:Server outlook.office365.com: Waiting for session
```

**Additional context**
exchangelib==4.0.0
Python 3.6.9
pip 21.0.1

**Comment by ecederstrand** [comment] 2021-03-25 08:22
This is unexpected. The problem happens because something takes a session from the session pool and never returns it. You should be able to see sessions going in and out of the session pool if you enable debug logging on the `exchangelib.protocol` logger.

I cannot reproduce this locally, and this is a pretty well-tested path. Are you perhaps running this in a multi-threaded environment? Can you trace the session returned by the last succesful `Protocol.get_session()` call and find out why that session is never returned (via either `Protocol.release_session()` or `Protocol.retire_session()`)?

**Comment by blueteamzone** [comment] 2021-03-25 08:33
Could you please tell me how can I enable ` exchangelib.protocol` logging?
Currently for logging I'm running the following snippet:

``` 
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
``` 

Could you also provide a snippet to trace the session?
Thanks

**Comment by ecederstrand** [comment] 2021-03-25 08:37
To trace this, add a `breakpoint()` inside the `Protocol.get_session()` method and step into the code from there. You'll probably enter this method a couple of times before you get into the problematic call where the session is not returned.

The above logging code sets DEBUG level for all exchangelib logging. If you want to reduce logging, you can set level INFO for some loggers, and DEBUG for others:

```python
logging.getLogger('exchnagelib.util').setLevel(logging.INFO)
logging.getLogger('exchnagelib.protocol').setLevel(logging.DEBUG)
```

**Comment by blueteamzone** [comment] 2021-03-25 10:22
I'm not getting this error any longer.
I did not change the code. Maybe it's due to some issue Exchange server side.

**Comment by ecederstrand** [comment] 2021-03-25 10:33
Ok. I'm closing this issue, but feel free to re-open if you hit this again and are able to collect some more information.

**Closed by ecederstrand** 2021-03-25 10:33 UTC
