### ISSUE TITLE
Using newest version (5.1) leads to not finding any meetings

### ISSUE THREAD

**Issue by gabowi** [ecederstrand/exchangelib#1228] opened 2023-09-19 08:44 UTC
**Describe the bug**
Having used exchangelib in version 4.9, we successfully retrieved the entries of a calender. With exchangelib in the newest version, the script fails: no calender entries are found (queried by ourAccount.calendar.view(start, end)).

Interestingly, the build version of our server is detected differently:

exchangelib v4.9:
Build=15.2.1258.0, API=Exchange2019, Fullname=Microsoft Exchange Server 2019

exchangelib v5.1:
Build=15.20.0.0, API=Exchange2015, Fullname=Microsoft Exchange Server 2015

**To Reproduce**
Install exchangelib through pip with exchangelib==4.9.

```python
credentials_accessing_user = Credentials('accessing_user@our_domain', 'accessing_user_password')
account_accessing_user = Account('accessing_user@our_domain', credentials=credentials_accessing_user, autodiscover=True)

mailbox_by_calendar = Account(
  primary_smtp_address='our_shared_calendar_address@our_domain', credentials=credentials_accessing_user,
  autodiscover=True, access_type=DELEGATE
)

actual_calendar = mailbox_by_calendar.calendar
actual_calendar.view(start = startTimeframe, end = endTimeframe)
```

**Expected behavior**
Retrieve calender entries successfully, as was the case with the previous version.

**Additional context**
Python 3.11.4 in both cases
Exchangelib 4.9 vs. 5.1 (not tested with other versions).

**Comment by ecederstrand** [comment] 2023-09-19 09:19
Can you please [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and check the difference in the FindItems XML requests between the two versions?

**Comment by ecederstrand** [comment] 2023-09-19 09:22
Also, are your using autodiscover to connect? It's possible that the two versions hit different Exchange servers. You can check with `print(some_account.protocol.server)`.

**Comment by gabowi** [comment] 2023-09-19 11:07
> Also, are your using autodiscover to connect? It's possible that the two versions hit different Exchange servers. You can check with `print(some_account.protocol.server)`.

Yes, we are using autodiscover. But the returned URL is the exactly same, thus the same Exchange server is hit with both versions.



> Can you please [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and check the difference in the FindItems XML requests between the two versions?

In fact, there are differences. The mailbox element is missing, see below. At the starting question, I added the minimum example for more clarity on our specific handling.

v4.9:
```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<s:Header>
		<t:RequestServerVersion Version="Exchange2016"/>
		<t:TimeZoneContext>
			<t:TimeZoneDefinition Id="W. Europe Standard Time"/>
		</t:TimeZoneContext>
	</s:Header>
	<s:Body>
		<m:FindItem Traversal="Shallow">
			<m:ItemShape>
				<t:BaseShape>IdOnly</t:BaseShape>
			</m:ItemShape>
			<m:CalendarView StartDate="2023-09-19T00:00:00+02:00" EndDate="2023-09-26T23:59:00+02:00"/>
			<m:ParentFolderIds>
				<t:DistinguishedFolderId Id="calendar">
					<t:Mailbox>
						<t:EmailAddress>our_shared_calendar_address@our_domain</t:EmailAddress>
						<t:RoutingType>SMTP</t:RoutingType>
						<t:MailboxType>Mailbox</t:MailboxType>
					</t:Mailbox>
				</t:DistinguishedFolderId>
			</m:ParentFolderIds>
		</m:FindItem>
	</s:Body>
</s:Envelope>
```

v5.1:
```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<s:Header>
		<t:RequestServerVersion Version="Exchange2015"/>
		<t:TimeZoneContext>
			<t:TimeZoneDefinition Id="W. Europe Standard Time"/>
		</t:TimeZoneContext>
	</s:Header>
	<s:Body>
		<m:FindItem Traversal="Shallow">
			<m:ItemShape>
				<t:BaseShape>IdOnly</t:BaseShape>
			</m:ItemShape>
			<m:CalendarView StartDate="2023-09-19T00:00:00+02:00" EndDate="2023-09-26T23:59:00+02:00"/>
			<m:ParentFolderIds>
				<t:DistinguishedFolderId Id="calendar"/>
			</m:ParentFolderIds>
		</m:FindItem>
	</s:Body>
</s:Envelope>
```

Does this help to understand the problem? Was there maybe a change in how delegates are handled in exchangelib?

**Comment by ecederstrand** [comment] 2023-09-19 13:59
Ah, so you are connecting with two accounts. In that case, I think this is a duplicate of #1222

**Comment by gabowi** [comment] 2023-09-19 14:07
Ok. In case I can support with any tests, please let me know.

**Closed** 2023-10-04 11:54 UTC
