### ISSUE TITLE
MailRecipientNotFoundException is not thrown when target email is not found using GetUserAvailability

### ISSUE THREAD

**Issue by james10424** [ecederstrand/exchangelib#1060] opened 2022-02-28 20:02 UTC
**Describe the bug**
When calling `get_free_busy_info` with an email that you do not have access to, or it does not exist, `MailRecipientNotFoundException` is not thrown, even though the [documentation](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getuseravailability-operation) says it will.

> If the target mailbox is unavailable or cannot be found, a MailRecipientNotFoundException exception is thrown. The client receives an error message that states that the mail recipient is not found in the Active Directory directory service or Active Directory Domain Services (AD DS).

Instead, this is returned:
```
ErrorProxyRequestProcessingFailed: Proxy web request failed. , inner exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Microsoft.Exchange.InfoWorker.Common.Availability.Proxy.RestService.EndGetSchedule(IAsyncResult asyncResult)
   at Microsoft.Exchange.InfoWorker.Common.Availability.FreeBusyApplication.EndRestProxyWebRequest(RestProxyWebRequest proxyWebRequest, QueryList queryList, RestService service, IAsyncResult asyncResult)
   at Microsoft.Exchange.InfoWorker.Common.Availability.RestProxyWebRequest.EndInvoke(IAsyncResult asyncResult)
   at Microsoft.Exchange.InfoWorker.Common.Availability.AsyncWebRequest.EndInvokeWithErrorHandling()
```

**To Reproduce**
```
c = Credentials(...)
a = Account(...)
start = datetime.now(a.default_timezone)
end = start+timedelta(hours=6)
info = a.protocol.get_free_busy_info(accounts=[("some_random_email_that_does_not_exist@outlook.com", "Required", False)], start=start, end=end)
free_busy = [i for i in info]
**EXCEPTION OCCURS HERE**
```

**Expected behavior**
`MailRecipientNotFoundException` is expected

**Log output**
If applicable, add relevant output from [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) .

**Additional context**
For example, Python and exchangelib versions.
Python 3.8.12
exchangelib==4.7.2

**Comment by ecederstrand** [comment] 2022-03-01 09:24
This exception is coming from the server and looks like an internal error from the Exchange server, possibly due to configuration problems, malfunctioning hardware, or a bug in Exchange. There's nothing exchangelib can do to fix this.

**Comment by ecederstrand** [comment] 2022-03-07 08:45
Closing, as I don't think there's anything exchangelib can do to fix the error message or the cause of the error.

**Closed by ecederstrand** 2022-03-07 08:45 UTC
