### ISSUE TITLE
Rename Folders

### ISSUE THREAD

**Issue by rodrigues8** [ecederstrand/exchangelib#796] opened 2020-08-17 23:57 UTC
Good night,

I would like to ask for help, I am very confused with the documentation, I needed to rename some folders that have the character '/' that are disturbing the imap queries, however when trying to rename I am not getting it, below:

```
from exchangelib import Credentials, Account, Configuration, DELEGATE, Folder

def ConnectEWS( url, mail, pw ):
    credentials = Credentials( mail, pw )
    config = Configuration ( server = url, credentials = credentials)
    account = Account( mail, config=config, autodiscover=False, access_type=DELEGATE)

    return account

url = 'xxx'
mail = 'xxx'
pw = 'xxx'

account = ConnectEWS( url, mail, pw )

for subfolder in account.root.walk():
    if re.search('/', subfolder.name):
        subfolder.name = subfolder.name.replace('/',  '-')
        subfolder.save()
```

Error message:

Traceback (most recent call last):
  File "/skymail/tools/skykit/bin/python/ews-renamefolders.py", line 29, in <module>
    subfolder.save()
  File "/usr/lib/python2.7/site-packages/exchangelib/folders/base.py", line 389, in save
    res = list(UpdateFolder(account=self.account).call(folders=[(self, update_fields)]))
  File "/usr/lib/python2.7/site-packages/exchangelib/services/update_folder.py", line 20, in call
    for folder, elem in zip(folders_list, self._get_elements(payload=self.get_payload(folders=folders))):
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 154, in _get_response_xml
    res = self._get_soap_messages(body=body, **parse_opts)
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 261, in _get_soap_messages
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 297, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.

Can someone help me?

Graciously.

**Comment by ecederstrand** [comment] 2020-08-18 05:07
I just did a quick test and cannot reproduce:

```python
c = Credentials(username, password)
a = Account(c.username, credentials=c, autodiscover=True)
print(a.inbox.tree())
f = Folder(name='sla/sh', parent=a.inbox)
f.save()
a.root.clear_cache()
print(a.inbox.tree())
f.name = f.name.replace('/', '-')
f.save()
a.root.clear_cache()
print(a.inbox.tree())
f.delete()
```

which outputs:
```
Inbox

Inbox
└── sla/sh

Inbox
└── sla-sh
```

Which server version is this? `account.protocol.version` will tell you.

Also, please enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and post the request XML that triggers this error.

If you can't get it to work, a workaround is to rename the folder using a different client, e.g. Outlook.

**Comment by rodrigues8** [comment] 2020-08-19 16:51
Good afternoon,

My problem is with folders that already exist in the account, this example that you passed the folder was created and then renamed, it works, I already tested it. However, if the folder already exists in the account, it is not possible to rename it.

I wanted to do this automation, as it has accounts with more than 100 folders with '/' and as this creates a problem in IMAP sync I have problems with message migration. To do this manually in different accounts is a very arduous process.

I'll do the troubleshooting and pass you on.

Graciously.

**Comment by ecederstrand** [comment] 2020-08-19 19:14
So it works to delete a folder created by exchangelib but not a folder created by some other means. How? There must be some difference between the two types of folders. What is that difference? Can you reproduce if you create a new folder without exchangelib and try to delete that?

**Comment by rodrigues8** [comment] 2020-08-20 22:06
Good night,

Sorry if I was not very clear, I will leave below the tests I did:

1 - First I created a new account to do the tests, I will leave it below if you want to use

2 - I created a folder via webmail, called 'Exchangelib / exists'

3 - I adjusted the script for both tests:


```
#!/usr/bin/python

import logging
import re

from exchangelib import Credentials, Account, Configuration, DELEGATE, Folder
from exchangelib.util import PrettyXmlHandler

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

def ConnectEWS( url, mail, pw ):
    credentials = Credentials( mail, pw )
    config = Configuration ( server = url, credentials = credentials)
    account = Account( mail, config=config, autodiscover=False, access_type=DELEGATE)

    return account

url = 'webapp.skymail.net.br'
mail = 'exchangelib@skydemo.com.br'
pw = 'Bm3Dy3Ej'

a = ConnectEWS( url, mail, pw )

print("Protocol Version:", a.protocol.version)
print("Create folder, rename, and delete with exchangelib")
print(a.inbox.tree())
f = Folder(name='sla/sh', parent=a.inbox)
f.save()
a.root.clear_cache()
print(a.inbox.tree())
f.name = f.name.replace('/', '-')
f.save()
a.root.clear_cache()
print(a.inbox.tree())
f.delete()
a.root.clear_cache()
print(a.inbox.tree())

print("Renaming folder created by webmail, folder name: 'exchangelib / exists")
print(a.inbox.tree())
for subfolder in a.inbox.walk():
    if re.search('/', subfolder.name):
        subfolder.name = subfolder.name.replace('/',  '-')
        subfolder.save()
        a.root.clear_cache()
        print(a.inbox.tree())
```

The script's response was as follows:

```
('Protocol Version:', Version(Build(15, 2, 464, 5), u'Exchange2016'))

Create folder, rename, and delete with exchangelib

Caixa de Entrada
└── exchangelib / exists

Caixa de Entrada
├── exchangelib / exists
└── sla/sh

Caixa de Entrada
├── exchangelib / exists
└── sla-sh

Caixa de Entrada
└── exchangelib / exists

Renaming folder created by webmail, folder name: 'exchangelib / exists

Caixa de Entrada
└── exchangelib / exists

Traceback (most recent call last):
  File "/skymail/tools/skykit/bin/python/ews-renamefolders.py", line 48, in <module>
    subfolder.save()
  File "/usr/lib/python2.7/site-packages/exchangelib/folders/base.py", line 389, in save
    res = list(UpdateFolder(account=self.account).call(folders=[(self, update_fields)]))
  File "/usr/lib/python2.7/site-packages/exchangelib/services/update_folder.py", line 20, in call
    for folder, elem in zip(folders_list, self._get_elements(payload=self.get_payload(folders=folders))):
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 71, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 154, in _get_response_xml
    res = self._get_soap_messages(body=body, **parse_opts)
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 261, in _get_soap_messages
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/usr/lib/python2.7/site-packages/exchangelib/services/common.py", line 297, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
```

The debug part at the time of the error also follows:

```
DEBUG:exchangelib.services.update_folder:Updating folder Messages (exchangelib - exists)
DEBUG:exchangelib.services.common:Trying API version Exchange2016 for account exchangelib@skydemo.com.br
DEBUG:exchangelib.protocol:Server webapp.skymail.net.br: Waiting for session
DEBUG:exchangelib.protocol:Server webapp.skymail.net.br: Got session 12998
DEBUG:exchangelib.util:Session 12998 thread 139650079729472: retry 0 timeout 120 POST'ing to https://webapp.skymail.net.br/EWS/Exchange.asmx after 10s wait
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 500 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 12998
Thread: 139650079729472
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f02c197f1d0>
URL: https://webapp.skymail.net.br/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f02c197f490>
Allow redirects: False
Streaming: False
Response time: 0.0474898815155
Status code: 500
Request headers: {'Content-Length': '2179', 'Accept-Encoding': u'gzip, deflate', 'X-AnchorMailbox': 'exchangelib@skydemo.com.br', 'Accept': '*/*', 'User-Agent': u'exchangelib/2.2.0 (python-requests/2.7.0 CPython/2.7.5 Linux/3.10.0-862.11.6.el7.x86_64)', 'Connection': 'Keep-Alive', 'Cookie': 'X-BackEndCookie=S-1-5-21-920983306-374479131-3432935423-99395=u56Lnp2ejJqBmpqdzZvGmp7SnZrLm9LLnc6c0sbKmsrSzM6emsacyMbOyM/HgYHNz83P0s/G0s7Gq83OxcvNxc/KgYyUhpKelpPRkZqL0Z2Ngc8=&exchangelib@skydemo.com.br=u56Lnp2ejJqBmpqdzZvGmp7SnZrLm9LLnc6c0sbKmsrSzM6emsacyMbOyM/HgYHNz83P0s/G0s7Gq83OxcvNxc7PgYyUhpKelpPRkZqL0Z2Ngc8=; exchangecookie=6e9c513f6b81468788a8d79e8f0c875a', 'Content-Type': u'text/xml; charset=utf-8'}
Response headers: {'x-calculatedbetarget': 'skysrv001.skymail.net.br', 'x-aspnet-version': '4.0.30319', 'transfer-encoding': 'chunked', 'request-id': 'b0605462-aa28-41c5-b41a-4c07f010cc71', 'x-powered-by': 'ASP.NET', 'set-cookie': 'exchangecookie=6e9c513f6b81468788a8d79e8f0c875a; path=/, X-BackEndCookie=S-1-5-21-920983306-374479131-3432935423-99395=u56Lnp2ejJqBmpqdzZvGmp7SnZrLm9LLnc6c0sbKmsrSzM6emsacyMbOyM/HgYHNz83P0s/G0s7Gq83OxcvNxc/KgYyUhpKelpPRkZqL0Z2Ngc8=&exchangelib@skydemo.com.br=u56Lnp2ejJqBmpqdzZvGmp7SnZrLm9LLnc6c0sbKmsrSzM6emsacyMbOyM/HgYHNz83P0s/G0s7Gq83OxcvNxc7PgYyUhpKelpPRkZqL0Z2Ngc8=; expires=Sat, 19-Sep-2020 21:42:10 GMT; path=/EWS; secure; HttpOnly', 'server': 'Microsoft-IIS/10.0', 'x-beserver': 'SKYSRV001', 'x-diaginfo': 'SKYSRV001', 'x-feserver': 'SKYSRV003', 'cache-control': 'private', 'date': 'Thu, 20 Aug 2020 21:42:10 GMT', 'content-type': 'text/xml; charset=utf-8'}
Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/><t:TimeZoneContext><t:TimeZoneDefinition Id="E. South America Standard Time"/></t:TimeZoneContext></s:Header><s:Body><m:UpdateFolder><m:FolderChanges><t:FolderChange><t:FolderId Id="AQMkAGI1ZGM5NmRlLTU2YjctNDg5OC05MmYyLTVmMDQyNWVhNDc3ADMALgAAAyJIf+jDnSJNuEo7stYZkRoBABXQZYe8vQlOnZKnMODD8OEAAAIBWQAAAA==" ChangeKey="AQAAABYAAAAV0GWHvL0JTp2SpzDgw/DhAAAAAAiM"/><t:Updates><t:SetFolderField><t:FieldURI FieldURI="folder:FolderClass"/><t:Folder><t:FolderClass>IPF.Note</t:FolderClass></t:Folder></t:SetFolderField><t:SetFolderField><t:FieldURI FieldURI="folder:DisplayName"/><t:Folder><t:DisplayName>exchangelib - exists</t:DisplayName></t:Folder></t:SetFolderField><t:SetFolderField><t:FieldURI FieldURI="folder:PermissionSet"/><t:Folder><t:PermissionSet><t:PermissionSet><t:Permissions><t:Permission><t:PermissionLevel>None</t:PermissionLevel><t:CanCreateItems>0</t:CanCreateItems><t:CanCreateSubfolders>0</t:CanCreateSubfolders><t:IsFolderOwner>0</t:IsFolderOwner><t:IsFolderVisible>0</t:IsFolderVisible><t:IsFolderContact>0</t:IsFolderContact><t:EditItems>None</t:EditItems><t:DeleteItems>None</t:DeleteItems><t:ReadItems>None</t:ReadItems><t:UserId><t:UserId><t:DistinguishedUser>Default</t:DistinguishedUser></t:UserId></t:UserId></t:Permission><t:Permission><t:PermissionLevel>None</t:PermissionLevel><t:CanCreateItems>0</t:CanCreateItems><t:CanCreateSubfolders>0</t:CanCreateSubfolders><t:IsFolderOwner>0</t:IsFolderOwner><t:IsFolderVisible>0</t:IsFolderVisible><t:IsFolderContact>0</t:IsFolderContact><t:EditItems>None</t:EditItems><t:DeleteItems>None</t:DeleteItems><t:ReadItems>None</t:ReadItems><t:UserId><t:UserId><t:DistinguishedUser>Anonymous</t:DistinguishedUser></t:UserId></t:UserId></t:Permission></t:Permissions></t:PermissionSet></t:PermissionSet></t:Folder></t:SetFolderField></t:Updates></t:FolderChange></m:FolderChanges></m:UpdateFolder></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInternalServerError</faultcode><faultstring xml:lang="en-US">An internal server error occurred. The operation failed.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInternalServerError</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">An internal server error occurred. The operation failed.</e:Message></detail></s:Fault></s:Body></s:Envelope>

DEBUG:exchangelib.util:No retry: wrong status code
DEBUG:exchangelib.util:Got status code 500 but trying to parse content anyway
DEBUG:exchangelib.util:Session 12998 thread 139650079729472: Useful response from https://webapp.skymail.net.br/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server webapp.skymail.net.br: Releasing session 12998
DEBUG:exchangelib.services.common:No header in XML response
```

I noticed in another part of the debug above, is that the folder created in webmail was like Messages type and the folder created by exchangelib was like Folder type, I think this may have some relation with the error:

```
DEBUG: exchangelib.services.common: Collecting folder Messages (exchangelib / exists)
DEBUG: exchangelib.services.common: Collecting folder Folder (sla-sh)
```

**Comment by ecederstrand** [comment] 2020-08-21 05:46
You can make the two folder even more alike by creating both as the Messages folder type. Also, what happens if you specify to have only the name updated, and not all other fields?

```python
from exchangelib import Credentials, Account
from exchangelib.folders import Messages

c = Credentials(username, password)
a = Account(c.username, credentials=c, autodiscover=True)
print(a.inbox.tree())
f = Messages(name='exchangelib / exists', parent=a.inbox)
f.save()
a.root.clear_cache()
print(a.inbox.tree())
f.name = f.name.replace('/', '-')
f.save(update_fields=['name'])
a.root.clear_cache()
print(a.inbox.tree())
f.delete()
```
(I can't get that to fail, either).

Finally, it would be interesting to see the exact definition of the two folders as returned in the response XML. If you use the `PrettyXmlHandler` logging handler, you can copy-paste the relevant parts of the response to the `GetFolder` request in a more human-friendly format.

When you paste the code here, you can even use XML-styled code blocks to have proper syntax-highlighting (like you can for python). This:
````
```xml
<some>(broken) XML document</here>
```
````
will show up as:
```xml
<some>(broken) XML document</here>
```

**Comment by rodrigues8** [comment] 2020-08-21 06:04
Good evening,

It worked with the specification of the field that was going to be updated, thanks for the help and tips for using github (I'm a little novice, I confess) helped me a lot! Just to finish, follow the code below:

```python
#!/usr/bin/python

import logging
import re

from exchangelib import Credentials, Account, Configuration, DELEGATE, Folder

def ConnectEWS( url, mail, pw ):
    credentials = Credentials( mail, pw )
    config = Configuration ( server = url, credentials = credentials)
    account = Account( mail, config=config, autodiscover=False, access_type=DELEGATE)

    return account

url = 'webapp.skymail.net.br'
mail = 'exchangelib@skydemo.com.br'
pw = 'Bm3Dy3Ej'

a = ConnectEWS( url, mail, pw )

print("Renaming folder created by webmail, folder name: 'exchangelib / exists")
print(a.inbox.tree())
for subfolder in a.root.walk():
    if re.search('/', subfolder.name):
        subfolder.name = subfolder.name.replace('/',  '-')
        subfolder.save(update_fields=['name'])
        a.root.clear_cache()
        print(a.inbox.tree())

```
Graciously.

**Comment by ecederstrand** [comment] 2020-08-21 08:31
Ok. That brings us a lot closer. Now we just need to find out which field the server is throwing an exception on. Can you try this and report which fields are failing?

```python
f.name = f.name.replace('/', '-')
for field in f.FIELDS:
    if field.is_read_only:
        continue
    try:
        f.save(update_fields=[field])
    except Exception as e:
        print('Field %r cannot be saved (%s)' % (f.name, e))
```

**Comment by ecederstrand** [comment] 2020-08-27 12:40
Hi @rodrigues8 Would you mind running the above for me? Then we can find out which fields are triggering the exception on the server.

**Comment by rodrigues8** [comment] 2020-09-01 15:44
Good afternoon,

Sorry for the delay, I had some unforeseen events.
I had to change your code a little because it wasn't working to simulate the error, I put it like this:

```python
            for field in subfolder.FIELDS:
                if field.is_read_only:
                    continue
                try:
                    subfolder.save(update_fields=[field.name])
                except Exception as e:
                    print field.name, field
                    print('Field %r cannot be saved (%s)' % (subfolder.name, e))
```
I came to the following conclusion:

```
permission_set PermissionSetField(name=u'permission_set', value_cls=<class 'exchangelib.properties.PermissionSet'>, is_list=False, is_complex=True, default=None)
Field 'E - E' cannot be saved (An internal server error occurred. The operation failed.)

permission_set PermissionSetField(name=u'permission_set', value_cls=<class 'exchangelib.properties.PermissionSet'>, is_list=False, is_complex=True, default=None)
Field 'exchangelib - exists' cannot be saved (An internal server error occurred. The operation failed.)

permission_set PermissionSetField(name=u'permission_set', value_cls=<class 'exchangelib.properties.PermissionSet'>, is_list=False, is_complex=True, default=None)
Field '1-2-3' cannot be saved (An internal server error occurred. The operation failed.)

permission_set PermissionSetField(name=u'permission_set', value_cls=<class 'exchangelib.properties.PermissionSet'>, is_list=False, is_complex=True, default=None)
Field '0-0' cannot be saved (An internal server error occurred. The operation failed.)

permission_set PermissionSetField(name=u'permission_set', value_cls=<class 'exchangelib.properties.PermissionSet'>, is_list=False, is_complex=True, default=None)
Field 'EEEEEEEE -------------' cannot be saved (An internal server error occurred. The operation failed.)
```

The error is in the permission_set field

Thanks.

**Comment by ecederstrand** [comment] 2020-09-02 11:28
Ok, so this is the `Folder.permission_set` field popping up. Maybe you don't have permissions to update the permission set, and EWS doesn't detect that there are no changes in the new value. It would have been nice with a better error message from the server :-/

I'm not sure if anything can be done in exchangelib to fix this. Updating the field definitely works in some situations, so we can't just make the field read-only.

**Comment by rodrigues8** [comment] 2020-09-02 23:04
Good night,

Yes, I understand, the direct update of the name field already works very well and helps me in my case. However, if you need any other type of testing, tell me what I do here in my environment.

You helped me a lot!

Graciously.

**Comment by ecederstrand** [comment] 2020-09-03 10:25
Ok, let's close the issue then. I think the problem and workaround has been described in sufficient detail in this issue. Let's hope someone else finds this if they run into the same issue.

**Closed by ecederstrand** 2020-09-03 10:25 UTC
