### ISSUE TITLE
Contacts: Synchronization notes, title and photo is it possible? 

### ISSUE THREAD

**Issue by hafedh305** [ecederstrand/exchangelib#645] opened 2019-09-24 09:03 UTC
Hello, 
Thank you verry much for this API.
Please, we wish to synchronize notes, title and photo of the contact but seems that this is not possible with the current version of the API!
Can you please confirm me?
If so, do you think you will add that?

Thank you very much already

**Comment by hafedh305** [comment] 2019-09-24 10:31
Thank you,
1/ Notes exist but it's marked as ReadOnly, we can not synchronize it to xchange! No?
![notes_is_readonly](https://user-images.githubusercontent.com/16020039/65504308-ee097980-dec6-11e9-8807-0573709e6a24.png)
2/ HasPicture it's also Readonly!
3/ I will try to use "JobTitle".
Thanks

**Comment by ecederstrand** [comment] 2019-09-24 10:54
`HasPicture` may be readonly because it's a calculated value. I just did a quick test adding a picture to a contact via OWA, and it results in a file attachment on the contact that looks something like this:

```python
FileAttachment(
    attachment_id=AttachmentId(id='AAMkAGR=', root_id=None, root_changekey=None), 
    name='ContactPicture.jpg', 
    content_type='image/jpeg', 
    size=8506, 
    last_modified_time=EWSDateTime(2019, 9, 24, 12, 27), 
    is_inline=False, 
    is_contact_photo=True
)
```

So probably if you add a file attachment and set `is_contact_photo=True`, then `HasPicture` will change to `True`.

I can't remember why `notes` is read-only. You can try to change the read-only setting here and give it a try. Please report back with your findings: https://github.com/ecederstrand/exchangelib/blob/ca29b437f49400fd3d18ec3e03a1b21a757ea7c4/exchangelib/items.py#L941

**Comment by ecederstrand** [comment] 2019-09-24 11:07
I just made this quick test which I have confirmed adds a photo to the contact:

```python
cnt = a.contacts.get(given_name='Test2')
att = FileAttachment(name='ContactPicture.jpg', content_type='image/png', is_inline=False, is_contact_photo=True, content=open(/home/me/Downloads/avatar.png', 'rb').read())
cnt.attach(att)
```

**Comment by hafedh305** [comment] 2019-09-24 11:23
I tryed without readonly attribute but i have this Exception:  Exception Detail An object within a change description must contain one and only one property to modify.____ 

contact Info: 
Contact(mime_content=b'BEGIN:VCARD\r\nPROFILE:VCARD\r\nVERSION:3.0\r\nMAILER:Microsoft Exchange\r\nPRODID:Microsoft Exchange\r\nFN:RAHMANI Thibaut\r\nN:RAHMANI;Thibaut;;;\r\nEMAIL;TYPE=INTERNET:thibaut@mymicroinvest.com\r\nORG:;\r\nCLASS:PUBLIC\r\nADR;TYPE=WORK:;;;;;;\r\nLABEL;TYPE=WORK:\r\nADR;TYPE=HOME:;;;;;;\r\nADR;TYPE=POSTAL:;;;;;;\r\nNICKNAME:rahmani-thibaut-27591\r\nTITLE: \r\nREV;VALUE=DATE-TIME:2019-09-24T08:38:58,720Z\r\nEND:VCARD\r\n', id='AAMkADExMjljYjBmLWQ2ZmMtNGZjZS1hNDdkLTFmNTM1NWM4YmQwMQBGAAAAAAD/kXCljLU6TreV/eucSNChBwCapxcFyUy1S64MR3x0wWM5AAAAAAEOAACapxcFyUy1S64MR3x0wWM5AAEW0C2EAAA=', changekey='EQAAABYAAACapxcFyUy1S64MR3x0wWM5AAEWyFpy', parent_folder_id=ParentFolderId(id='AAMkADExMjljYjBmLWQ2ZmMtNGZjZS1hNDdkLTFmNTM1NWM4YmQwMQAuAAAAAAD/kXCljLU6TreV/eucSNChAQCapxcFyUy1S64MR3x0wWM5AAAAAAEOAAA=', changekey='AQAAAA=='), item_class='IPM.Contact', subject='Thibaut RAHMANI', sensitivity='Normal', attachments=[], datetime_received=EWSDateTime(2019, 9, 24, 8, 38, 57, tzinfo=<UTC>), size=2076, importance='Normal', is_submitted=False, is_draft=True, is_from_me=False, is_resend=False, is_unmodified=False, datetime_sent=EWSDateTime(2019, 9, 24, 8, 38, 57, tzinfo=<UTC>), datetime_created=EWSDateTime(2019, 9, 24, 8, 38, 57, tzinfo=<UTC>), reminder_is_set=False, reminder_minutes_before_start=0, has_attachments=False, culture='en-US', effective_rights=EffectiveRights(create_associated=False, create_contents=False, create_hierarchy=False, delete=True, modify=True, read=True, view_private_items=True), last_modified_name='Test API', last_modified_time=EWSDateTime(2019, 9, 24, 8, 38, 58, tzinfo=<UTC>), is_associated=False, web_client_read_form_query_string='https://outlook.office365.com/owa/?ItemID=AAMkADExMjljYjBmLWQ2ZmMtNGZjZS1hNDdkLTFmNTM1NWM4YmQwMQBGAAAAAAD%2FkXCljLU6TreV%2FeucSNChBwCapxcFyUy1S64MR3x0wWM5AAAAAAEOAACapxcFyUy1S64MR3x0wWM5AAEW0C2EAAA%3D&exvsurl=1&viewmodel=PersonaCardViewModelFactory', conversation_id=ConversationId(id='AAQkADExMjljYjBmLWQ2ZmMtNGZjZS1hNDdkLTFmNTM1NWM4YmQwMQAQALNoxTM1X4pKvM92jdiM2q8=', changekey=None), unique_body='<html><body></body></html>', file_as_mapping='None', display_name='RAHMANI Thibaut', given_name='Thibaut', nickname='rahmani-thibaut-27591', email_addresses=[EmailAddress(label='EmailAddress1', email='thibaut@mymicroinvest.com')], physical_addresses=[PhysicalAddress(label='Business', street='', city='', state='', country='', zipcode='')], phone_numbers=[PhoneNumber(label='BusinessPhone', phone_number=' '), PhoneNumber(label='MobilePhone', phone_number=' '), PhoneNumber(label='BusinessFax', phone_number=' ')], job_title=' ', postal_address_index='None', surname='RAHMANI', 

notes='Notes..')_

**Comment by ecederstrand** [comment] 2019-09-24 11:26
Writing to the `notes` field just raises `ErrorInvalidPropertyRequest` in my tests. Instead, OWA just writes to the 'body' field when you enter something in the `notes` form field. You can try using `body` instead.

**Comment by hafedh305** [comment] 2019-09-24 11:35
I think I have trouble understanding, could you send me an example please?
I can not find the field body!

**Comment by ecederstrand** [comment] 2019-09-24 11:41
I just updated the documentation on contacts with an example: https://github.com/ecederstrand/exchangelib#contacts

**Comment by hafedh305** [comment] 2019-09-24 11:51
Thank you, Thank you very very much. 
Sync note work fine now.

**Comment by ecederstrand** [comment] 2019-09-25 05:49
Closing. Feel free to reopen if you there are remaining issues.

**Closed by ecederstrand** 2019-09-25 05:49 UTC
