### ISSUE TITLE
the meeting timezone changed

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [ecederstrand/exchangelib#471] opened 2018-09-06 09:07 UTC
i update a meeting item , but the meeting item's timezone changed .
here is my code 
![image](https://user-images.githubusercontent.com/24671601/45147048-a7cb7480-b1f6-11e8-85cb-ac95e8769349.png)
you can see my timezone is "Asia/Shanghai",that's ture
![image](https://user-images.githubusercontent.com/24671601/45147265-258f8000-b1f7-11e8-8e01-386c7e9d87ae.png)

then i changed the meeting item's subject ,here is my code
![image](https://user-images.githubusercontent.com/24671601/45147182-f1b45a80-b1f6-11e8-90dc-734109c601ae.png)
the my subject and the time all changed.
how can i fix this?
![image](https://user-images.githubusercontent.com/24671601/45147525-b1a1a780-b1f7-11e8-82e4-b27c7ae348ae.png)

**Comment by SamGenTLEManKaka** [comment] 2018-09-06 09:26
i don't change any time or timezone 
i just change the subject 
but the time changed

**Comment by ecederstrand** [comment] 2018-09-06 14:27
When you post example code, please post plain text instead of screenshots. It makes it much easier to read, copy-paste and test your code.

I can't reproduce the issue using version 1.11.4. I ran the following:

```python
c = Credentials('username', 'password')
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)
tz = EWSTimeZone.localzone()
print(tz)
item = CalendarItem(
    folder=a.calendar, 
    subject='TZ Test',
    start=tz.localize(EWSDateTime(2018, 10, 1, 8, 0)), 
    end=tz.localize(EWSDateTime(2018, 10, 1, 10, 0)),
).save()
print(item.start, item._start_timezone, item.end, item._end_timezone)
fresh_item = a.calendar.get(item_id=item.item_id)
print(fresh_item.start, fresh_item._start_timezone, fresh_item.end, fresh_item._end_timezone)
fresh_item.subject = 'TZ Test changed'
fresh_item.save()
changed_item = a.calendar.get(item_id=fresh_item.item_id)
print(changed_item.start, changed_item._start_timezone, changed_item.end, changed_item._end_timezone)
item.delete()
```

which printed:

```python
Europe/Copenhagen
2018-10-01 08:00:00+02:00 Europe/Copenhagen 2018-10-01 10:00:00+02:00 Europe/Copenhagen
2018-10-01 06:00:00+00:00 Europe/Copenhagen 2018-10-01 08:00:00+00:00 Europe/Copenhagen
2018-10-01 06:00:00+00:00 Europe/Copenhagen 2018-10-01 08:00:00+00:00 Europe/Copenhagen
```

This means the server remembered the timezone of the start and end dates, and didn't change the timestamp. The difference in output is just that the two last lines print the start and end n UTC instead of localized time. That's a feature, and the timestamps are still the same, just in different timezones.

**Comment by SamGenTLEManKaka** [comment] 2018-09-07 01:50
thank for your answer!
I restored the scene:
here is my code :
```python
tz = EWSTimeZone.localzone()
print(tz)
thistime = EWSDateTime.from_datetime(datetime.datetime.now())
calendar_item = CalendarItem(
    account=account,
    folder=account.calendar,
    start=tz.localize(thistime+datetime.timedelta(hours=1)),
    end=tz.localize(thistime+datetime.timedelta(hours=2)),
    subject="Subject of Meeting",
    body="Please come to my meeting",
    location = "home",
    required_attendees=['father@contoso.com'],
    is_response_requested=False,
    allow_new_time_proposal = False,
    reminder_minutes_before_start = 59
)
calendar_item.save(send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY)
print(calendar_item.start,calendar_item._start_timezone)
print(calendar_item.end,calendar_item._end_timezone)
changed_item = account.calendar.get(item_id=calendar_item.item_id)
calendar_item.subject = "111"
calendar_item.save(send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY)
print(changed_item.start, changed_item._start_timezone, changed_item.end,changed_item._end_timezone)
```
print
```python
Asia/Shanghai
2018-09-07 10:42:24.715393+08:00 Asia/Shanghai
2018-09-07 11:42:24.715393+08:00 Asia/Shanghai
2018-09-07 02:42:24+00:00 Asia/Hong_Kong 2018-09-07 03:42:24+00:00 Asia/Hong_Kong
```

**Comment by ecederstrand** [comment] 2018-09-07 06:42
Which version of Exchange is this? I'm asking because timezones are handled differently depending on the Exchange version. `print(account.protocol.version)` will tell you, if you don't know.

**Comment by SamGenTLEManKaka** [comment] 2018-09-10 03:44
I have done a lot of testing on this issue, and I still don’t have any clues until now.

**Comment by SamGenTLEManKaka** [comment] 2018-09-12 06:41
![image](https://user-images.githubusercontent.com/24671601/45406645-b522ac00-b699-11e8-8745-8c038a7b04b1.png)

**Comment by ecederstrand** [comment] 2018-09-14 12:19
Try deleting C:\programdata\anaconda3\site-packages\exchangelib* entirely and install again from GitLab. Sometimes pip does not properly delete all existing package files.

**Comment by SamGenTLEManKaka** [comment] 2018-09-17 02:17
It seems to work, I will do more tests.

**Comment by ecederstrand** [comment] 2018-09-20 11:32
Closing. Feel free to reopen if this still doesn't work as expected.

**Closed by ecederstrand** 2018-09-20 11:32 UTC

**Comment by mak627** [comment] 2023-02-22 23:41
Hi @ecederstrand I am facing a similar issue, so I am replying here instead of creating a new one. I have gone through everything discussed in this thread, even the part about manually deleting exchangelib from sitepackages and reinstalling it from git. However, the issue still prevails for me. My code snippet is as follows:
```
items = account.calendar.filter(subject='SampleMeeting')
    with open(r'C:\Users\*****\Python\PythonProjects\CalendarAutomation\out\outfile.txt', 'wt') as g:
        for item in items:
            print(item.subject, item.organizer, item.start, item._start_timezone, item.end, item._end_timezone, file = g)
``
The content of outfile.txt is:
SampleMeeting Mailbox(name='Khadka, Mandeep', email_address='**************', routing_type='SMTP', mailbox_type='Mailbox') 2023-02-28 13:30:00+00:00 Europe/Berlin 2023-02-28 14:00:00+00:00 Europe/Berlin
SampleMeeting Mailbox(name='Khadka, Mandeep', email_address='**************', routing_type='SMTP', mailbox_type='Mailbox') 2023-02-27 09:00:00+00:00 Europe/Berlin 2023-02-27 09:30:00+00:00 Europe/Berlin

The timezone is printed correctly as Europe/Berlin but the start and end times are as per UTC. What am I doing wrong here?
