### ISSUE TITLE
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type

### ISSUE THREAD

**Issue by alfredbra** [ecederstrand/exchangelib#100] opened 2017-03-17 00:11 UTC
i receive the follow error message using your code example. I just want to be able to pull calendar data from outlook mailboxes. This is my code. I have to admit I am new to this and have been googling and researching as much as i can but really am stuck

year, month, day = 2017,01, 20
tz = EWSTimeZone.timezone('Australia/Brisbane')
item = CalendarItem(folder=account.calendar, subject='foo')

# Build a list of calendar items
calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
        required_attendees = [Attendee(
            mailbox=Mailbox(email_address='user1@example.com'),
            response_type='Accept'
        )]
    ))

# bulk_update() and bulk_delete() methods are also supported.
res = account.calendar.bulk_create(items=calendar_items)

 File "/var/www/xibo/autoupdater/calendar/exchangelib/exchangelib/folders.py", line 2241, in get_distinguished
    shape=shape
  File "/var/www/xibo/autoupdater/calendar/exchangelib/exchangelib/services.py", line 260, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/var/www/xibo/autoupdater/calendar/exchangelib/exchangelib/services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, xml=msg_xml)
  File "/var/www/xibo/autoupdater/calendar/exchangelib/exchangelib/services.py", line 250, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type.

**Comment by ecederstrand** [comment] 2017-03-17 22:42
Can you post the exact code that gives this error? I can't reproduce with the code you posted above. Which version of exchangelib was this with? And which Exchange version are you testing against?

**Comment by alfredbra** [comment] 2017-03-17 23:16
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody
 
config = Configuration(
     server='email.domain.com',
     credentials=Credentials(username='Dom\\user', password='pass'),
     auth_type=NTLM,
     verify_ssl=False
)
account = Account(primary_smtp_address='allan.wilesmith@health.qld.gov.au', config=config,
                   access_type=DELEGATE)
 
 
#m = Message(
#    account= Account(primary_smtp_address='Email@email.com', config=config,
#                   access_type=DELEGATE),
#    subject='na',
#    body='na',
#    to_recipients=[Mailbox(email_address='')]
#)
#m.send()

year, month, day = 2017,01, 20
tz = EWSTimeZone.timezone('Australia/Brisbane')
item = CalendarItem(folder=account.calendar, subject='foo')
 
# Build a list of calendar items
calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
        required_attendees = [Attendee(
            mailbox=Mailbox(email_address='user1@example.com'),
            response_type='Accept'
        )]
    ))
 
# bulk_update() and bulk_delete() methods are also supported.
res = account.calendar.bulk_create(items=calendar_items)
print(res)

**Comment by alfredbra** [comment] 2017-03-17 23:16
I can send email ok. Using exchange 2007

**Comment by ecederstrand** [comment] 2017-03-17 23:30
The formatting in your post is really messed up. You can format code as python in GitHub posts by putting it within triple back-quotes and specifying the language, like this:

\```python
your_python_code = 'Here'
\```

Try doing that. Then it's a lot easier for me to copy-paste the code and test it locally.

**Comment by alfredbra** [comment] 2017-03-17 23:38
'''python
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody
 
config = Configuration(
     server='email.email.com,
     credentials=Credentials(username='dom\\user', password='pass'),
     auth_type=NTLM,
     verify_ssl=False
)
account = Account(primary_smtp_address='Email@email.com', config=config,
                   access_type=DELEGATE)
 
 
#m = Message(
#    account= Account(primary_smtp_address='Email@email.com', config=config,
#                   access_type=DELEGATE),
#    subject='na',
#    body='na',
#    to_recipients=[Mailbox(email_address='')]
#)
#m.send()
year, month, day = 2017,01, 20
tz = EWSTimeZone.timezone('Australia/Brisbane')
item = CalendarItem(folder=account.calendar, subject='foo')
 
# Build a list of calendar items
calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
        required_attendees = [Attendee(
            mailbox=Mailbox(email_address='user1@example.com'),
            response_type='Accept'
        )]
    ))
 
# bulk_update() and bulk_delete() methods are also supported.
res = account.calendar.bulk_create(items=calendar_items)
print(res)

'''

**Comment by alfredbra** [comment] 2017-03-17 23:42
```python
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q
from exchangelib.folders import Calendar, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody
 
config = Configuration(
     server='email.com.au',
     credentials=Credentials(username='Dom\\user', password='pass'),
     auth_type=NTLM,
     verify_ssl=False
)
account = Account(primary_smtp_address='Email@email.com', config=config,
                   access_type=DELEGATE)
 
 
#m = Message(
#    account= Account(primary_smtp_address='', config=config,
#                   access_type=DELEGATE),
#    subject='na',
#    body='na',
#    to_recipients=[Mailbox(email_address='')]
#)
#m.send()
year, month, day = 2017,01, 20
tz = EWSTimeZone.timezone('Australia/Brisbane')
item = CalendarItem(folder=account.calendar, subject='foo')
 
# Build a list of calendar items
calendar_items = []
for hour in range(7, 17):
    calendar_items.append(CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        categories=['foo', 'bar'],
        required_attendees = [Attendee(
            mailbox=Mailbox(email_address='user1@example.com'),
            response_type='Accept'
        )]
    ))
 
# bulk_update() and bulk_delete() methods are also supported.
res = account.calendar.bulk_create(items=calendar_items)
print(res)
```

**Comment by ecederstrand** [comment] 2017-03-28 10:50
I'm sorry, but I cannot reproduce with the latest checkout. Please try to install `exchangelib` from GitHub and see if this still occurs. If so, please paste the full XML response containing the `ErrorInvalidPropertyRequest` message here. You can get it by enabling standard `DEBUG` logging and running your code again.

**Comment by robjuffermans** [comment] 2017-04-02 08:24
Hi, I have a similar problem when I iterate over the results from account.inbox.all()

I'm using Exchange 2007. Here's the XML send to the server and the response:

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007_SP1" /></s:Header><s:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>IdOnly</t:BaseShape></m:ItemShape><m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="100" Offset="0" /><m:ParentFolderIds><t:FolderId ChangeKey="AQAAABYAAACbhmPzad87QZSvNTXEkAQvARi+2sB0" Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNAAuAAAAAAAbBm7H+5ImR4NP9z03/oWvAQA/0N/VVapzRYfATxMbQxrWAAABSbFAAAA=" /></m:ParentFolderIds></m:FindItem></s:Body></s:Envelope>'
Response data: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Header><t:ServerVersionInfo MajorVersion="8" MinorVersion="1" MajorBuildNumber="436" MinorBuildNumber="0" Version="Exchange2007_SP1" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" /></soap:Header><soap:Body><m:FindItemResponse xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><m:ResponseMessages><m:FindItemResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:RootFolder IndexedPagingOffset="17" TotalItemsInView="17" IncludesLastItemInRange="true"><t:Items><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAWHeMJzNAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAWHeW8WH" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAWHeMJzKAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAWHeWXwP" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAWHeMJzJAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAWHeWS7w" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx27AAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkV9Dvd" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx2CAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkV7Lsa" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx1zAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkV5bkG" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx08AAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkV1iCC" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx0GAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkVwty2" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARkVpx0EAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARkVwJZ+" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARjDvlfvAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARjEGYNY" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARjDvleZAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARjECBj6" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARjDvleKAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARjEBz59" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvARjDvleDAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvARjEGiZy" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAPJRY6AuAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAPJRhszv" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAPJP3fylAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAPJQPxV7" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAPJP3fykAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAPJQPxV5" /></t:Message><t:Message><t:ItemId Id="AAMkADJiZmFhZmRiLTBjOGEtNGFkYy04YmRmLWQ2YjlkMjNjYjRlNABGAAAAAAAbBm7H+5ImR4NP9z03/oWvBwA/0N/VVapzRYfATxMbQxrWAAABSbFAAACbhmPzad87QZSvNTXEkAQvAPJP3fyZAAA=" ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAPJQMoQF" /></t:Message></t:Items></m:RootFolder></m:FindItemResponseMessage></m:ResponseMessages></m:FindItemResponse></soap:Body></soap:Envelope>

**** RESPONSE ****
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Header><t:ServerVersionInfo MajorVersion="8" MinorVersion="1" MajorBuildNumber="436" MinorBuildNumber="0" Version="Exchange2007_SP1" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" /></soap:Header><soap:Body><m:GetItemResponse xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><m:ResponseMessages><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Property is not valid for this object type.</m:MessageText><m:ResponseCode>ErrorInvalidPropertyRequest</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="calendar:End" /></m:MessageXml><m:Items /></m:GetItemResponseMessage></m:ResponseMessages></m:GetItemResponse></soap:Body></soap:Envelope>

DEBUG:exchangelib.util:Session 28312 thread -1235215504: Useful response from https://webmail.vanilia.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server webmail.vanilia.com: Releasing session 28312
DEBUG:exchangelib.services:Trying API version Exchange2007_SP1 for account r.juffermans@vanilia.com
DEBUG:exchangelib.services:GetItem._get_elements result 1 of 1 is ready
Traceback (most recent call last):
  File "scan.py", line 382, in <module>
    send_receive_mailbox(username, password)
  File "scan.py", line 369, in send_receive_mailbox
    for mail in mails:
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/queryset.py", line 253, in __iter__
    for val in result_formatter(self._query()):
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/account.py", line 400, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=only_fields):
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/services.py", line 456, in _pool_requests
    for elem in elems:
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/services.py", line 268, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/services.py", line 242, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.8.1-py3.6.egg/exchangelib/services.py", line 258, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyRequest: Property is not valid for this object type. (FieldURI='calendar:End')

**Comment by robjuffermans** [comment] 2017-04-02 08:33
Think Exchange 2007doesn't support these fields. Fixed when I applied this in folders.py

class Messages(Folder):                                                                                                                                                                                                                             

    CONTAINER_CLASS = 'IPF.Note'                                                                                                                                                                                                                    
    supported_item_models = (Message, )  # RJ: , MeetingRequest, MeetingResponse, MeetingCancellation                                                                                                                                               
                                                                                                                                                                                                                          
    __slots__ = Folder.__slots__

**Comment by ecederstrand** [comment] 2017-04-03 09:29
Thanks for the analysis! This will be fixed in #87

**Comment by ecederstrand** [comment] 2017-04-11 09:39
Hi, I just committed a fix to disable the `start` and `end` fields for meeting requests on Exchange 2007. Can you please test again? I don't have an Exchange 2007 server handy myself.

**Closed** 2017-04-11 09:38 UTC

**Comment by robjuffermans** [comment] 2017-04-11 20:13
Just tested with latest version and it now works correctly. Thanks!

I see that the GetAttchment method isn't implemented for Exchange 2007. How should you get the attachment instead?

**Comment by ecederstrand** [comment] 2017-04-11 20:15
I actually have no idea how to get attachments on Exchange 2007. You'll have to do some research on that :-)

**Comment by ecederstrand** [comment] 2017-04-11 21:10
It serms GetAttachment may be supported on Exchange2007 after all. You could try to remove the check and see if it works om your server

**Comment by robjuffermans** [comment] 2017-04-12 19:54
Indeed it also works on Exchange 2007!

**Comment by ecederstrand** [comment] 2017-04-12 20:07
Thanks! Fixed in https://github.com/ecederstrand/exchangelib/commit/9f428584d49ebb97c899aac2a8687f47c183ee55
