### ISSUE TITLE
CASError: UnauthenticatedRequest

### ISSUE THREAD

**Issue by olschultz** [ecederstrand/exchangelib#411] opened 2018-05-14 12:45 UTC
Hello, 
I've got the problem, that I'm not able to get my code running.
The only thing I want to do, is reading out the latest E-Mail and download the attachment of it.
That's the code I want to run:

```python
from exchangelib import Credentials, Account, Folder
import os

credentials = Credentials('example.test@mail.com', 'password')
account = Account('example.test@mail.com', credentials=credentials, autodiscover=True)
for item in account.inbox.all().order_by('-datetime_received')[:1]:
    for attachment in item.attachments:
        fpath = os.path.join("path/to/destination", attachment.name)
        with open(fpath, 'wb') as f:
            f.write(attachment.content)
```

And here is the response, that I get when I try to run the Code:

```
CASError: CAS error: UnauthenticatedRequest
```

Does anyone of you know how to fix the problem, or what excactly causes the problem?
Thanks for your help in advance.

**Comment by ecederstrand** [comment] 2018-05-14 13:16
Can you please post the entire stacktrace, so we can see where the error comes from?

**Comment by olschultz** [comment] 2018-05-14 13:27
Yes sure, here it is:

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "Z:/Olivers Automatisierung/bla.py", line 45, in <module>
    account = Account('example.test@mail.com', credentials=credentials, autodiscover=True)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\account.py", line 82, in __init__
    credentials=credentials)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\autodiscover.py", line 209, in discover
    return _try_autodiscover(hostname=domain, credentials=credentials, email=email)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\autodiscover.py", line 238, in _try_autodiscover
    has_ssl=True)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\autodiscover.py", line 308, in _autodiscover_hostname
    r = _get_response(protocol=autodiscover_protocol, email=email)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\autodiscover.py", line 374, in _get_response
    headers=DEFAULT_HEADERS.copy(), data=data, allow_redirects=True)

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\util.py", line 539, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception

  File "C:\Users\schuoli\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\util.py", line 585, in _raise_response_errors
    raise CASError(cas_error=cas_error, response=r)

CASError: CAS error: UnauthenticatedRequest

**Comment by ecederstrand** [comment] 2018-05-15 07:10
Ok, so that is an error thrown by the server during the autodiscover process. I haven't seen this specific error before, but the previous `CASError`s have been internal errors happening in an Exchange cluster.

Is this error persistent, or does it only happen occasionally? Are you able to successfully complete an autodiscover test for the same account at  https://testconnectivity.microsoft.com ?

**Comment by olschultz** [comment] 2018-05-15 07:47
This error is consistent, I mean the first two times I want to try the code I get a ReadTimeout: HTTPSConnectionPool(host='autodiscover.foo.com', port=443): Read timed out. (read timeout=10), but afterwords I only get this specific CASError.

I've tried to test my connectivity and got this report: 

Exchange Web Services synchronization, notification, availability, and Automatic Replies.
  | Not all tests of Exchange Web Services tasks completed.

  | The Microsoft Connectivity Analyzer is attempting to test Autodiscover for example@mail.com.
  | Testing Autodiscover failed.

  | Attempting each method of contacting the Autodiscover service.
  | The Autodiscover service couldn't be contacted successfully by any method.

Attempting to test potential Autodiscover URL https://foo.com:443/Autodiscover/Autodiscover.xml
  | Testing of this potential Autodiscover URL failed.

Attempting to resolve the host name tui.com in DNS.
  | The host name resolved successfully.

Testing TCP port 443 on host tui.com to ensure it's listening and open.
  | The port was opened successfully.

Testing the SSL certificate to make sure it's valid.
  | The certificate passed all validation requirements.

Checking the IIS configuration for client certificate authentication.
  | Client certificate authentication wasn't detected.

Attempting to send an Autodiscover POST request to potential Autodiscover URLs.
  | Autodiscover settings weren't obtained when the Autodiscover POST request was sent.

**Comment by ecederstrand** [comment] 2018-05-15 07:52
Since the connectivity test also failed, there's not much we can do, either. Autodiscovery is simply broken for your domain. You'll have to raise this with your email hosting provider.

**Comment by olschultz** [comment] 2018-05-15 08:36
Okay thanks for your help so far, I'm going to give you some advice when I know a bit more on how to fix the problem.
The only strange thing is, that it worked on like one specific friday, but haven't worked before oder after this day, so I may need to figure out what happened on this day.

**Comment by ecederstrand** [comment] 2018-05-23 14:52
Closing. Feel free to provide any useful information here if you manage to find the cause of this.

**Closed by ecederstrand** 2018-05-23 14:52 UTC

**Comment by olschultz** [comment] 2018-06-08 07:34
I solved the problem by not using the autodiscover and I guess, that there is a firewall at my company, that blocks the autodiscover process.
