### ISSUE TITLE
Read emails with same domain as the used account

### ISSUE THREAD

**Issue by sa-ghi** [ecederstrand/exchangelib#1023] opened 2021-11-15 17:14 UTC
Hi,
It looks like we are not able to find and read emails  sent from the same domain as the account we are connected to. 
For example, we wuold like to read emails from user1@mydomain.com connecting to the acoount of user2@mydomain.com, but new incoming emails are not found.
We are using the following code

```python
self.account.inbox.filter(datetime_received__range=(exchangelib.EWSDateTime.from_datetime(dateRange['start']),
                                                                                  exchangelib.EWSDateTime.from_datetime(dateRange['end'])),
				       sender__contains__in=senderList)
```

Thanks a lot.

**Comment by thefedoration** [comment] 2021-11-16 17:16
I did some digging into this issue [here](https://github.com/ecederstrand/exchangelib/issues/913#issuecomment-847265522). 

I'm not sure if it's on exchange or exchangelib, what what I found is that:
- filtering **exact** email using sender works as expected: `sender__icontains=email@company.com` or `sender@company.com` for all emails
- filtering partial email works for external domains: `sender__icontains=@othercompany.com`
- filtering partial emails for same domain works for OneOff mailboxes (in my case it was transactional email accounts, not real exchange mailboxes)
- the only way I managed to consistently filter for parts of email addresses for both internal + external domains was to use the [EWS querystring format](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype) like `account.inbox.filter("from:somedomain.com")`


FYI: Pros of using querystring filtrers over default filter queries:
- supports consistent filtering for to/from fields, unlike default filter queries
- supports filtering on cc/bcc which is not supported at all with filter queries

Cons
- can't run querystring filters on FolderCollections, can query one folder at a time only
- less options for filter fields available
- validation doesn't happen in exchangelib or ews, will just return 0 results if your query is incorrect

**Comment by ecederstrand** [comment] 2021-11-16 21:50
Thanks for the explanation again, @thefedoration !

I'm closing this issue, as it's essentially a duplicate of #913 which has all the details.

**Closed by ecederstrand** 2021-11-16 21:50 UTC
