### ISSUE TITLE
Saving message to disk

### ISSUE THREAD

**Issue by honzasram** [ecederstrand/exchangelib#421] opened 2018-06-03 20:04 UTC
Hi, 

I'm trying to create app, which is dumping email to disk. It has to be Outlook readable so I guess .msg extension is required as these email is something as archive and from time to time somebody need read it. 
Can this library also format and dump messages to file? Is it even possible except case where I interact with Outlook application?

Thanks

**Comment by ecederstrand** [comment] 2018-06-04 06:11
There's no explicit support for dump formats. I believe most email clients can read a .eml file where the you save the contents of the `mime_content` field.

**Comment by ecederstrand** [comment] 2018-06-04 23:14
Closing as duplicate of https://github.com/ecederstrand/exchangelib/issues/143 Feel free to reopen if you have additional issues :-)

**Closed by ecederstrand** 2018-06-04 23:14 UTC
