### ISSUE TITLE
Support for MIME "multipart/signed" certificates

### ISSUE THREAD

**Issue by macdorman** [ecederstrand/exchangelib#328] opened 2018-01-14 21:34 UTC
Support for MIME "multipart/signed" certificates

**Comment by ecederstrand** [comment] 2018-01-15 10:01
Are you referring to the `UserSMIMECertificate` and `MSExchangeCertificate` fields on the `Contact` items (as listed in https://github.com/ecederstrand/exchangelib/issues/203)?

**Comment by ecederstrand** [comment] 2018-01-18 17:10
@macdorman There's not enough context in your description for me to understand what you're actually asking for. Please elaborate.

**Comment by macdorman** [comment] 2018-01-19 22:47
Outlook has the security option to digitally sign a message with the sender's certificate.

**Comment by ecederstrand** [comment] 2018-01-20 08:37
Unless Outlook implements email signing in a non-standard way, I think this is handled just as well outside of exchangelib. See e.g. https://stackoverflow.com/questions/10496902/pgp-signing-multipart-e-mails-with-python on how to sign your email messages in Python.

**Comment by ecederstrand** [comment] 2018-01-24 14:12
Closing as duplicate of #331 which has more details.

**Closed by ecederstrand** 2018-01-24 14:12 UTC
